export const APP_ROLES=["Admin Total","Gerencia","Admin","Finanzas","Operaciones","Bodega","Supervisora"] as const;
export type AppRole=typeof APP_ROLES[number];
export const CAPABILITIES={SURVEY_REGISTER:"survey.register",SURVEY_LINK_MANAGE:"survey.link.manage",SUPPLY_MANAGE:"supply.manage",PURCHASE_ORDER_MANAGE:"purchase_order.manage",RECEIPT_REGISTER:"receipt.register",INVENTORY_ADJUST:"inventory.adjust",DISPATCH_MANAGE:"dispatch.manage",DELIVERY_REGISTER:"delivery.register",ROUTE_ACCESS:"route.access",ROUTE_MANAGE:"route.manage"} as const;
export type Capability=typeof CAPABILITIES[keyof typeof CAPABILITIES];
const CAPABILITY_ROLES:Record<Capability,readonly AppRole[]>={[CAPABILITIES.SURVEY_REGISTER]:["Admin Total","Gerencia","Admin","Operaciones","Supervisora"],[CAPABILITIES.SURVEY_LINK_MANAGE]:["Admin Total","Gerencia","Admin","Operaciones","Supervisora"],[CAPABILITIES.SUPPLY_MANAGE]:["Admin Total","Gerencia","Admin","Operaciones"],[CAPABILITIES.PURCHASE_ORDER_MANAGE]:["Admin Total","Gerencia","Admin","Operaciones"],[CAPABILITIES.RECEIPT_REGISTER]:["Admin Total","Admin","Operaciones","Bodega"],[CAPABILITIES.INVENTORY_ADJUST]:["Admin Total","Gerencia","Admin","Operaciones","Bodega"],[CAPABILITIES.DISPATCH_MANAGE]:["Admin Total","Admin","Operaciones","Bodega"],[CAPABILITIES.DELIVERY_REGISTER]:["Admin Total","Admin","Operaciones","Bodega","Supervisora"],[CAPABILITIES.ROUTE_ACCESS]:["Admin Total","Gerencia","Admin","Operaciones","Bodega","Supervisora"],[CAPABILITIES.ROUTE_MANAGE]:["Admin Total","Gerencia","Admin","Operaciones","Bodega"]};
export const MODULES_BY_ROLE:Record<AppRole,readonly string[]>={"Admin Total":["inicio","maestros","campañas","levantamientos","abastecimiento","oc","finanzas","recepcion","inventario","despacho","auditoria","respaldos"],"Gerencia":["inicio","maestros","campañas","levantamientos","abastecimiento","oc","finanzas","recepcion","inventario","despacho","auditoria"],"Admin":["inicio","maestros","campañas","levantamientos","abastecimiento","oc","recepcion","despacho"],"Finanzas":["finanzas"],"Operaciones":["inicio","campañas","levantamientos","abastecimiento","oc","recepcion","inventario","despacho"],"Bodega":["inicio","recepcion","inventario","despacho"],"Supervisora":["inicio","levantamientos","abastecimiento","recepcion","despacho"]};
export function rolesFor(capability:Capability):AppRole[]{return [...CAPABILITY_ROLES[capability]]}
export function roleCan(role:string|undefined|null,capability:Capability):boolean{return Boolean(role)&&CAPABILITY_ROLES[capability].includes(role as AppRole)}
export function modulesForRole(role:string|undefined|null):string[]{return role&&role in MODULES_BY_ROLE?[...MODULES_BY_ROLE[role as AppRole]]:["inicio"]}
