import "server-only";
import {readFile} from "node:fs/promises";
import path from "node:path";
import {PDFDocument,StandardFonts,rgb,type PDFFont,type PDFPage} from "pdf-lib";

export type DispatchPdfLine={code?:string|null;product:string;family?:string|null;presentation?:string|null;unit?:string|null;quantity:number};
export type DispatchPdfInput={guideNumber:string;internalNumber?:string|null;client:string;clientRut?:string|null;contract:string;installation:string;address?:string|null;observations?:string|null;responsible?:string|null;recipientName?:string|null;recipientRut?:string|null;recipientRole?:string|null;recipientEmail?:string|null;createdAt?:string|null;deliveredAt?:string|null;signature?:string|null;lines:DispatchPdfLine[]};

const LETTER:[number,number]=[612,792];
const NAVY=rgb(11/255,45/255,91/255),TEAL=rgb(13/255,155/255,145/255),LINE=rgb(174/255,184/255,189/255),TEXT=rgb(20/255,35/255,45/255),MUTED=rgb(91/255,102/255,112/255),PALE=rgb(247/255,250/255,248/255),WHITE=rgb(1,1,1);
function safe(v:unknown,fallback="—"){const s=String(v??"").replace(/[\u0000-\u001F\u007F]/g," ").trim();return s||fallback}
function wrap(text:string,font:PDFFont,size:number,maxWidth:number){const words=safe(text).split(/\s+/).filter(Boolean),out:string[]=[];let line="";for(const word of words){const test=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(test,size)<=maxWidth)line=test;else{if(line)out.push(line);line=word}}if(line)out.push(line);return out.length?out:["—"]}
function dateOnly(v?:string|null){if(!v)return "—";const d=new Date(v);return Number.isNaN(d.getTime())?safe(v):new Intl.DateTimeFormat("es-CL",{timeZone:"America/Santiago",day:"2-digit",month:"2-digit",year:"numeric"}).format(d).replaceAll("/","-")}
function dateTime(v?:string|null){if(!v)return "____-____-________ · ____:____";const d=new Date(v);if(Number.isNaN(d.getTime()))return safe(v);const day=dateOnly(v),time=new Intl.DateTimeFormat("es-CL",{timeZone:"America/Santiago",hour:"2-digit",minute:"2-digit"}).format(d);return `${day} · ${time}`}
function campaign(v?:string|null){return String(v||"").replace(/^CAMPAÑA:[^·]+·?\s*/,"").trim()||"Sin observaciones"}

export async function generarGuiaPdf(input:DispatchPdfInput){
 const pdf=await PDFDocument.create(),regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);let logo:any=null;try{logo=await pdf.embedPng(await readFile(path.join(process.cwd(),"public","alemsi-logo.png")))}catch{}
 const margin=24,width=LETTER[0]-margin*2;let page!:PDFPage,y=0;
 const header=()=>{page=pdf.addPage(LETTER);y=LETTER[1]-32;if(logo){const scale=Math.min(105/logo.width,42/logo.height);page.drawImage(logo,{x:margin,y:y-40,width:logo.width*scale,height:logo.height*scale})}else page.drawText("ALEMSI",{x:margin,y:y-20,size:14,font:bold,color:NAVY});page.drawText("ALEMSI",{x:142,y:y-10,size:14,font:bold,color:NAVY});page.drawText("GUÍA DE ENTREGA DE MATERIALES",{x:142,y:y-25,size:8.5,font:bold,color:TEXT});page.drawText("Documento interno/logístico - No constituye DTE tributario del SII",{x:142,y:y-37,size:6.2,font:regular,color:MUTED});const bx=430,bw=158;page.drawRectangle({x:bx,y:y-47,width:bw,height:48,borderColor:LINE,borderWidth:.7});page.drawText("N.º interno",{x:bx+8,y:y-11,size:6.5,font:bold,color:MUTED});page.drawText(safe(input.internalNumber||input.guideNumber),{x:bx+8,y:y-27,size:11,font:bold,color:NAVY});page.drawText(`Fecha: ${dateOnly(input.createdAt)}`,{x:bx+8,y:y-40,size:6.5,font:regular,color:TEXT});y-=58};
 const ensure=(h:number)=>{if(y-h<45)header()};
 const boxField=(label:string,value:string,x:number,top:number,w:number,h=24)=>{page.drawRectangle({x,y:top-h,width:w,height:h,borderColor:LINE,borderWidth:.55});page.drawText(label,{x:x+5,y:top-9,size:6.3,font:bold,color:MUTED});wrap(value,bold,7.5,w-10).slice(0,2).forEach((line,i)=>page.drawText(line,{x:x+5,y:top-19-i*8,size:7.5,font:bold,color:TEXT}))};
 const tableHeader=()=>{const xs=[margin,margin+34,margin+113,margin+405,margin+489,margin+543,margin+width];page.drawRectangle({x:margin,y:y-20,width,height:20,color:PALE,borderColor:LINE,borderWidth:.6});["N.º","Código","Descripción del material","Presentación","Unidad","Cant."].forEach((t,i)=>page.drawText(t,{x:xs[i]+4,y:y-13,size:6.5,font:bold,color:TEXT}));for(const x of xs.slice(1,-1))page.drawLine({start:{x,y},end:{x,y:y-20},thickness:.45,color:LINE});y-=20};
 header();
 boxField("Cliente",safe(input.client),margin,y,226);boxField("RUT cliente",safe(input.clientRut),margin+226,y,112);boxField("Contrato",safe(input.contract),margin+338,y,width-338);y-=24;
 boxField("Instalación",safe(input.installation),margin,y,width);y-=24;
 boxField("Responsable entrega",safe(input.responsible,"Se registrará al confirmar entrega"),margin,y,width,28);y-=28;
 boxField("Dirección de entrega",safe(input.address),margin,y,width);y-=31;
 tableHeader();
 for(let index=0;index<input.lines.length;index++){
  const item=input.lines[index],product=wrap(item.product,bold,7.1,280),family=item.family?wrap(item.family,regular,6.1,280):[],presentation=wrap(item.presentation||"—",regular,6.8,74),rowLines=Math.max(product.length+family.length,presentation.length,1),h=Math.max(24,12+rowLines*8);
  if(y-h<150){header();tableHeader()}
  const xs=[margin,margin+34,margin+113,margin+405,margin+489,margin+543,margin+width];page.drawRectangle({x:margin,y:y-h,width,height:h,borderColor:LINE,borderWidth:.5,color:WHITE});for(const x of xs.slice(1,-1))page.drawLine({start:{x,y},end:{x,y:y-h},thickness:.4,color:LINE});page.drawText(String(index+1),{x:xs[0]+5,y:y-15,size:7,font:regular,color:TEXT});page.drawText(safe(item.code),{x:xs[1]+4,y:y-15,size:6.8,font:regular,color:TEXT});product.forEach((line,i)=>page.drawText(line,{x:xs[2]+4,y:y-14-i*8,size:7.1,font:bold,color:TEXT}));family.forEach((line,i)=>page.drawText(line,{x:xs[2]+4,y:y-14-(product.length+i)*8,size:6.1,font:regular,color:MUTED}));presentation.forEach((line,i)=>page.drawText(line,{x:xs[3]+4,y:y-15-i*8,size:6.8,font:regular,color:TEXT}));page.drawText(safe(item.unit),{x:xs[4]+4,y:y-15,size:6.8,font:regular,color:TEXT});page.drawText(String(Number(item.quantity||0)),{x:xs[5]+12,y:y-15,size:7.2,font:bold,color:TEXT});y-=h;
 }
 ensure(128);y-=7;page.drawRectangle({x:margin,y:y-38,width,height:38,borderColor:LINE,borderWidth:.55});page.drawText("Campaña / período de entrega",{x:margin+6,y:y-11,size:6.5,font:bold,color:MUTED});wrap(campaign(input.observations),regular,7,width-12).slice(0,3).forEach((line,i)=>page.drawText(line,{x:margin+6,y:y-23-i*8,size:7,font:regular,color:TEXT}));y-=45;
 page.drawRectangle({x:margin,y:y-78,width,height:78,borderColor:LINE,borderWidth:.6});page.drawText("RECIBÍ CONFORME",{x:margin+6,y:y-12,size:8,font:bold,color:TEXT});const left=margin+6,mid=margin+214,sigX=margin+405;page.drawText("Nombre",{x:left,y:y-28,size:6.2,font:bold,color:MUTED});page.drawText(safe(input.recipientName,"________________________________"),{x:left,y:y-39,size:7.2,font:bold,color:TEXT});page.drawText("RUT",{x:mid,y:y-28,size:6.2,font:bold,color:MUTED});page.drawText(safe(input.recipientRut,"________________"),{x:mid,y:y-39,size:7.2,font:bold,color:TEXT});page.drawText("Cargo / receptor",{x:left,y:y-52,size:6.2,font:bold,color:MUTED});page.drawText(safe(input.recipientRole,"________________"),{x:left,y:y-64,size:7.2,font:bold,color:TEXT});page.drawText("Correo informado en terreno",{x:mid,y:y-52,size:6.2,font:bold,color:MUTED});page.drawText(safe(input.recipientEmail,"________________"),{x:mid,y:y-64,size:7,font:bold,color:TEXT});page.drawText("Fecha / hora",{x:left,y:y-75,size:6.2,font:bold,color:MUTED});page.drawText(dateTime(input.deliveredAt),{x:left+62,y:y-75,size:7,font:bold,color:TEXT});page.drawText("Firma",{x:sigX,y:y-28,size:6.2,font:bold,color:MUTED});
 if(input.signature&&/^data:image\/(png|jpeg);base64,/i.test(input.signature)){try{const [meta,data]=input.signature.split(",",2),img=/png/i.test(meta)?await pdf.embedPng(Buffer.from(data,"base64")):await pdf.embedJpg(Buffer.from(data,"base64")),scale=Math.min(125/img.width,43/img.height,1);page.drawImage(img,{x:sigX,y:y-72,width:img.width*scale,height:img.height*scale})}catch{page.drawText("________________________",{x:sigX,y:y-52,size:7,font:regular,color:TEXT})}}else page.drawText("________________________",{x:sigX,y:y-52,size:7,font:regular,color:TEXT});
 const pages=pdf.getPages();pages.forEach((p,i)=>{p.drawText(`Guía interna ALEMSI · ${safe(input.internalNumber||input.guideNumber)}`,{x:margin,y:20,size:6.2,font:regular,color:MUTED});const label=`Página ${i+1} de ${pages.length}`;p.drawText(label,{x:LETTER[0]-margin-regular.widthOfTextAtSize(label,6.2),y:20,size:6.2,font:regular,color:MUTED})});return Buffer.from(await pdf.save())
}
