import "server-only";
import {PDFDocument,StandardFonts,rgb,type PDFFont,type PDFPage} from "pdf-lib";

export type DispatchPdfLine={code?:string|null;product:string;presentation?:string|null;unit?:string|null;quantity:number};
export type DispatchPdfInput={guideNumber:string;internalNumber?:string|null;status:string;client:string;contract:string;installation:string;address?:string|null;observations?:string|null;responsible?:string|null;recipientName?:string|null;recipientRut?:string|null;recipientRole?:string|null;recipientEmail?:string|null;deliveredAt?:string|null;signature?:string|null;lines:DispatchPdfLine[]};

const LETTER:[number,number]=[612,792];
const NAVY=rgb(11/255,45/255,91/255),TEAL=rgb(13/255,155/255,145/255),GREEN=rgb(8/255,122/255,70/255),LIGHT=rgb(247/255,250/255,248/255),LINE=rgb(215/255,225/255,220/255),TEXT=rgb(20/255,35/255,45/255),MUTED=rgb(91/255,102/255,112/255);
function safe(v:unknown){return String(v??"").replace(/[\u0000-\u001F\u007F]/g," ").trim()||"—"}
function wrap(text:string,font:PDFFont,size:number,maxWidth:number){const words=safe(text).split(/\s+/).filter(Boolean),out:string[]=[];let line="";for(const word of words){const test=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(test,size)<=maxWidth)line=test;else{if(line)out.push(line);line=word}}if(line)out.push(line);return out.length?out:["—"]}
function dateCL(v?:string|null){if(!v)return "—";const d=new Date(v);return Number.isNaN(d.getTime())?safe(v):new Intl.DateTimeFormat("es-CL",{dateStyle:"short",timeStyle:"short",timeZone:"America/Santiago"}).format(d)}

export async function generarGuiaPdf(input:DispatchPdfInput){
 const pdf=await PDFDocument.create(),regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);const margin=42,width=LETTER[0]-margin*2;let page!:PDFPage,y=0;
 const header=()=>{page=pdf.addPage(LETTER);y=LETTER[1]-48;page.drawText("ALEMSI",{x:margin,y,size:16,font:bold,color:NAVY});page.drawText("GUÍA DE ENTREGA DE MATERIALES",{x:LETTER[0]-margin-220,y:y-1,size:11,font:bold,color:NAVY});page.drawText(`Guía ${safe(input.guideNumber)}`,{x:LETTER[0]-margin-220,y:y-18,size:8,font:bold,color:TEAL});page.drawLine({start:{x:margin,y:y-30},end:{x:LETTER[0]-margin,y:y-30},thickness:1.4,color:TEAL});y-=50};
 const need=(h:number)=>{if(y-h<62)header()};
 const field=(label:string,value:string,x:number,top:number,w:number)=>{page.drawText(label.toUpperCase(),{x,y:top,size:6.8,font:bold,color:MUTED});wrap(value,bold,8.5,w).slice(0,2).forEach((line,i)=>page.drawText(line,{x,y:top-12-i*10,size:8.5,font:bold,color:TEXT}))};
 header();page.drawText("DATOS DE LA ENTREGA",{x:margin,y,size:8,font:bold,color:GREEN});y-=15;page.drawRectangle({x:margin,y:y-88,width,height:88,color:LIGHT,borderColor:LINE,borderWidth:.7});field("Cliente",safe(input.client),margin+10,y-14,235);field("Contrato",safe(input.contract),margin+275,y-14,235);field("Instalación",safe(input.installation),margin+10,y-49,235);field("Estado",safe(input.status),margin+275,y-49,105);field("Fecha entrega",dateCL(input.deliveredAt),margin+390,y-49,120);y-=106;
 page.drawText("MATERIALES ENTREGADOS",{x:margin,y,size:8,font:bold,color:GREEN});y-=14;page.drawRectangle({x:margin,y:y-21,width,height:21,color:NAVY});[["Código",margin+7],["Producto",margin+72],["Presentación",margin+300],["Unidad",margin+405],["Cantidad",margin+465]].forEach(([t,x])=>page.drawText(String(t),{x:Number(x),y:y-14,size:7,font:bold,color:rgb(1,1,1)}));y-=21;
 for(const item of input.lines){const prod=wrap(item.product,bold,8,218),pres=wrap(item.presentation||"—",regular,7.8,95),h=Math.max(27,13+Math.max(prod.length,pres.length)*10);if(y-h<120){header();page.drawText("MATERIALES ENTREGADOS (CONTINUACIÓN)",{x:margin,y,size:8,font:bold,color:GREEN});y-=14;page.drawRectangle({x:margin,y:y-21,width,height:21,color:NAVY});y-=21}page.drawRectangle({x:margin,y:y-h,width,height:h,color:rgb(1,1,1),borderColor:LINE,borderWidth:.5});[margin+64,margin+292,margin+397,margin+457].forEach(x=>page.drawLine({start:{x,y},end:{x,y:y-h},thickness:.4,color:LINE}));page.drawText(safe(item.code),{x:margin+7,y:y-17,size:7.5,font:regular,color:TEXT});prod.forEach((l,i)=>page.drawText(l,{x:margin+72,y:y-17-i*10,size:8,font:bold,color:TEXT}));pres.forEach((l,i)=>page.drawText(l,{x:margin+300,y:y-17-i*10,size:7.8,font:regular,color:TEXT}));page.drawText(safe(item.unit),{x:margin+405,y:y-17,size:7.8,font:regular,color:TEXT});page.drawText(String(Number(item.quantity||0)),{x:margin+472,y:y-17,size:8.5,font:bold,color:NAVY});y-=h}
 need(150);y-=18;page.drawText("RECEPCIÓN",{x:margin,y,size:8,font:bold,color:GREEN});y-=15;page.drawRectangle({x:margin,y:y-78,width,height:78,color:LIGHT,borderColor:LINE,borderWidth:.7});field("Receptor",safe(input.recipientName),margin+10,y-14,205);field("RUT",safe(input.recipientRut),margin+230,y-14,120);field("Cargo",safe(input.recipientRole),margin+365,y-14,145);field("Responsable entrega",safe(input.responsible),margin+10,y-48,245);field("Correo receptor",safe(input.recipientEmail),margin+275,y-48,235);y-=94;
 if(input.signature&&/^data:image\/(png|jpeg);base64,/i.test(input.signature)){try{const [meta,data]=input.signature.split(",",2),bytes=Buffer.from(data,"base64"),img=/png/i.test(meta)?await pdf.embedPng(bytes):await pdf.embedJpg(bytes),scale=Math.min(160/img.width,55/img.height,1);need(80);page.drawText("FIRMA RECEPTOR",{x:margin,y,size:7,font:bold,color:MUTED});page.drawImage(img,{x:margin,y:y-62,width:img.width*scale,height:img.height*scale});y-=70}catch{}}
 if(input.observations&&input.observations.trim()){need(55);page.drawText("OBSERVACIONES",{x:margin,y,size:7,font:bold,color:MUTED});y-=12;wrap(input.observations,regular,7.8,width).slice(0,4).forEach((l,i)=>page.drawText(l,{x:margin,y:y-i*10,size:7.8,font:regular,color:TEXT}))}
 const pages=pdf.getPages();pages.forEach((p,i)=>{p.drawLine({start:{x:margin,y:37},end:{x:LETTER[0]-margin,y:37},thickness:.6,color:LINE});p.drawText("ALEMSI · Guía de entrega de materiales",{x:margin,y:23,size:7,font:regular,color:MUTED});const label=`Página ${i+1} de ${pages.length}`;p.drawText(label,{x:LETTER[0]-margin-regular.widthOfTextAtSize(label,7),y:23,size:7,font:regular,color:MUTED})});return Buffer.from(await pdf.save())
}
