import "server-only";
import {createClient} from "@supabase/supabase-js";
import {renderEmail,type EmailModule} from "@/lib/email-engine";
import {enviarCorreoSmtp,type SmtpAttachment} from "@/lib/email-smtp";
import {generarGuiaPdf} from "@/lib/dispatch-pdf";
import {archiveGuidePdf} from "@/lib/google-drive";

type ProcessResult={id:string;processed:boolean;ok:boolean;status:string;errorType?:string|null;blockedRecipients?:string[]};
function serviceDb(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.trim(),key=process.env.SUPABASE_SECRET_KEY?.trim();if(!url||!key)return null;return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function syncRelatedStatus(db:any,item:any,status:string){if(item.related_table==="dispatches"&&item.email_type==="signed_delivery_copy")await db.from("dispatches").update({email_status:status}).eq("id",item.related_id)}
function campaignFromObservations(value?:string|null){const text=String(value||"");const marked=text.match(/CAMPAÑA:([^\n\r|]+)/i)?.[1]?.trim();if(marked&&!/^[0-9a-f-]{36}$/i.test(marked))return marked;const readable=text.match(/(?:Campaña|CAMPAÑA)\s*[:\-]\s*([^\n\r|]+)/)?.[1]?.trim();return readable&&!/^[0-9a-f-]{36}$/i.test(readable)?readable:null}
async function signedGuideAttachment(db:any,dispatchId:string):Promise<SmtpAttachment[]>{try{const {data:d,error}=await db.from("dispatches").select("id,internal_number,guide_number,observations,recipient_name,recipient_email,recipient_rut,recipient_role,recipient_signature,created_at,delivered_at,delivered_by,installations(name,address,commune,city,region,contracts(name,clients(legal_name,rut))),dispatch_lines(required_qty,delivered_qty,materials(name,family,supplier_code,presentation,unit))").eq("id",dispatchId).single();if(error||!d)return[];let responsible="—";if(d.delivered_by){const {data:p}=await db.from("user_profiles").select("full_name,email").eq("id",d.delivered_by).maybeSingle();responsible=p?.full_name||p?.email||"—"}const installation:any=Array.isArray(d.installations)?d.installations[0]:d.installations,contract:any=Array.isArray(installation?.contracts)?installation.contracts[0]:installation?.contracts,client:any=Array.isArray(contract?.clients)?contract.clients[0]:contract?.clients;const filename=`Guia-${d.internal_number||d.guide_number||dispatchId}.pdf`;const pdf=await generarGuiaPdf({guideNumber:d.internal_number||d.guide_number||dispatchId,internalNumber:d.internal_number,client:client?.legal_name||"—",clientRut:client?.rut||"—",contract:contract?.name||"—",installation:installation?.name||"—",address:[installation?.address,installation?.commune,installation?.city,installation?.region].filter(Boolean).join(" · "),observations:d.observations,responsible,recipientName:d.recipient_name,recipientRut:d.recipient_rut,recipientRole:d.recipient_role,recipientEmail:d.recipient_email,createdAt:d.created_at,deliveredAt:d.delivered_at,signature:d.recipient_signature,lines:(d.dispatch_lines||[]).map((l:any)=>({code:l.materials?.supplier_code,product:l.materials?.name||"Material",family:l.materials?.family,presentation:l.materials?.presentation,unit:l.materials?.unit,quantity:d.delivered_at?Number(l.delivered_qty||0):Number(l.required_qty||0)}))});try{const archived=await archiveGuidePdf({pdf,filename,client:client?.legal_name||"Sin cliente",contract:contract?.name||"Sin contrato",campaign:campaignFromObservations(d.observations)||"Sin campaña",year:new Date(d.delivered_at||d.created_at||Date.now()).getFullYear()});await db.from("activity_log").insert({entity_type:"dispatch",entity_id:d.id,action:"guide_pdf_archived_drive",new_data:{drive_file_id:archived.id,drive_file_name:archived.name,drive_url:archived.webViewLink,drive_folder_id:archived.folderId}})}catch(driveError){console.error("DISPATCH_DRIVE_ARCHIVE_ERROR",driveError);await db.from("activity_log").insert({entity_type:"dispatch",entity_id:d.id,action:"guide_pdf_drive_pending",new_data:{error:driveError instanceof Error?driveError.message:String(driveError)}})}return[{filename,contentType:"application/pdf",content:pdf}]}catch(error){console.error("DISPATCH_PDF_ERROR",error);return[]}}
export async function processQueuedEmailById(id:string):Promise<ProcessResult>{const db=serviceDb();if(!db)return{id,processed:false,ok:false,status:"Pendiente",errorType:"configuration"};const {data:item,error:loadError}=await db.from("email_queue").select("*").eq("id",id).maybeSingle();if(loadError||!item)return{id,processed:false,ok:false,status:"No encontrado",errorType:loadError?.message||"not_found"};if(item.status!=="Pendiente")return{id,processed:false,ok:item.status==="Enviado",status:item.status};const {data:claimed,error:claimError}=await db.from("email_queue").update({status:"Procesando"}).eq("id",id).eq("status","Pendiente").select("id").maybeSingle();if(claimError||!claimed)return{id,processed:false,ok:false,status:"Pendiente",errorType:claimError?.message||"already_claimed"};const payload:any=item.payload||{},module=(item.module||payload.module||"alerts") as EmailModule,event=String(item.event_code||payload.event||item.email_type||"notification"),summary=String(payload.summary||"Existe una actualización en el proceso de materiales."),html=renderEmail({module,event,title:item.subject,summary,facts:payload.facts||{},actionUrl:payload.action_url||null});const attachments=item.related_table==="dispatches"&&item.email_type==="signed_delivery_copy"?await signedGuideAttachment(db,String(item.related_id)):[];const delivery=await enviarCorreoSmtp({to:item.to_addresses,cc:item.cc_addresses||[],subject:item.subject,text:summary,html,attachments});const attempts=Number(item.attempts||0)+1;if(delivery.ok){const now=new Date().toISOString();await db.from("email_queue").update({status:"Enviado",attempts,sent_at:now,last_error:null}).eq("id",id);await syncRelatedStatus(db,item,"Enviado");await db.from("email_events").insert({email_queue_id:id,event_type:"sent",provider_message_id:null,detail:{module,event,provider:"smtp",status:delivery.status,attachments:attachments.map(a=>a.filename)}});return{id,processed:true,ok:true,status:"Enviado"}}const blocked=delivery.errorType==="recipient_policy",finalFailure=!blocked&&attempts>=5,status=blocked?"Bloqueado":finalFailure?"Fallido":"Pendiente",lastError=blocked?`Bloqueado por política de destinatarios del entorno: ${(delivery.blockedRecipients||[]).join(", ")}`:`SMTP ${delivery.errorType}`;await db.from("email_queue").update({status,attempts,last_error:lastError}).eq("id",id);await syncRelatedStatus(db,item,status);await db.from("email_events").insert({email_queue_id:id,event_type:blocked?"blocked":"failed",provider_message_id:null,detail:{module,event,provider:"smtp",status:lastError}});return{id,processed:true,ok:false,status,errorType:delivery.errorType,blockedRecipients:delivery.blockedRecipients}}
export async function processPendingEmailQueue(limit=20){const db=serviceDb();if(!db)return{processed:0,results:[] as ProcessResult[],configurationError:true};const {data:queue,error}=await db.from("email_queue").select("id").eq("status","Pendiente").lt("attempts",5).order("created_at").limit(Math.max(1,Math.min(limit,50)));if(error)throw error;const results:ProcessResult[]=[];for(const item of queue||[])results.push(await processQueuedEmailById(String(item.id)));return{processed:results.filter(x=>x.processed).length,results,configurationError:false}}
