"use client";
import {useMemo,useState} from "react";
import {closeCampaign,createCampaign} from "@/app/actions";
import {forceCloseCampaign,justifyCampaignInstallation} from "@/app/campaign-actions";
import {deleteCampaignSafe} from "@/app/delete-campaign-action";
import type {ClientInstallationGroup} from "@/components/modules/ClientInstallationsModule";

type CampaignInstallation={id?:string;installation_id?:string;status:string;justification?:string|null;installations?:{id?:string;name?:string|null;region?:string|null;contracts?:{name?:string|null;clients?:{legal_name?:string|null}|null}|null}|null};
type CampaignRow={id:string;label:string;status:string;created_at:string;contracts?:{name?:string|null;clients?:{legal_name?:string|null}|null}|null;campaign_installations?:CampaignInstallation[]};
const campaignInfo=(label:string)=>{try{const value=JSON.parse(label);return typeof value?.name==="string"?value:{name:label,periodicity:"No indicada",clientCount:null}}catch{return{name:label,periodicity:"No indicada",clientCount:null}}};

export default function CampaignsModule({campaigns,clients,onOpenSurveys}:{campaigns:CampaignRow[];clients:ClientInstallationGroup[];onOpenSurveys?:(campaignId:string,installationId?:string)=>void}){
 const [showNew,setShowNew]=useState(false);
 const [selectedClientIds,setSelectedClientIds]=useState<string[]>([]);
 const [adminCampaign,setAdminCampaign]=useState<string|null>(null);
 const [openCampaign,setOpenCampaign]=useState<string|null>(null);
 const selectableClients=clients.filter(client=>client.contracts.some(contract=>contract.installations?.length));
 const selectedUniverse=useMemo(()=>clients.filter(client=>selectedClientIds.includes(client.id)).flatMap(client=>client.contracts.flatMap(contract=>(contract.installations||[]).map(installation=>({client:client.legal_name,contract:contract.name,installation})))),[clients,selectedClientIds]);
 const toggleClient=(clientId:string)=>setSelectedClientIds(current=>current.includes(clientId)?current.filter(id=>id!==clientId):[...current,clientId]);
 return <section className="panel campaignModule"><div className="catalogIntro"><div><h2>Universo cerrado de levantamientos</h2><p>Una campaña puede reunir varios clientes; sus contratos e instalaciones activas forman un único universo.</p></div><button type="button" onClick={()=>setShowNew(value=>!value)}>+ Nueva campaña</button></div>
 {showNew&&<form action={createCampaign} className="adminForm campaignForm"><h3>Crear campaña</h3><div className="campaignFields"><label>Nombre de campaña<input name="name" required placeholder="Ej.: Levantamiento zona sur"/></label><label>Periodicidad<select name="periodicity" required defaultValue="Mensual"><option>Mensual</option><option>Bimensual</option><option>Trimestral</option><option>Cuatrimestral</option><option>Semestral</option><option>Personalizada</option></select></label></div><fieldset className="campaignClientPicker"><legend>Clientes del maestro</legend>{selectableClients.map(client=>{const installationCount=client.contracts.reduce((sum,contract)=>sum+(contract.installations?.length||0),0);return <label key={client.id}><input type="checkbox" name="client_ids" value={client.id} checked={selectedClientIds.includes(client.id)} onChange={()=>toggleClient(client.id)}/><span><b>{client.legal_name}</b><small>{client.contracts.length} contratos · {installationCount} instalaciones</small></span></label>})}</fieldset><div className="campaignUniversePreview"><div className="campaignUniverseHead"><b>Instalaciones resultantes</b><span>{selectedUniverse.length} instalaciones</span></div>{selectedUniverse.length?<div className="campaignUniverseList">{selectedUniverse.map(({client,contract,installation})=><article key={installation.id}><span><b>{installation.name}</b><small>{client} · {contract}</small></span><small>{[installation.commune,installation.city,installation.region].filter(Boolean).join(" · ")||"Ubicación pendiente"}</small></article>)}</div>:<p>Selecciona uno o varios clientes para visualizar su universo de instalaciones.</p>}</div><button disabled={!selectedClientIds.length}>Crear campaña</button></form>}
 <div className="campaignList">{campaigns.length?campaigns.map(c=>{const info=campaignInfo(c.label);const universe=c.campaign_installations||[];const total=universe.length;const completed=universe.filter(item=>item.status==="Completada").length;const justified=universe.filter(item=>item.status==="Justificada"||(!item.status.includes("Completada")&&!!item.justification?.trim())).length;const pending=universe.filter(item=>item.status!=="Completada"&&item.status!=="Justificada"&&!item.justification?.trim()).length;const adminOpen=adminCampaign===c.id;const campaignOpen=openCampaign===c.id;return <article key={c.id} className="campaignCard"><div className="campaignCardHead"><span><b>{info.name}</b><small>{info.periodicity} · {info.clientCount??1} clientes · {total} instalaciones</small></span><em>{c.status}</em></div><button type="button" className="campaignSurveyLink" onClick={()=>setOpenCampaign(campaignOpen?null:c.id)}>{campaignOpen?"Cerrar campaña":"Abrir campaña"}</button><div className="campaignMetrics"><span><b>{total}</b><small>Esperadas</small></span><span><b>{completed}</b><small>Completadas</small></span><span><b>{justified}</b><small>Justificadas</small></span><span className={pending?"pending":"complete"}><b>{pending}</b><small>Pendientes reales</small></span></div>
 {campaignOpen&&<div className="surveyUniverse"><div className="campaignUniverseHead"><b>Instalaciones de la campaña</b><span>{total} instalaciones</span></div>{universe.length?<div className="surveyInstallationList">{universe.map(item=>{const installationId=item.installation_id||item.installations?.id||item.id||"";return <article className="surveyInstallationCard" key={installationId}><span><small>Cliente</small><b>{item.installations?.contracts?.clients?.legal_name||"Cliente pendiente"}</b></span><span><small>Contrato</small><b>{item.installations?.contracts?.name||"Contrato pendiente"}</b></span><span><small>Instalación</small><b>{item.installations?.name||"Instalación pendiente"}</b></span><span><small>Región</small><b>{item.installations?.region||"Región pendiente"}</b></span><span><small>Estado</small><b className="surveyStatus">{item.status}</b></span><button type="button" onClick={()=>onOpenSurveys?.(c.id,installationId)}>Abrir conteo</button></article>})}</div>:<div className="empty"><b>Esta campaña no tiene instalaciones guardadas</b></div>}<button type="button" className="campaignSurveyLink" onClick={()=>onOpenSurveys?.(c.id)}>Ver todos los levantamientos</button></div>}
 {c.status==="Abierta"&&<>{pending===0&&<form action={closeCampaign} className="campaignClose"><input type="hidden" name="campaign_id" value={c.id}/><button>Cerrar campaña</button><small>Universo completo o formalmente justificado.</small></form>}<button type="button" className="campaignSurveyLink" onClick={()=>setAdminCampaign(adminOpen?null:c.id)}>{adminOpen?"Ocultar controles":"Administrar campaña"}</button></>}
 {adminOpen&&<div className="adminForm campaignForm"><h3>Control administrativo</h3><p>Las instalaciones sin materiales pueden justificarse para que no bloqueen el cierre. El cierre forzado conserva la campaña y su trazabilidad.</p>{universe.filter(item=>item.status!=="Completada"&&item.status!=="Justificada").map(item=>{const installationId=item.installation_id||item.installations?.id||item.id||"";return <form action={justifyCampaignInstallation} key={installationId} className="campaignClose"><input type="hidden" name="campaign_id" value={c.id}/><input type="hidden" name="installation_id" value={installationId}/><span><b>{item.installations?.name||"Instalación"}</b><small>{item.installations?.contracts?.clients?.legal_name||""} · {item.installations?.region||"Región pendiente"}</small></span><input name="reason" required minLength={4} placeholder="Ej.: Sin materiales configurados / No corresponde levantamiento"/><button>Justificar</button></form>})}
 <form action={forceCloseCampaign} className="campaignClose"><input type="hidden" name="campaign_id" value={c.id}/><input name="reason" required minLength={5} placeholder="Motivo obligatorio del cierre forzado"/><button>Forzar cierre</button><small>Marca los pendientes como justificados y conserva todos los levantamientos existentes.</small></form>
 <form action={deleteCampaignSafe} className="campaignClose" onSubmit={event=>{if(!window.confirm(`¿Eliminar definitivamente la campaña ${info.name}? Esta acción eliminará sus levantamientos de prueba y no se puede deshacer.`))event.preventDefault()}}><input type="hidden" name="campaign_id" value={c.id}/><input type="hidden" name="confirmation" value="ELIMINAR"/><button>Eliminar campaña</button><small>Solo se permite antes de abastecimiento, compras locales o despachos. Elimina también sus levantamientos de prueba.</small></form></div>}
 </article>}):<div className="empty"><b>Sin campañas</b><span>Crea la primera campaña seleccionando uno o varios clientes.</span></div>}</div>
 </section>;
}
