"use client";
import {useMemo,useState} from "react";
import {closeCampaign,createCampaign} from "@/app/actions";
import type {ClientInstallationGroup} from "@/components/modules/ClientInstallationsModule";

type CampaignInstallation={id:string;status:string;justification?:string|null;installations?:{name?:string|null}|null};
type CampaignRow={id:string;label:string;status:string;created_at:string;contracts?:{name?:string|null;clients?:{legal_name?:string|null}|null}|null;campaign_installations?:CampaignInstallation[]};
const campaignInfo=(label:string)=>{try{const value=JSON.parse(label);return typeof value?.name==="string"?value:{name:label,periodicity:"No indicada",clientCount:null}}catch{return{name:label,periodicity:"No indicada",clientCount:null}}};

export default function CampaignsModule({campaigns,clients}:{campaigns:CampaignRow[];clients:ClientInstallationGroup[]}){
 const [showNew,setShowNew]=useState(false);
 const [selectedClientIds,setSelectedClientIds]=useState<string[]>([]);
 const selectableClients=clients.filter(client=>client.contracts.some(contract=>contract.installations?.length));
 const selectedUniverse=useMemo(()=>clients.filter(client=>selectedClientIds.includes(client.id)).flatMap(client=>client.contracts.flatMap(contract=>(contract.installations||[]).map(installation=>({client:client.legal_name,contract:contract.name,installation})))),[clients,selectedClientIds]);
 const toggleClient=(clientId:string)=>setSelectedClientIds(current=>current.includes(clientId)?current.filter(id=>id!==clientId):[...current,clientId]);
 return <section className="panel campaignModule"><div className="catalogIntro"><div><h2>Universo cerrado de levantamientos</h2><p>Una campaña puede reunir varios clientes; sus contratos e instalaciones activas forman un único universo.</p></div><button type="button" onClick={()=>setShowNew(value=>!value)}>+ Nueva campaña</button></div>
 {showNew&&<form action={createCampaign} className="adminForm campaignForm"><h3>Crear campaña</h3><div className="campaignFields"><label>Nombre de campaña<input name="name" required placeholder="Ej.: Levantamiento zona sur"/></label><label>Periodicidad<select name="periodicity" required defaultValue="Mensual"><option>Mensual</option><option>Bimensual</option><option>Trimestral</option><option>Cuatrimestral</option><option>Semestral</option><option>Personalizada</option></select></label></div><fieldset className="campaignClientPicker"><legend>Clientes del maestro</legend>{selectableClients.map(client=>{const installationCount=client.contracts.reduce((sum,contract)=>sum+(contract.installations?.length||0),0);return <label key={client.id}><input type="checkbox" name="client_ids" value={client.id} checked={selectedClientIds.includes(client.id)} onChange={()=>toggleClient(client.id)}/><span><b>{client.legal_name}</b><small>{client.contracts.length} contratos · {installationCount} instalaciones</small></span></label>})}</fieldset><div className="campaignUniversePreview"><div className="campaignUniverseHead"><b>Instalaciones resultantes</b><span>{selectedUniverse.length} instalaciones</span></div>{selectedUniverse.length?<div className="campaignUniverseList">{selectedUniverse.map(({client,contract,installation})=><article key={installation.id}><span><b>{installation.name}</b><small>{client} · {contract}</small></span><small>{[installation.commune,installation.city,installation.region].filter(Boolean).join(" · ")||"Ubicación pendiente"}</small></article>)}</div>:<p>Selecciona uno o varios clientes para visualizar su universo de instalaciones.</p>}</div><button disabled={!selectedClientIds.length}>Crear campaña</button></form>}
 <div className="campaignList">{campaigns.length?campaigns.map(c=>{const info=campaignInfo(c.label);const universe=c.campaign_installations||[];const total=universe.length;const completed=universe.filter(item=>item.status==="Completada").length;const pending=total-completed;const unjustified=universe.filter(item=>item.status!=="Completada"&&!item.justification?.trim()).length;return <article key={c.id} className="campaignCard"><div className="campaignCardHead"><span><b>{info.name}</b><small>{info.periodicity} · {info.clientCount??1} clientes · {total} instalaciones</small></span><em>{c.status}</em></div><div className="campaignMetrics"><span><b>{total}</b><small>Esperadas</small></span><span><b>{completed}</b><small>Completadas</small></span><span className={pending?"pending":"complete"}><b>{pending}</b><small>Pendientes</small></span></div>{c.status==="Abierta"&&<form action={closeCampaign} className="campaignClose"><input type="hidden" name="campaign_id" value={c.id}/><button disabled={unjustified>0}>Cerrar campaña</button><small>{unjustified>0?`${unjustified} pendientes sin justificar impiden el cierre`:"Universo completo o pendientes formalmente justificadas"}</small></form>}</article>}):<div className="empty"><b>Sin campañas</b><span>Crea la primera campaña seleccionando uno o varios clientes.</span></div>}</div>
 </section>;
}
