"use client";
import {useMemo,useState} from "react";
import {createClientWithContract,createInstallation,importClientsInstallationsCsv,renameContract} from "@/app/actions";
import {loadInstallationMaterialProfile,saveInstallationMaterialConfig} from "@/app/material-profile-actions";

type Installation={id:string;name:string;address?:string|null;region?:string|null;city?:string|null;commune?:string|null;delivery_contact_name?:string|null;delivery_email?:string|null;delivery_phone?:string|null;phone?:string|null;general_email?:string|null;active?:boolean};
type Contract={id:string;name:string;code?:string|null;installations:Installation[]};
export type ClientInstallationGroup={id:string;legal_name:string;rut?:string|null;business_center?:string|null;contracts:Contract[]};
type Assignment={id?:string;material_id:string;authorized:boolean;authorized_qty:number;net_limit?:number|null;coverage_status?:string|null;notes?:string|null};
type Limit={material_id:string;period_type?:string|null;period_value?:number|null;quantity_limit?:number|null;net_amount_limit?:number|null};
type ProfileMaterial={id:string;family?:string|null;name:string;presentation?:string|null;unit?:string|null;supplier_code?:string|null;current_net_price?:number|null};
const clean=(value:unknown)=>String(value??"").trim(); const normalized=(value:unknown)=>clean(value).toLocaleLowerCase("es-CL");
const periodValue=(type:string)=>({Mensual:1,Bimensual:2,Trimestral:3,Cuatrimestral:4,Semestral:6}[type]||null);

export default function ClientInstallationsModule({clients}:{clients:ClientInstallationGroup[]}){
 const [search,setSearch]=useState(""),[showNewClient,setShowNewClient]=useState(false),[newInstallation,setNewInstallation]=useState<string|null>(null),[editingContract,setEditingContract]=useState<string|null>(null);
 const [profileTarget,setProfileTarget]=useState<{contract:Contract;installation:Installation;client:string}|null>(null),[profileMaterials,setProfileMaterials]=useState<ProfileMaterial[]>([]),[profileRows,setProfileRows]=useState<Record<string,{assigned:boolean;authorized_qty:number;period_type:string;quantity_limit:number|null;net_amount_limit:number|null;notes:string}>>({}),[profileSearch,setProfileSearch]=useState(""),[profileLoading,setProfileLoading]=useState(false),[profileMessage,setProfileMessage]=useState("");
 const rows=useMemo(()=>clients.map(client=>({...client,contracts:(client.contracts||[]).map(contract=>({...contract,installations:(contract.installations||[]).filter(item=>!search||[client.legal_name,contract.name,item.name,item.region,item.city,item.commune].some(value=>normalized(value).includes(normalized(search))))})).filter(contract=>!search||normalized(client.legal_name).includes(normalized(search))||normalized(contract.name).includes(normalized(search))||contract.installations.length)})).filter(client=>!search||normalized(client.legal_name).includes(normalized(search))||client.contracts.length),[clients,search]);
 const total=clients.reduce((sum,client)=>sum+client.contracts.reduce((inner,contract)=>inner+contract.installations.length,0),0);
 const filteredMaterials=useMemo(()=>profileMaterials.filter(m=>!profileSearch||[m.family,m.supplier_code,m.name,m.presentation,m.unit].some(v=>normalized(v).includes(normalized(profileSearch)))),[profileMaterials,profileSearch]);
 async function openProfile(client:string,contract:Contract,installation:Installation){setProfileTarget({client,contract,installation});setProfileLoading(true);setProfileMessage("");try{const data=await loadInstallationMaterialProfile(contract.id,installation.id);const materials=(data.materials||[]) as ProfileMaterial[];setProfileMaterials(materials);const assignments=new Map((data.assignments as Assignment[]).map(x=>[x.material_id,x]));const limits=new Map((data.limits as Limit[]).map(x=>[x.material_id,x]));const next:typeof profileRows={};for(const m of materials){const a=assignments.get(m.id),l=limits.get(m.id);next[m.id]={assigned:Boolean(a?.authorized),authorized_qty:Number(a?.authorized_qty||0),period_type:String(l?.period_type||""),quantity_limit:l?.quantity_limit==null?null:Number(l.quantity_limit),net_amount_limit:l?.net_amount_limit==null?(a?.net_limit==null?null:Number(a.net_limit)):Number(l.net_amount_limit),notes:String(a?.notes||"")};}setProfileRows(next);}catch(error:any){setProfileMessage(error?.message||"No fue posible cargar la configuración");}finally{setProfileLoading(false)}}
 async function saveMaterial(materialId:string){if(!profileTarget)return;const row=profileRows[materialId];if(!row)return;setProfileMessage("Guardando...");try{await saveInstallationMaterialConfig({contract_id:profileTarget.contract.id,installation_id:profileTarget.installation.id,material_id:materialId,assigned:row.assigned,authorized_qty:row.assigned?Number(row.authorized_qty||0):0,period_type:row.assigned&&row.period_type?row.period_type:null,period_value:row.assigned&&row.period_type?periodValue(row.period_type):null,quantity_limit:row.assigned?row.quantity_limit:null,net_amount_limit:row.assigned?row.net_amount_limit:null,coverage_status:row.assigned?"included":"not_included",notes:row.notes||null});setProfileMessage("Guardado y verificado en Supabase");}catch(error:any){setProfileMessage(error?.message||"Error al guardar");}}
 const patch=(id:string,values:Partial<(typeof profileRows)[string]>)=>setProfileRows(current=>({...current,[id]:{...current[id],...values}}));
 return <section className="panel clientCore"><div className="catalogIntro"><div><h2>Clientes e instalaciones</h2><p>Núcleo único: cliente, contrato, instalaciones y materiales autorizados.</p></div><span className="catalogCount">{clients.length} clientes · {total} instalaciones</span></div><div className="coreToolbar"><label>Buscar cliente o instalación<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Dirección del Trabajo, Curanilahue..."/></label>{search&&<button type="button" className="clearFilters" onClick={()=>setSearch("")}>Limpiar</button>}<button type="button" onClick={()=>setShowNewClient(v=>!v)}>+ Nuevo cliente</button></div>
 <div className="masterActions"><a className="downloadLink" href="/plantilla-clientes-instalaciones.csv" download>Descargar plantilla CSV</a><form action={importClientsInstallationsCsv}><input type="file" name="file" accept=".csv,text/csv" required/><button>Cargar clientes e instalaciones</button></form><small>Una fila por instalación. Si no hay sucursal, usa el nombre del cliente como instalación.</small></div>
 {showNewClient&&<form action={createClientWithContract} className="adminForm"><h3>Crear cliente y contrato inicial</h3><input name="legal_name" required placeholder="Nombre del cliente"/><input name="contract_name" required placeholder="Nombre del contrato"/><input name="business_center" placeholder="Centro de negocio (opcional)"/><button>Guardar cliente</button></form>}
 <div className="clientGroups">{rows.map(client=>{const count=client.contracts.reduce((s,c)=>s+c.installations.length,0);return <details className="clientGroup" key={client.id} open={Boolean(search)}><summary><span><b>{client.legal_name}</b><small>{client.business_center||"Centro de negocio pendiente"}</small></span><em>{count} instalaciones</em></summary><div className="contractGroups">{client.contracts.map(contract=><div className="contractGroup" key={contract.id}><div className="contractTitle"><span><b>{contract.name}</b>{contract.code&&<small>Código: {contract.code}</small>}</span><span className="contractActions"><button type="button" onClick={()=>setEditingContract(editingContract===contract.id?null:contract.id)}>Editar contrato</button><button type="button" onClick={()=>setNewInstallation(newInstallation===contract.id?null:contract.id)}>+ Instalación</button></span></div>{editingContract===contract.id&&<form action={renameContract} className="inlineAdminForm"><input type="hidden" name="contract_id" value={contract.id}/><input name="name" required defaultValue={contract.name}/><button>Guardar nombre</button></form>}{newInstallation===contract.id&&<form action={createInstallation} className="adminForm installationForm"><input type="hidden" name="contract_id" value={contract.id}/><input name="name" required placeholder="Nombre instalación"/><input name="region" placeholder="Región"/><input name="city" placeholder="Ciudad"/><input name="commune" placeholder="Comuna"/><button>Agregar</button></form>}{contract.installations.length?<div className="installationGrid">{contract.installations.map(item=><article key={item.id} className={normalized(item.name)==="prueba"?"needsReview":""}><div><b>{item.name}</b><small>{[item.commune,item.city,item.region].filter(Boolean).join(" · ")||"Ubicación pendiente"}</small></div><span>{normalized(item.name)==="prueba"?"Revisar":"Activa"}</span><button type="button" onClick={()=>openProfile(client.legal_name,contract,item)}>Configurar materiales</button></article>)}</div>:<div className="associationPending"><b>Sin instalaciones</b><span>Usa “+ Instalación” para agregarla a este contrato.</span></div>}</div>)}</div></details>})}</div>{!rows.length&&<div className="empty"><b>Sin coincidencias</b></div>}
 {profileTarget&&<section className="materialProfileEditor"><div className="catalogIntro"><div><h3>Materiales autorizados · {profileTarget.installation.name}</h3><p>{profileTarget.client} · {profileTarget.contract.name}</p></div><button type="button" onClick={()=>setProfileTarget(null)}>Cerrar</button></div><div className="coreToolbar"><label>Buscar material<input value={profileSearch} onChange={e=>setProfileSearch(e.target.value)} placeholder="Código, producto o familia"/></label><span className="catalogCount">{Object.values(profileRows).filter(r=>r.assigned).length} asignados</span></div>{profileMessage&&<p className="note">{profileMessage}</p>}{profileLoading?<div className="empty">Cargando configuración...</div>:<div className="materialProfileList">{filteredMaterials.map(m=>{const row=profileRows[m.id]||{assigned:false,authorized_qty:0,period_type:"",quantity_limit:null,net_amount_limit:null,notes:""};return <article key={m.id} className={row.assigned?"assigned":""}><label className="materialProfileToggle"><input type="checkbox" checked={row.assigned} onChange={e=>patch(m.id,{assigned:e.target.checked})}/><span><b>{m.name||"Material"}</b><small>{[m.family,m.supplier_code,m.presentation,m.unit].filter(Boolean).join(" · ")}</small></span></label><label>Máximo autorizado<input type="number" min="0" step="any" disabled={!row.assigned} value={row.authorized_qty} onChange={e=>patch(m.id,{authorized_qty:Number(e.target.value)})}/></label><label>Periodicidad<select disabled={!row.assigned} value={row.period_type} onChange={e=>patch(m.id,{period_type:e.target.value})}><option value="">Sin regla</option><option>Mensual</option><option>Bimensual</option><option>Trimestral</option><option>Cuatrimestral</option><option>Semestral</option></select></label><label>Límite cantidad<input type="number" min="0" step="any" disabled={!row.assigned} value={row.quantity_limit??""} onChange={e=>patch(m.id,{quantity_limit:e.target.value===""?null:Number(e.target.value)})}/></label><label>Límite neto<input type="number" min="0" step="1" disabled={!row.assigned} value={row.net_amount_limit??""} onChange={e=>patch(m.id,{net_amount_limit:e.target.value===""?null:Number(e.target.value)})}/></label><label>Observación<input disabled={!row.assigned} value={row.notes} onChange={e=>patch(m.id,{notes:e.target.value})}/></label><button type="button" onClick={()=>saveMaterial(m.id)}>{row.assigned?"Guardar":"Retirar"}</button></article>})}</div>}</section>}
 <p className="catalogNote">La asignación usa el maestro único y queda guardada por contrato + instalación + material, con auditoría y límites reutilizables por Levantamientos y Abastecimiento.</p></section>;
}
