"use client";
import {useMemo,useState} from "react";
import {createClientWithContract,createInstallation,importClientsInstallationsCsv,renameContract} from "@/app/actions";
type Installation={id:string;name:string;region?:string|null;city?:string|null;commune?:string|null;active?:boolean};
type Contract={id:string;name:string;code?:string|null;installations:Installation[]};
export type ClientInstallationGroup={id:string;legal_name:string;business_center?:string|null;contracts:Contract[]};
const clean=(value:unknown)=>String(value??"").trim(); const normalized=(value:unknown)=>clean(value).toLocaleLowerCase("es-CL");
export default function ClientInstallationsModule({clients}:{clients:ClientInstallationGroup[]}){
 const [search,setSearch]=useState(""),[showNewClient,setShowNewClient]=useState(false),[newInstallation,setNewInstallation]=useState<string|null>(null),[editingContract,setEditingContract]=useState<string|null>(null);
 const rows=useMemo(()=>clients.map(client=>({...client,contracts:(client.contracts||[]).map(contract=>({...contract,installations:(contract.installations||[]).filter(item=>!search||[client.legal_name,contract.name,item.name,item.region,item.city,item.commune].some(value=>normalized(value).includes(normalized(search))))})).filter(contract=>!search||normalized(client.legal_name).includes(normalized(search))||normalized(contract.name).includes(normalized(search))||contract.installations.length)})).filter(client=>!search||normalized(client.legal_name).includes(normalized(search))||client.contracts.length),[clients,search]);
 const total=clients.reduce((sum,client)=>sum+client.contracts.reduce((inner,contract)=>inner+contract.installations.length,0),0);
 return <section className="panel clientCore"><div className="catalogIntro"><div><h2>Clientes e instalaciones</h2><p>Núcleo único: cliente, contrato e instalaciones asociadas.</p></div><span className="catalogCount">{clients.length} clientes · {total} instalaciones</span></div><div className="coreToolbar"><label>Buscar cliente o instalación<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Dirección del Trabajo, Curanilahue..."/></label>{search&&<button type="button" className="clearFilters" onClick={()=>setSearch("")}>Limpiar</button>}<button type="button" onClick={()=>setShowNewClient(v=>!v)}>+ Nuevo cliente</button></div>
 <div className="masterActions"><a className="downloadLink" href="/plantilla-clientes-instalaciones.csv" download>Descargar plantilla CSV</a><form action={importClientsInstallationsCsv}><input type="file" name="file" accept=".csv,text/csv" required/><button>Cargar clientes e instalaciones</button></form><small>Una fila por instalación. Si no hay sucursal, usa el nombre del cliente como instalación.</small></div>
 {showNewClient&&<form action={createClientWithContract} className="adminForm"><h3>Crear cliente y contrato inicial</h3><input name="legal_name" required placeholder="Nombre del cliente"/><input name="contract_name" required placeholder="Nombre del contrato"/><input name="business_center" placeholder="Centro de negocio (opcional)"/><button>Guardar cliente</button></form>}
 <div className="clientGroups">{rows.map(client=>{const count=client.contracts.reduce((s,c)=>s+c.installations.length,0);return <details className="clientGroup" key={client.id} open={Boolean(search)}><summary><span><b>{client.legal_name}</b><small>{client.business_center||"Centro de negocio pendiente"}</small></span><em>{count} instalaciones</em></summary><div className="contractGroups">{client.contracts.map(contract=><div className="contractGroup" key={contract.id}><div className="contractTitle"><span><b>{contract.name}</b>{contract.code&&<small>Código: {contract.code}</small>}</span><span className="contractActions"><button type="button" onClick={()=>setEditingContract(editingContract===contract.id?null:contract.id)}>Editar contrato</button><button type="button" onClick={()=>setNewInstallation(newInstallation===contract.id?null:contract.id)}>+ Instalación</button></span></div>{editingContract===contract.id&&<form action={renameContract} className="inlineAdminForm"><input type="hidden" name="contract_id" value={contract.id}/><input name="name" required defaultValue={contract.name}/><button>Guardar nombre</button></form>}{newInstallation===contract.id&&<form action={createInstallation} className="adminForm installationForm"><input type="hidden" name="contract_id" value={contract.id}/><input name="name" required placeholder="Nombre instalación"/><input name="region" placeholder="Región"/><input name="city" placeholder="Ciudad"/><input name="commune" placeholder="Comuna"/><button>Agregar</button></form>}{contract.installations.length?<div className="installationGrid">{contract.installations.map(item=><article key={item.id} className={normalized(item.name)==="prueba"?"needsReview":""}><div><b>{item.name}</b><small>{[item.commune,item.city,item.region].filter(Boolean).join(" · ")||"Ubicación pendiente"}</small></div><span>{normalized(item.name)==="prueba"?"Revisar":"Activa"}</span></article>)}</div>:<div className="associationPending"><b>Sin instalaciones</b><span>Usa “+ Instalación” para agregarla a este contrato.</span></div>}</div>)}</div></details>})}</div>{!rows.length&&<div className="empty"><b>Sin coincidencias</b></div>}<p className="catalogNote">Los cambios administrativos quedan registrados en auditoría.</p></section>;
}
