"use client";
import type {ClientProfile,MaterialState,SupplyLine,SupplyRun} from "@/lib/materiales-domain";
import {activeCampaign,clp,consolidatedFor,now,uid} from "@/lib/materiales-store";
export default function ConsolidadoModule({state,setState,profile}:{state:MaterialState;setState:(x:MaterialState)=>void;profile:ClientProfile}){
 const c=activeCampaign(state,profile.id),data=consolidatedFor(state,c),net=data.reduce((s,l)=>s+l.net,0),limit=state.limits[profile.id]||0,run=state.supplyRuns.find(x=>x.campaignId===c?.id);
 const prepare=()=>{if(!c||c.status!=="Cerrada")return;const lines:SupplyLine[]=data.map(l=>({...l,supplier:"Proveedor por definir",approvedQty:l.qty,approvedNet:l.net}));setState({...state,supplyRuns:[{id:uid("abast"),profileId:profile.id,campaignId:c.id,createdAt:now(),contractLimitNet:limit,consolidatedNet:net,approvedNet:net,lines,status:"Borrador"},...state.supplyRuns]})};
 const upd=(r:SupplyRun)=>setState({...state,supplyRuns:state.supplyRuns.map(x=>x.id===r.id?r:x)});
 const gen=()=>{if(!run)return;const groups=new Map<string,SupplyLine[]>();run.lines.filter(l=>l.approvedQty>0).forEach(l=>{const s=l.supplier||"Proveedor por definir";groups.set(s,[...(groups.get(s)||[]),l])});const ocs=[...groups.entries()].map(([supplier,ls])=>({id:uid("OC"),supplyRunId:run.id,supplier,totalNet:ls.reduce((s,l)=>s+l.approvedNet,0),receivedNet:0,status:"Emitida" as const}));setState({...state,purchaseOrders:[...ocs,...state.purchaseOrders],supplyRuns:state.supplyRuns.map(x=>x.id===run.id?{...x,status:"OC generadas"}:x)})};
 return <><h1>Consolidado / Abastecimiento</h1><p className="lead">Solo después de cerrar todos los levantamientos.</p><div className="card"><label>Límite neto del contrato</label><input type="number" value={limit||""} onChange={e=>setState({...state,limits:{...state.limits,[profile.id]:Number(e.target.value)||0}})}/></div><div className="tableWrap"><table><thead><tr><th>Producto</th><th>Cantidad</th><th>Neto</th></tr></thead><tbody>{data.length?data.map(x=><tr key={x.productId}><td><b>{x.productName}</b></td><td>{x.qty}</td><td>{clp(x.net)}</td></tr>):<tr><td colSpan={3}>Sin consolidado.</td></tr>}</tbody></table></div>{!run&&<button className="btn primary large" disabled={!c||c.status!=="Cerrada"||!data.length} onClick={prepare}>Preparar abastecimiento</button>}{run&&<div className="card sectionCard"><h2>Decisión de Gerencia</h2><div className="tableWrap"><table><thead><tr><th>Producto</th><th>Aprobar</th><th>Proveedor</th><th>Neto</th></tr></thead><tbody>{run.lines.map((l,i)=><tr key={l.productId}><td>{l.productName}</td><td><input type="number" value={l.approvedQty} onChange={e=>{const q=Number(e.target.value)||0,lines=run.lines.map((x,idx)=>idx===i?{...x,approvedQty:q,approvedNet:x.qty?x.net*(q/x.qty):0}:x);upd({...run,lines,approvedNet:lines.reduce((s,x)=>s+x.approvedNet,0)})}}/></td><td><input value={l.supplier} onChange={e=>upd({...run,lines:run.lines.map((x,idx)=>idx===i?{...x,supplier:e.target.value}:x)})}/></td><td>{clp(l.approvedNet)}</td></tr>)}</tbody></table></div>{run.status==="Borrador"?<button className="btn primary" onClick={()=>upd({...run,status:"Aprobado Gerencia"})}>Aprobar abastecimiento</button>:run.status==="Aprobado Gerencia"?<button className="btn primary" onClick={gen}>Generar OC</button>:null}</div>}</>;
}
