"use client";
import {useMemo,useState} from "react";

type Material={id?:string;name?:string|null;family?:string|null;presentation?:string|null;unit?:string|null;supplier_code?:string|null};
type SurveyLine={id?:string;material_id:string;authorized_qty?:number|null;physical_remainder?:number|null;shortage_qty?:number|null;unit_net_price?:number|null;line_net?:number|null;materials?:Material|null};
type SurveyRow={id:string;campaign_id:string;installation_id:string;status:string;confirmed_at?:string|null;shortage_net?:number|null;campaigns?:{id?:string;label?:string|null;status?:string|null}|null;installations?:{id?:string;name?:string|null;region?:string|null;contracts?:{id?:string;name?:string|null;clients?:{id?:string;legal_name?:string|null}|null}|null}|null;survey_lines?:SurveyLine[]};

const money=(n:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(n||0);
const campaignName=(label?:string|null)=>{if(!label)return "Campaña";try{const value=JSON.parse(label);return typeof value?.name==="string"?value.name:label}catch{return label}};

export default function ConsolidatedSupplyModule({surveys}:{surveys:SurveyRow[]}){
  const [campaignId,setCampaignId]=useState("");
  const [view,setView]=useState<"global"|"installation">("global");
  const campaigns=useMemo(()=>{const map=new Map<string,string>();for(const survey of surveys){if(survey.campaign_id)map.set(survey.campaign_id,campaignName(survey.campaigns?.label))}return [...map.entries()].map(([id,name])=>({id,name}));},[surveys]);
  const filtered=useMemo(()=>campaignId?surveys.filter(s=>s.campaign_id===campaignId):surveys,[surveys,campaignId]);
  const globalRows=useMemo(()=>{const map=new Map<string,any>();for(const survey of filtered){for(const line of survey.survey_lines||[]){const key=line.material_id;const current=map.get(key)||{material_id:key,material:line.materials,shortage_qty:0,line_net:0,installations:new Set<string>()};current.shortage_qty+=Number(line.shortage_qty||0);current.line_net+=Number(line.line_net||0);if(survey.installation_id)current.installations.add(survey.installation_id);map.set(key,current)}}return [...map.values()].sort((a,b)=>String(a.material?.name||"").localeCompare(String(b.material?.name||""),"es"));},[filtered]);
  const installations=useMemo(()=>{const map=new Map<string,any>();for(const survey of filtered){const inst=survey.installations;const group=map.get(survey.installation_id)||{installation_id:survey.installation_id,name:inst?.name||"Instalación",region:inst?.region||"",client:inst?.contracts?.clients?.legal_name||"Cliente",contract:inst?.contracts?.name||"Contrato",total:0,lines:[] as SurveyLine[]};for(const line of survey.survey_lines||[]){group.lines.push(line);group.total+=Number(line.line_net||0)}map.set(survey.installation_id,group)}return [...map.values()].sort((a,b)=>String(a.client).localeCompare(String(b.client),"es")||String(a.name).localeCompare(String(b.name),"es"));},[filtered]);
  const totalQty=globalRows.reduce((sum,row)=>sum+Number(row.shortage_qty||0),0);
  const totalNet=globalRows.reduce((sum,row)=>sum+Number(row.line_net||0),0);
  return <section className="panel consolidatedModule">
    <div className="catalogIntro"><div><h2>Consolidado de necesidades</h2><p>La carencia confirmada conserva su origen por instalación y se acumula en una vista global para abastecimiento.</p></div><span className="catalogCount">{filtered.length} levantamientos confirmados</span></div>
    <div className="surveyCampaignFilters"><label>Campaña<select value={campaignId} onChange={e=>setCampaignId(e.target.value)}><option value="">Todas las campañas confirmadas</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="consolidatedViewSwitch"><button type="button" className={view==="global"?"active":""} onClick={()=>setView("global")}>Consolidado global</button><button type="button" className={view==="installation"?"active":""} onClick={()=>setView("installation")}>Detalle por instalación</button></div></div>
    <div className="campaignMetrics"><span><b>{globalRows.length}</b><small>Productos con necesidad</small></span><span><b>{totalQty}</b><small>Unidades requeridas</small></span><span><b>{installations.length}</b><small>Instalaciones con carencia</small></span><span><b>{money(totalNet)}</b><small>Necesidad neta estimada</small></span></div>
    {view==="global"?<div className="table consolidatedTable">{globalRows.length?globalRows.map(row=><div className="row" key={row.material_id}><span><b>{row.material?.name||"Material"}</b><small>{[row.material?.family,row.material?.presentation,row.material?.unit].filter(Boolean).join(" · ")}</small></span><span><small>Instalaciones</small><b>{row.installations.size}</b></span><span><small>Necesidad total</small><b>{row.shortage_qty}</b></span><strong>{money(row.line_net)} neto</strong></div>):<div className="empty"><b>Sin carencias confirmadas</b><span>Los levantamientos confirmados aparecerán aquí automáticamente.</span></div>}</div>:<div className="consolidatedInstallations">{installations.length?installations.map(group=><article className="campaignCard" key={group.installation_id}><div className="campaignCardHead"><span><b>{group.name}</b><small>{group.client} · {group.contract}{group.region?` · ${group.region}`:""}</small></span><strong>{money(group.total)} neto</strong></div><div className="table">{group.lines.filter((line:SurveyLine)=>Number(line.shortage_qty||0)>0).map((line:SurveyLine)=><div className="row" key={line.id||line.material_id}><span><b>{line.materials?.name||"Material"}</b><small>{[line.materials?.presentation,line.materials?.unit].filter(Boolean).join(" · ")}</small></span><span><small>Autorizado</small><b>{Number(line.authorized_qty||0)}</b></span><span><small>Remanente</small><b>{Number(line.physical_remainder||0)}</b></span><span><small>Carencia</small><b>{Number(line.shortage_qty||0)}</b></span><strong>{money(Number(line.line_net||0))}</strong></div>)}</div></article>):<div className="empty"><b>Sin detalle disponible</b></div>}</div>}
    <p className="note">Este consolidado no pierde el vínculo de origen: cada cantidad global puede volver a cliente, contrato, instalación y levantamiento. La siguiente etapa será asignar proveedor y cantidades para generar una o varias OC.</p>
  </section>;
}
