"use client";
import Link from "next/link";
import {useMemo,useRef,useState,useTransition} from "react";
import {createDispatchV1,registerDispatchDeliveryV1,transitionDispatchV1} from "@/app/actions";
import type {MaterialCatalogRow} from "./MaterialsCatalogModule";
import type {ClientInstallationGroup} from "./ClientInstallationsModule";

type DispatchLine={id:string;material_id:string;required_qty:number|string;delivered_qty:number|string;pending_qty:number|string;materials?:{id:string;family?:string;name:string;supplier_code?:string;presentation?:string;unit?:string}};
type Dispatch={id:string;guide_number?:string;internal_number?:string;status:string;observations?:string;recipient_name?:string;recipient_email?:string;recipient_phone?:string;recipient_rut?:string;recipient_role?:string;recipient_signature?:string;created_at:string;delivered_at?:string;installations?:any;dispatch_lines:DispatchLine[]};
const buckets=["Pendientes","En preparación","Listos para despacho","En tránsito","Entregados","Con observaciones"];
const bucket=(status:string)=>status==="Borrador"||status==="Pendiente"?"Pendientes":status==="Listo para despacho"?"Listos para despacho":status==="Entregado conforme"?"Entregados":["Entrega parcial","Entrega con observaciones","Rechazado/No entregado","Anulado"].includes(status)?"Con observaciones":status;
const n=(value:unknown)=>Number(value||0);const normalize=(v:unknown)=>String(v||"").toLocaleLowerCase("es-CL");
const location=(d:Dispatch)=>d.installations||{};const contract=(d:Dispatch)=>location(d).contracts||{};const client=(d:Dispatch)=>contract(d).clients||{};

export default function DispatchDeliveryModule({dispatches,clients,materials,role}:{dispatches:Dispatch[];clients:ClientInstallationGroup[];materials:MaterialCatalogRow[];role:string}){
 const [active,setActive]=useState("Pendientes"),[showNew,setShowNew]=useState(false),[delivery,setDelivery]=useState<Dispatch|null>(null),[notice,setNotice]=useState("");
 const [filters,setFilters]=useState({q:"",client:"",contract:"",installation:"",region:"",status:""});
 const rows=useMemo(()=>dispatches.filter(d=>bucket(d.status)===active).filter(d=>{const i=location(d),c=contract(d),cl=client(d);return(!filters.q||normalize(d.guide_number).includes(normalize(filters.q)))&&(!filters.client||cl.id===filters.client)&&(!filters.contract||c.id===filters.contract)&&(!filters.installation||i.id===filters.installation)&&(!filters.region||i.region===filters.region)&&(!filters.status||d.status===filters.status)}),[dispatches,active,filters]);
 const canOperate=["Admin Total","Admin","Bodega"].includes(role);const canDeliver=canOperate||role==="Supervisora";
 const doTransition=async(d:Dispatch,status:string)=>{const reason=["Anulado","Rechazado/No entregado"].includes(status)?prompt("Motivo obligatorio:")||"":"";if(["Anulado","Rechazado/No entregado"].includes(status)&&!reason)return;try{await transitionDispatchV1(d.id,status,reason);setNotice(`Despacho actualizado a ${status}.`)}catch(e:any){alert(e.message)}};
 const regions=[...new Set(clients.flatMap(c=>c.contracts.flatMap(k=>k.installations.map(i=>i.region).filter(Boolean))))] as string[];
 return <section className="panel dispatchModule"><div className="catalogIntro"><div><h2>Despacho y entrega de materiales</h2><p>Guías internas ALEMSI, salida física, entrega y saldo pendiente con trazabilidad.</p></div>{canOperate&&<button onClick={()=>setShowNew(true)}>+ Nuevo despacho</button>}</div>
 {notice&&<div className="notice">{notice}</div>}<div className="dispatchBuckets">{buckets.map(name=><button key={name} className={active===name?"active":""} onClick={()=>setActive(name)}>{name}<b>{dispatches.filter(d=>bucket(d.status)===name).length}</b></button>)}</div>
 <div className="dispatchFilters"><select value={filters.client} onChange={e=>setFilters({...filters,client:e.target.value,contract:"",installation:""})}><option value="">Todos los clientes</option>{clients.map(c=><option value={c.id} key={c.id}>{c.legal_name}</option>)}</select><select value={filters.contract} onChange={e=>setFilters({...filters,contract:e.target.value,installation:""})}><option value="">Todos los contratos</option>{clients.filter(c=>!filters.client||c.id===filters.client).flatMap(c=>c.contracts).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><select value={filters.installation} onChange={e=>setFilters({...filters,installation:e.target.value})}><option value="">Todas las instalaciones</option>{clients.flatMap(c=>c.contracts).filter(c=>!filters.contract||c.id===filters.contract).flatMap(c=>c.installations).map(i=><option value={i.id} key={i.id}>{i.name}</option>)}</select><select value={filters.region} onChange={e=>setFilters({...filters,region:e.target.value})}><option value="">Todas las regiones</option>{regions.map(r=><option key={r}>{r}</option>)}</select><input value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})} placeholder="N.º guía"/></div>
 <div className="dispatchCards">{rows.map(d=>{const i=location(d),c=contract(d),cl=client(d),pending=d.dispatch_lines.reduce((s,l)=>s+n(l.pending_qty),0);return <article key={d.id}><div className="dispatchCardHead"><span><b>{d.internal_number||d.guide_number||"Guía interna"}</b><small>{cl.legal_name||"Cliente"} · {c.name||"Contrato"}</small></span><em>{d.status}</em></div><h3>{i.name}</h3><p>{[i.address,i.commune,i.city,i.region].filter(Boolean).join(" · ")||"Dirección pendiente"}</p><div className="dispatchTotals"><span>{d.dispatch_lines.length} materiales</span><span>{pending} unidades pendientes</span></div><div className="dispatchActions"><Link href={`/despachos/${d.id}/guia`} target="_blank">Ver guía interna</Link>{canOperate&&d.status==="Borrador"&&<button onClick={()=>doTransition(d,"En preparación")}>Preparar</button>}{canOperate&&d.status==="En preparación"&&<button onClick={()=>doTransition(d,"Listo para despacho")}>Marcar listo</button>}{canOperate&&d.status==="Listo para despacho"&&<button onClick={()=>doTransition(d,"En tránsito")}>Confirmar salida</button>}{canDeliver&&["En tránsito","Entrega parcial"].includes(d.status)&&<button onClick={()=>setDelivery(d)}>Registrar entrega</button>}{canOperate&&!['Entregado conforme','Entrega con observaciones','Anulado'].includes(d.status)&&<button className="dangerAction" onClick={()=>doTransition(d,"Anulado")}>Anular</button>}</div></article>})}{!rows.length&&<div className="empty"><b>Sin despachos en esta vista</b><span>Usa los filtros o crea un nuevo despacho.</span></div>}</div>
 {showNew&&<CreateDispatchModal clients={clients} materials={materials} close={()=>setShowNew(false)} done={()=>{setShowNew(false);setNotice("Despacho creado en Borrador.")}}/>}{delivery&&<DeliveryModal dispatch={delivery} close={()=>setDelivery(null)} done={()=>{setDelivery(null);setNotice("Entrega registrada con trazabilidad.")}}/>}
 </section>;
}

function CreateDispatchModal({clients,materials,close,done}:{clients:ClientInstallationGroup[];materials:MaterialCatalogRow[];close:()=>void;done:()=>void}){
 const [clientId,setClientId]=useState(""),[contractId,setContractId]=useState(""),[installationId,setInstallationId]=useState(""),[qty,setQty]=useState<Record<string,string>>({}),[search,setSearch]=useState(""),[pending,start]=useTransition();
 const client=clients.find(c=>c.id===clientId),contract=client?.contracts.find(c=>c.id===contractId),installation=contract?.installations.find(i=>i.id===installationId);
 const visible=materials.filter(m=>n(m.availability)>0&&(!search||[m.family,m.supplier_code,m.product,m.presentation].some(v=>normalize(v).includes(normalize(search)))));
 const submit=(form:FormData)=>{const lines=materials.map(m=>({material_id:String(m.id),quantity:n(qty[String(m.id)])})).filter(l=>l.quantity>0);if(!installationId||!lines.length){alert("Selecciona una instalación y al menos un material.");return}start(async()=>{try{await createDispatchV1({installationId,lines,observations:String(form.get("observations")||"")});done()}catch(e:any){alert(e.message)}})};
 return <div className="modalBg"><div className="modal dispatchModal"><div className="modalHead"><div><h2>Nuevo despacho</h2><p>Cliente → Contrato → Instalación</p></div><button onClick={close}>Cerrar</button></div><div className="dispatchHierarchy"><label>Cliente<select value={clientId} onChange={e=>{setClientId(e.target.value);setContractId("");setInstallationId("")}}><option value="">Seleccionar</option>{clients.map(c=><option value={c.id} key={c.id}>{c.legal_name}</option>)}</select></label><label>Contrato<select value={contractId} onChange={e=>{setContractId(e.target.value);setInstallationId("")}} disabled={!client}><option value="">Seleccionar</option>{client?.contracts.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Instalación<select value={installationId} onChange={e=>setInstallationId(e.target.value)} disabled={!contract}><option value="">Seleccionar</option>{contract?.installations.map(i=><option value={i.id} key={i.id}>{i.name}</option>)}</select></label></div>{installation&&<div className="contactSummary"><b>{installation.name}</b><span>{[installation.address,installation.commune,installation.city,installation.region].filter(Boolean).join(" · ")||"Dirección pendiente"}</span><span>Receptor: {installation.delivery_contact_name||"Pendiente"} · {installation.delivery_email||installation.general_email||"Sin correo"} · {installation.delivery_phone||installation.phone||"Sin teléfono"}</span></div>}<input className="materialSearch" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar material, familia o código"/><div className="dispatchMaterialTable"><table><thead><tr><th>Código</th><th>Producto</th><th>Presentación</th><th>Unidad</th><th>Disponible</th><th>Cantidad despacho</th></tr></thead><tbody>{visible.map(m=><tr key={m.id}><td>{m.supplier_code||"—"}</td><td><b>{m.product}</b><small>{m.family}</small></td><td>{m.presentation||"—"}</td><td>{m.unit||"—"}</td><td>{n(m.availability)}</td><td><input type="number" min="0" max={n(m.availability)} step="1" value={qty[String(m.id)]||""} onChange={e=>setQty({...qty,[String(m.id)]:e.target.value})}/></td></tr>)}</tbody></table></div><form action={submit} className="dispatchSubmit"><textarea name="observations" placeholder="Observaciones del despacho"/><button disabled={pending}>{pending?"Guardando...":"Crear despacho en borrador"}</button></form></div></div>;
}

function DeliveryModal({dispatch,close,done}:{dispatch:Dispatch;close:()=>void;done:()=>void}){
 const [amounts,setAmounts]=useState<Record<string,string>>({}),[pending,start]=useTransition(),canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false);
 const pos=(e:any)=>{const r=canvas.current!.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:(p.clientX-r.left)*(canvas.current!.width/r.width),y:(p.clientY-r.top)*(canvas.current!.height/r.height)}};
 const begin=(e:any)=>{drawing.current=true;const p=pos(e),c=canvas.current!.getContext("2d")!;c.beginPath();c.moveTo(p.x,p.y);e.preventDefault()};const move=(e:any)=>{if(!drawing.current)return;const p=pos(e),c=canvas.current!.getContext("2d")!;c.lineWidth=2;c.lineCap="round";c.strokeStyle="#073b5c";c.lineTo(p.x,p.y);c.stroke();e.preventDefault()};
 const submit=(form:FormData)=>{const lines=dispatch.dispatch_lines.map(l=>({line_id:l.id,delivered_qty:n(l.delivered_qty)+Math.min(n(l.pending_qty),n(amounts[l.id]))}));start(async()=>{try{await registerDispatchDeliveryV1({dispatchId:dispatch.id,recipientName:String(form.get("recipient_name")||""),recipientRut:String(form.get("recipient_rut")||""),recipientRole:String(form.get("recipient_role")||""),observations:String(form.get("observations")||""),signature:canvas.current?.toDataURL("image/png"),lines});done()}catch(e:any){alert(e.message)}})};
 return <div className="modalBg"><div className="modal deliveryModal"><div className="modalHead"><div><h2>Registrar entrega</h2><p>{dispatch.internal_number} · {location(dispatch).name}</p></div><button onClick={close}>Cerrar</button></div><form action={submit}><div className="deliveryLines">{dispatch.dispatch_lines.map(l=><label key={l.id}><span><b>{l.materials?.name}</b><small>Pendiente: {n(l.pending_qty)} {l.materials?.unit}</small></span><input type="number" min="0" max={n(l.pending_qty)} step="1" required value={amounts[l.id]||"0"} onChange={e=>setAmounts({...amounts,[l.id]:e.target.value})}/></label>)}</div><div className="deliveryFields"><input name="recipient_name" required defaultValue={dispatch.recipient_name||location(dispatch).delivery_contact_name||""} placeholder="Nombre receptor"/><input name="recipient_rut" required placeholder="RUT receptor"/><input name="recipient_role" placeholder="Cargo / receptor"/><textarea name="observations" placeholder="Observaciones de la entrega"/></div><label className="signatureLabel">Firma en pantalla<canvas ref={canvas} width="700" height="180" onMouseDown={begin} onMouseMove={move} onMouseUp={()=>drawing.current=false} onMouseLeave={()=>drawing.current=false} onTouchStart={begin} onTouchMove={move} onTouchEnd={()=>drawing.current=false}/><button type="button" onClick={()=>canvas.current?.getContext("2d")?.clearRect(0,0,700,180)}>Limpiar firma</button></label><button className="deliveryConfirm" disabled={pending}>{pending?"Registrando...":"Confirmar entrega"}</button></form></div></div>;
}
