"use client";
import {useEffect,useMemo,useState} from "react";
import {reconcilePurchaseDocument} from "@/app/finance-purchase-actions";
import InvoiceRecognitionTest from "@/components/modules/InvoiceRecognitionTest";
const money=(n:any)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(Number(n)||0);
const fmt=(v:any)=>v?new Intl.DateTimeFormat("es-CL",{dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"—";
const esc=(v:any)=>`"${String(v??"").replaceAll('"','""')}"`;
function download(name:string,rows:any[][]){const csv=rows.map(r=>r.map(esc).join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
export default function FinancePurchaseRegister({role,mode="purchases"}:{role:string;mode?:"purchases"|"invoices"|"orders"|"suppliers"|"reports"}){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[openId,setOpenId]=useState<string|null>(null),[from,setFrom]=useState(""),[to,setTo]=useState(""),[report,setReport]=useState("facturas");
 const load=async()=>{setLoading(true);try{const r=await fetch("/api/finance/purchases",{cache:"no-store"}),b=await r.json();if(!r.ok)throw new Error(b.error||"No se pudo cargar Finanzas");setData(b)}catch(e:any){setMessage(e?.message||"No se pudo cargar Finanzas")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const receipts=data?.receipts||[],orders=data?.orders||[],suppliers=data?.suppliers||[],dispatches=data?.dispatches||[],clients=data?.clients||[],profiles=data?.profiles||[],documents=data?.documents||[];
 const inst=useMemo(()=>{const m=new Map<string,any>();for(const c of clients)for(const ct of c.contracts||[])for(const i of ct.installations||[])m.set(i.id,{...i,client:c.legal_name,clientRut:c.rut,contract:ct.name});return m},[clients]);
 const people=useMemo(()=>new Map(profiles.map((p:any)=>[p.id,p.full_name||p.email])),[profiles]);
 const inRange=(v:any)=>{if(!v)return false;const d=String(v).slice(0,10);return(!from||d>=from)&&(!to||d<=to)};
 if(loading)return <section className="panel"><b>Cargando información real…</b></section>;if(message)return <section className="panel"><b>{message}</b></section>;
 if(mode==="orders")return <section className="panel"><Header title="Órdenes de compra" sub="OC que aún requieren gestión, con detalle disponible en la misma vista."/><div className="list">{orders.filter((o:any)=>!["Recibida","Cerrada","Anulada"].includes(o.status)).map((o:any)=><article className="card" key={o.id}><button className="row" onClick={()=>setOpenId(openId===o.id?null:o.id)}><span><b>{o.order_number}</b><small>{o.suppliers?.legal_name||"Proveedor"} · {o.status}</small></span><strong>{money(o.total_net)}</strong><em>{openId===o.id?"Cerrar":"Abrir OC"}</em></button>{openId===o.id&&<OcDetail o={o}/>}</article>)}</div><Style/></section>;
 if(mode==="suppliers")return <section className="panel"><Header title="Proveedores" sub="Compras reales y condición de pago registrada."/><div className="supplierGrid">{suppliers.map((s:any)=>{const rs=receipts.filter((r:any)=>r.supplier_id===s.id),total=rs.reduce((a:number,r:any)=>a+Number(r.document_net||0),0);return <article key={s.id}><b>{s.legal_name}</b><small>{s.rut||"RUT no registrado"}</small><span>Condición <strong>{s.payment_terms||"Pendiente"}</strong></span><span>Facturas <strong>{rs.length}</strong></span><span>Neto acumulado <strong>{money(total)}</strong></span></article>})}</div><Style/></section>;
 if(mode==="reports"){const fact=receipts.filter((r:any)=>inRange(r.document_date||r.received_at)),guides=dispatches.filter((d:any)=>inRange(d.delivered_at||d.dispatched_at||d.created_at));const exportNow=()=>report==="facturas"?download("informe_facturas.csv",[["Tipo","Folio","Fecha","Proveedor","RUT proveedor","OC","Neto","IVA","Total","Estado inventario"],...fact.map((r:any)=>[r.document_type,r.document_folio,r.document_date,r.suppliers?.legal_name,r.suppliers?.rut,r.purchase_orders?.order_number,r.document_net,r.vat_amount,r.document_total,r.inventory_posted?"Cargado":"Pendiente"])]):download("informe_guias_entregas.csv",[["Guía","Fecha despacho","Fecha entrega","Hora entrega","Cliente","RUT cliente","Contrato","Instalación","Región","Comuna","Responsable entrega","Recibe","RUT recibe","Estado","Observaciones"],...guides.map((d:any)=>{const i=inst.get(d.installation_id),dt=d.delivered_at?new Date(d.delivered_at):null;return[d.guide_number,d.dispatched_at,d.delivered_at,dt?dt.toLocaleTimeString("es-CL",{hour:"2-digit",minute:"2-digit"}):"",i?.client,i?.clientRut,i?.contract,i?.name,i?.region,i?.commune,people.get(d.delivered_by)||"",d.recipient_name,d.recipient_rut,d.status,d.observations]})]);return <section className="panel"><Header title="Extractor de informes" sub="Elige qué información extraer y el período. Los archivos se generan desde los registros reales."/><div className="filters"><label>Informe<select value={report} onChange={e=>setReport(e.target.value)}><option value="facturas">Facturas</option><option value="guias">Guías y entregas</option></select></label><label>Desde<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={exportNow}>Exportar CSV</button></div><div className="reportPreview"><b>{report==="facturas"?fact.length:guides.length} registros</b><span>{report==="facturas"?"Incluye folio, proveedor, OC, neto, IVA, total y estado.":"Incluye guía, fechas y hora, cliente, instalación, región, responsable, receptor y estado."}</span></div><Style/></section>}
 const invoices=receipts;return <section className="panel"><Header title={mode==="invoices"?"Facturas / Pagos":"Compras / Recepción"} sub={mode==="invoices"?"Factura, documento original, OC asociada y detalle en una sola ficha.":"Carga y cotejo de documentos contra la compra e inventario."}/>{mode==="purchases"&&<InvoiceRecognitionTest/>}<div className="list">{invoices.map((r:any)=>{const isOpen=openId===r.id,doc=documents.find((d:any)=>d.entity_id===r.id);return <article className="card" key={r.id}><button className="row invoiceRow" onClick={()=>setOpenId(isOpen?null:r.id)}><span><b>{r.document_type||"Documento"} {r.document_folio||"sin folio"}</b><small>{r.document_date||"Sin fecha"} · {r.suppliers?.legal_name||"Proveedor"}</small></span><span><small>OC asociada</small><b>{r.purchase_orders?.order_number||"Sin OC"}</b></span><span><small>Neto</small><b>{money(r.document_net)}</b></span><span className={r.inventory_posted?"ok":"pending"}>{r.inventory_posted?"Inventario cargado":r.reconciliation_status||"Pendiente"}</span><em>{isOpen?"Cerrar":"Ver detalle"}</em></button>{isOpen&&<div className="detail"><div className="detailGrid"><span><small>Documento original</small><b>{doc?doc.file_name:"No archivado"}</b>{doc?.storage_path&&<small>{doc.storage_path}</small>}</span><span><small>Total factura</small><b>{money(r.document_total)}</b></span><span><small>IVA</small><b>{money(r.vat_amount)}</b></span><span><small>Recepción</small><b>{fmt(r.received_at)}</b></span></div>{r.purchase_orders?<div className="linkedOc"><h4>Orden de compra asociada</h4><OcDetail o={orders.find((o:any)=>o.id===r.purchase_order_id)||r.purchase_orders}/></div>:<p className="notice">Esta factura no tiene una OC asociada.</p>}<h4>Detalle recibido</h4><div className="lines">{(r.receipt_lines||[]).map((l:any)=><div key={l.id}><span>{l.materials?.name||"Material"}</span><span>{l.received_qty} {l.materials?.unit||""}</span><span>{money(l.actual_unit_net)} c/u</span><strong>{money(l.line_net)}</strong></div>)}</div>{!r.inventory_posted&&["Admin Total","Gerencia","Finanzas"].includes(role)&&mode==="purchases"&&<button className="primaryAction" onClick={async()=>{if(!confirm("¿Confirmas el cotejo y carga a inventario?"))return;const f=new FormData();f.set("receipt_id",r.id);f.set("confirmation","CONFIRMAR");await reconcilePurchaseDocument(f);await load()}}>Cotejar y cargar inventario</button>}</div>}</article>})}</div><Style/></section>}
function Header({title,sub}:{title:string,sub:string}){return <div className="head"><h2>{title}</h2><p>{sub}</p></div>}
function OcDetail({o}:{o:any}){if(!o)return <p>OC no disponible.</p>;return <div className="ocDetail"><div><span><small>OC</small><b>{o.order_number}</b></span><span><small>Estado</small><b>{o.status}</b></span><span><small>Neto</small><b>{money(o.total_net)}</b></span><span><small>Total</small><b>{money(o.total_amount)}</b></span></div>{o.purchase_order_lines?.length>0&&<div className="lines">{o.purchase_order_lines.map((l:any)=><div key={l.id}><span>{l.materials?.name||"Material"}</span><span>{l.ordered_qty} {l.materials?.unit||""}</span><span>{money(l.unit_net)} c/u</span><strong>{money(l.line_net)}</strong></div>)}</div>}</div>}
function Style(){return <style jsx>{`.head h2{margin:0}.head p{margin:5px 0 16px;color:#5d7180}.list{display:grid;gap:9px}.card{border:1px solid #d9e4e8;border-radius:12px;background:#fff;overflow:hidden}.row{width:100%;border:0;background:#fff;color:#102a3a;padding:13px 15px;display:grid;grid-template-columns:2fr 1fr auto;gap:14px;align-items:center;text-align:left}.invoiceRow{grid-template-columns:2fr 1.1fr .8fr 1fr auto}.row span{display:flex;flex-direction:column;min-width:0}.row small,.detail small,.supplierGrid small{color:#657b88}.row em{font-style:normal;color:#007f83;font-weight:800}.ok{color:#14724c;font-weight:800}.pending{color:#9b6500;font-weight:800}.detail{padding:16px;border-top:1px solid #e3eaed;background:#fbfdfe}.detailGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.detailGrid span{padding:10px;background:#fff;border:1px solid #e0e8eb;border-radius:8px;display:flex;flex-direction:column}.linkedOc{margin-top:14px}.linkedOc h4,.detail h4{margin:14px 0 8px}.ocDetail>div:first-child{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.ocDetail span{display:flex;flex-direction:column}.lines{border:1px solid #e0e8eb;border-radius:8px;overflow:hidden}.lines>div{display:grid;grid-template-columns:2fr repeat(3,1fr);gap:8px;padding:8px 10px;border-bottom:1px solid #edf1f2}.lines>div:last-child{border:0}.notice{padding:10px;background:#fff5df;border-radius:8px}.primaryAction{margin-top:12px}.supplierGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:9px}.supplierGrid article{border:1px solid #dce5e8;border-radius:10px;padding:13px;display:flex;flex-direction:column;gap:5px}.supplierGrid article>span{display:flex;justify-content:space-between;gap:8px}.filters{display:grid;grid-template-columns:1.4fr 1fr 1fr auto;gap:10px;align-items:end}.filters label{display:flex;flex-direction:column;gap:5px;font-weight:700}.filters input,.filters select{padding:9px;border:1px solid #ccdadd;border-radius:8px;background:#fff}.filters button{padding:10px 14px;border:0;border-radius:8px;background:#073b5c;color:#fff;font-weight:800}.reportPreview{margin-top:14px;padding:14px;background:#eef6f6;border-radius:10px;display:flex;flex-direction:column;gap:4px}@media(max-width:850px){.invoiceRow{grid-template-columns:1fr 1fr}.invoiceRow>span:first-child,.invoiceRow>em{grid-column:1/-1}.detailGrid,.ocDetail>div:first-child{grid-template-columns:1fr 1fr}.filters{grid-template-columns:1fr 1fr}.filters label:first-child,.filters button{grid-column:1/-1}}@media(max-width:520px){.row,.invoiceRow{grid-template-columns:1fr}.row>*{grid-column:1!important}.detailGrid,.ocDetail>div:first-child,.filters{grid-template-columns:1fr}.lines>div{grid-template-columns:1fr 1fr}.supplierGrid{grid-template-columns:1fr}}`}</style>}
