"use client";
import {useEffect,useMemo,useState} from "react";
const money=(n:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(Number(n)||0);
const num=(v:any)=>Number(v||0);
function daysFromTerms(v?:string|null){const m=String(v||"").match(/(\d+)\s*d[ií]as?/i);return m?Number(m[1]):null}
function dueDate(date?:string|null,terms?:string|null){const d=daysFromTerms(terms);if(!date||d===null)return null;const x=new Date(`${date}T12:00:00`);x.setDate(x.getDate()+d);return x}
function csvDownload(name:string,rows:any[]){if(!rows.length)return;const keys=Object.keys(rows[0]);const esc=(v:any)=>`"${String(v??"").replace(/"/g,'""')}"`;const csv=[keys.map(esc).join(";"),...rows.map(r=>keys.map(k=>esc(r[k])).join(";"))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
export default function FinanceDashboard(){const[data,setData]=useState<any>(null),[error,setError]=useState("");useEffect(()=>{fetch("/api/finance/purchases",{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b)}).catch(e=>setError(e.message))},[]);
 const model=useMemo(()=>{if(!data)return null;const runs=new Map((data.supplyRuns||[]).map((r:any)=>[r.id,r]));const contracts=new Map<string,any>();for(const c of data.clients||[])for(const ct of c.contracts||[])contracts.set(ct.id,{...ct,client:c});const clients=(data.clients||[]).map((c:any)=>{const cts=(c.contracts||[]).filter((x:any)=>x.active!==false);let budget=0,committed=0,invoiced=0;for(const ct of cts){budget+=num(ct.net_budget);for(const r of data.supplyRuns||[])if(r.contract_id===ct.id)committed+=num(r.approved_net);for(const rec of data.receipts||[]){const run=runs.get(rec.purchase_orders?.supply_run_id) as any;if(run?.contract_id===ct.id)invoiced+=num(rec.document_net)}}return{...c,budget,committed,invoiced,balance:budget-invoiced,contracts:cts}});
 const suppliers=(data.suppliers||[]).map((s:any)=>{const rec=(data.receipts||[]).filter((r:any)=>r.supplier_id===s.id);return{...s,invoiced:rec.reduce((a:number,r:any)=>a+num(r.document_net),0),docs:rec.length}}).sort((a:any,b:any)=>b.invoiced-a.invoiced);
 const reminders=(data.receipts||[]).map((r:any)=>{const terms=r.purchase_orders?.payment_terms||r.suppliers?.payment_terms||null;const due=dueDate(r.document_date,terms);const days=due?Math.ceil((due.getTime()-Date.now())/86400000):null;return{...r,terms,due,days}}).filter((r:any)=>r.due).sort((a:any,b:any)=>a.due.getTime()-b.due.getTime());
 return{clients,suppliers,reminders,contracts,runs}},[data]);
 if(error)return <section className="panel"><b>No se pudo cargar el tablero financiero:</b> {error}</section>;if(!model)return <section className="panel"><b>Cargando información financiera real…</b></section>;
 const totalBudget=model.clients.reduce((a:number,c:any)=>a+c.budget,0),totalInvoiced=model.clients.reduce((a:number,c:any)=>a+c.invoiced,0),totalCommitted=model.clients.reduce((a:number,c:any)=>a+c.committed,0);const receipts=data.receipts||[];
 const exportDetail=()=>csvDownload("finanzas_detalle_compras.csv",receipts.map((r:any)=>{const run=model.runs.get(r.purchase_orders?.supply_run_id) as any;const ct=run?model.contracts.get(run.contract_id):null;return{Fecha:r.document_date,Folio:r.document_folio,Proveedor:r.suppliers?.legal_name||"",Cliente:ct?.client?.legal_name||"",Contrato:ct?.name||"",Neto:num(r.document_net),IVA:num(r.vat_amount),Total:num(r.document_total),OC:r.purchase_orders?.order_number||"",Estado_cotejo:r.reconciliation_status||"",Condicion_pago:r.purchase_orders?.payment_terms||r.suppliers?.payment_terms||""}}));
 return <div className="financeDash"><section className="financeKpis"><article><small>Cuota / presupuesto contratos</small><b>{money(totalBudget)}</b></article><article><small>Comprometido aprobado</small><b>{money(totalCommitted)}</b></article><article><small>Facturado neto atribuible</small><b>{money(totalInvoiced)}</b></article><article><small>Facturas registradas</small><b>{receipts.length}</b></article></section>
 <section className="panel"><div className="catalogIntro"><div><h2>Control por cliente</h2><p>Presupuesto, flujo aprobado y gasto facturado. Solo se muestran valores existentes en la base.</p></div><button type="button" onClick={()=>csvDownload("finanzas_clientes.csv",model.clients.map((c:any)=>({Cliente:c.legal_name,RUT:c.rut||"",Presupuesto_neto:c.budget,Comprometido_neto:c.committed,Facturado_neto:c.invoiced,Saldo_vs_facturado:c.balance})))}>CSV clientes</button></div><div className="clientFinanceGrid">{model.clients.map((c:any)=>{const pct=c.budget>0?Math.min(100,Math.round(c.invoiced/c.budget*100)):0;return <article key={c.id}><div><b>{c.legal_name}</b><small>{c.rut||"RUT no registrado"}</small></div><div className="budgetLine"><span>Presupuesto <b>{money(c.budget)}</b></span><span>Facturado <b>{money(c.invoiced)}</b></span><span>Saldo <b>{money(c.balance)}</b></span></div><div className="bar"><i style={{width:`${pct}%`}}/></div><small>{c.budget>0?`${pct}% facturado sobre presupuesto`:`Presupuesto no registrado · no se calcula porcentaje`}</small></article>})}</div></section>
 <section className="financeTwo"><section className="panel"><div className="catalogIntro"><div><h2>Compras por proveedor</h2><p>Acumulado neto de documentos registrados.</p></div><button type="button" onClick={()=>csvDownload("finanzas_proveedores.csv",model.suppliers.map((s:any)=>({Proveedor:s.legal_name,RUT:s.rut||"",Condicion_pago:s.payment_terms||"Pendiente",Facturado_neto:s.invoiced,Documentos:s.docs})))}>CSV</button></div>{model.suppliers.map((s:any)=><div className="financeRow" key={s.id}><span><b>{s.legal_name}</b><small>{s.payment_terms||"Condición de pago pendiente"}</small></span><strong>{money(s.invoiced)}</strong></div>)}</section>
 <section className="panel"><h2>Vencimientos calculables</h2><p className="note">Solo se calcula cuando existe una condición de pago con días registrada en la OC o proveedor. No se asumen plazos.</p>{model.reminders.length?model.reminders.map((r:any)=><div className="financeRow" key={r.id}><span><b>{r.suppliers?.legal_name||"Proveedor"} · {r.document_folio||"sin folio"}</b><small>{r.terms} · vence {r.due.toLocaleDateString("es-CL")}</small></span><strong>{r.days<0?`${Math.abs(r.days)} d vencida`:r.days===0?"Vence hoy":`${r.days} d`}</strong></div>):<div className="empty"><b>Sin vencimientos calculables</b><span>Complete condiciones de pago reales en proveedores u OC.</span></div>}</section></section>
 <section className="panel"><div className="catalogIntro"><div><h2>Reportes</h2><p>El CSV de detalle conserva documento, proveedor, cliente y contrato cuando la trazabilidad de la OC permite atribuirlos.</p></div><button type="button" onClick={exportDetail}>Descargar CSV detalle</button></div></section>
 <style jsx>{`.financeDash{display:grid;gap:14px;margin-bottom:18px}.financeKpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.financeKpis article{background:#fff;border:1px solid #dce5e8;border-radius:12px;padding:14px;display:flex;flex-direction:column;gap:5px}.financeKpis b{font-size:1.35rem}.financeKpis small,.clientFinanceGrid small,.financeRow small{opacity:.7}.clientFinanceGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.clientFinanceGrid article{border:1px solid #e0e7e9;border-radius:11px;padding:13px;display:grid;gap:9px}.clientFinanceGrid article>div:first-child,.financeRow span{display:flex;flex-direction:column}.budgetLine{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.budgetLine span{display:flex;flex-direction:column;font-size:.82rem}.bar{height:7px;background:#edf2f3;border-radius:9px;overflow:hidden}.bar i{display:block;height:100%;background:currentColor;opacity:.55}.financeTwo{display:grid;grid-template-columns:1fr 1fr;gap:14px}.financeRow{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid #edf1f2}.financeRow:last-child{border:0}@media(max-width:900px){.financeKpis{grid-template-columns:1fr 1fr}.clientFinanceGrid,.financeTwo{grid-template-columns:1fr}}@media(max-width:560px){.financeKpis{grid-template-columns:1fr}.budgetLine{grid-template-columns:1fr 1fr}.catalogIntro{align-items:flex-start}}`}</style></div>}
