"use client";
import {useEffect,useMemo,useState} from "react";
import {reconcilePurchaseDocument,registerPurchaseWithoutOc} from "@/app/finance-purchase-actions";
import InvoiceRecognitionTest from "@/components/modules/InvoiceRecognitionTest";
const money=(n:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(n||0);
export default function FinancePurchaseRegister({role,mode="purchases"}:{role:string;mode?:"purchases"|"invoices"|"orders"|"suppliers"|"reports"}){const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[openId,setOpenId]=useState<string|null>(null);const load=async()=>{setLoading(true);try{const r=await fetch("/api/finance/purchases",{cache:"no-store"}),b=await r.json();if(!r.ok)throw new Error(b.error||"No se pudo cargar Finanzas");setData(b)}catch(e:any){setMessage(e?.message||"No se pudo cargar Finanzas")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);const receipts=data?.receipts||[],orders=data?.orders||[],suppliers=data?.suppliers||[];if(loading)return <section className="panel"><b>Cargando información real…</b></section>;if(message)return <section className="panel"><b>{message}</b></section>;
 if(mode==="orders")return <section className="panel"><h2>OC pendientes</h2><p>Órdenes que aún requieren gestión de compra o recepción.</p><div className="simpleList">{orders.filter((o:any)=>!["Recibida","Cerrada","Anulada"].includes(o.status)).map((o:any)=><article key={o.id}><span><b>{o.order_number}</b><small>{o.suppliers?.legal_name||"Proveedor"} · {o.status}</small></span><strong>{money(Number(o.total_net||0))}</strong></article>)}</div><Style/></section>;
 if(mode==="suppliers")return <section className="panel"><h2>Proveedores</h2><p>Condiciones y compras registradas por proveedor.</p><div className="simpleList">{suppliers.map((s:any)=>{const total=receipts.filter((r:any)=>r.supplier_id===s.id).reduce((a:number,r:any)=>a+Number(r.document_net||0),0);return <article key={s.id}><span><b>{s.legal_name}</b><small>{s.payment_terms||"Condición de pago pendiente"}</small></span><strong>{money(total)}</strong></article>})}</div><Style/></section>;
 if(mode==="reports")return <section className="panel"><h2>Informes</h2><p>Resumen financiero construido desde compras y documentos registrados.</p><div className="reportCards"><article><small>Documentos</small><b>{receipts.length}</b></article><article><small>Neto registrado</small><b>{money(receipts.reduce((a:number,r:any)=>a+Number(r.document_net||0),0))}</b></article><article><small>OC registradas</small><b>{orders.length}</b></article><article><small>Proveedores activos</small><b>{suppliers.length}</b></article></div><Style/></section>;
 const title=mode==="invoices"?"Facturas / Pagos":"Compras / Recepción";const visible=mode==="invoices"?receipts:receipts;return <section className="panel"><div className="catalogIntro"><div><h2>{title}</h2><p>{mode==="invoices"?"Documentos de proveedor, valores netos y estado de inventario.":"Recepciones y cotejo de compras contra inventario."}</p></div></div>{mode==="purchases"&&<InvoiceRecognitionTest/>}<div className="purchaseRegister">{visible.map((r:any)=>{const isOpen=openId===r.id;return <article className="purchase" key={r.id}><button type="button" className="purchaseHead" onClick={()=>setOpenId(isOpen?null:r.id)}><span><b>{r.document_type||"Documento"} {r.document_folio||"sin folio"}</b><small>{r.document_date||"Sin fecha"} · {r.suppliers?.legal_name||"Proveedor"}</small></span><span><b>{money(Number(r.document_net||0))}</b><small>Neto</small></span><span><b>{r.inventory_posted?"Inventario cargado":r.reconciliation_status||"Pendiente"}</b></span><strong>{isOpen?"Cerrar":"Ver"}</strong></button>{isOpen&&<div className="purchaseBody"><p><b>OC:</b> {r.purchase_orders?.order_number||"Sin OC"}</p><p><b>Total:</b> {money(Number(r.document_total||0))}</p>{!r.inventory_posted&&["Admin Total","Gerencia","Finanzas"].includes(role)&&mode==="purchases"&&<button onClick={async()=>{if(!confirm("¿Confirmas el cotejo y carga a inventario?"))return;const f=new FormData();f.set("receipt_id",r.id);f.set("confirmation","CONFIRMAR");await reconcilePurchaseDocument(f);await load()}}>Cotejar y cargar inventario</button>}</div>}</article>})}</div><Style/></section>}
function Style(){return <style jsx>{`.simpleList,.purchaseRegister{display:grid;gap:9px;margin-top:12px}.simpleList article,.purchase{border:1px solid #dce5e8;border-radius:10px;background:#fff}.simpleList article{padding:12px;display:flex;justify-content:space-between;gap:12px}.simpleList span,.purchaseHead span{display:flex;flex-direction:column}.simpleList small,.purchaseHead small{opacity:.68}.purchaseHead{width:100%;display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:12px;align-items:center;text-align:left;padding:13px;background:#fff;color:inherit;border:0}.purchaseBody{padding:12px;border-top:1px solid #e6ecee}.reportCards{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:12px}.reportCards article{padding:14px;border:1px solid #dce5e8;border-radius:10px;display:flex;flex-direction:column}.reportCards b{font-size:1.25rem}@media(max-width:700px){.reportCards{grid-template-columns:1fr 1fr}.purchaseHead{grid-template-columns:1fr 1fr}.purchaseHead>span:first-child{grid-column:1/-1}}`}</style>}
