"use client";
import {useRef,useState} from "react";
import {confirmInstallationCsvRows,previewInstallationCsvRows} from "@/app/installation-import-actions";
type Row={client?:string;rut?:string;contract?:string;installation?:string;region?:string;city?:string;commune?:string;address?:string};
const parse=(line:string,d:string)=>{const a:string[]=[];let v="",q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){v+='"';i++;}else q=!q;}else if(c===d&&!q){a.push(v.trim());v="";}else v+=c;}a.push(v.trim());return a;};
const norm=(v:string)=>String(v||"").trim().toLocaleLowerCase("es-CL").normalize("NFD").replace(/[\u0300-\u036f]/g,"");
export default function InstallationCsvImportPanel(){const ref=useRef<HTMLInputElement|null>(null);const [rows,setRows]=useState<Row[]>([]),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(file:File){setBusy(true);setMessage("");try{const txt=(await file.text()).replace(/^\uFEFF/,"");const lines=txt.split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw new Error("CSV vacío");const d=lines[0].includes(";")?";":",";const h=parse(lines[0],d).map(norm);const aliases:any={client:["cliente","razon social","razon_social"],rut:["rut"],contract:["contrato","perfil","contrato perfil"],installation:["instalacion","instalación"],region:["region","región"],city:["ciudad"],commune:["comuna"],address:["direccion","dirección"]};const idx=(k:string)=>h.findIndex(x=>aliases[k].includes(x));if(idx("client")<0||idx("contract")<0||idx("installation")<0)throw new Error("Debe incluir Cliente, Contrato e Instalacion");const parsed=lines.slice(1).map(l=>{const a=parse(l,d),g=(k:string)=>idx(k)>=0?(a[idx(k)]||"").trim():"";return{client:g("client"),rut:g("rut"),contract:g("contract"),installation:g("installation"),region:g("region"),city:g("city"),commune:g("commune"),address:g("address")};}).filter(r=>r.client||r.installation);setRows(parsed);setPreview(await previewInstallationCsvRows(parsed));}catch(e:any){setMessage(e?.message||"No se pudo analizar");}finally{setBusy(false);}}
 async function confirm(){setBusy(true);try{const r=await confirmInstallationCsvRows(rows);setMessage(`Carga: ${r.created} agregadas, ${r.skipped} ya existentes, ${r.review} en revisión.`);setPreview(null);setRows([]);if(ref.current)ref.current.value="";window.location.reload();}catch(e:any){setMessage(e?.message||"No se pudo confirmar");}finally{setBusy(false);}}
 return <div className="clientCsvImport"><div className="clientCsvTop"><input ref={ref} type="file" accept=".csv,text/csv" onChange={e=>{const f=e.target.files?.[0];if(f)void load(f);}}/><span>{busy?"Procesando...":"Cargar instalaciones CSV"}</span></div><p style={{margin:"10px 0 0"}}>Solo agrega instalaciones faltantes. No duplica clientes ni instalaciones existentes.</p>{message&&<p className="note">{message}</p>}{preview&&<><div className="clientCsvSummary"><span>{preview.total} filas</span><span>{preview.add} agregar</span><span>{preview.exists} existentes</span><span>{preview.review} revisar</span></div><div className="clientCsvTable"><table><thead><tr><th>Cliente</th><th>Contrato</th><th>Instalación</th><th>Resultado</th><th>Detalle</th></tr></thead><tbody>{preview.details.map((d:any)=><tr key={`${d.index}-${d.installation}`}><td>{d.client}</td><td>{d.contract}</td><td>{d.installation}</td><td><b>{d.status}</b></td><td>{d.reason||"—"}</td></tr>)}</tbody></table></div><div className="clientCsvActions"><button type="button" disabled={busy||preview.add===0} onClick={confirm}>Confirmar solo faltantes</button></div></>}</div>;
}
