"use client";

import {useRef,useState} from "react";
import {confirmMaterialProfileImport,findMaterialProfileImportTargets,previewMaterialProfileImport,type MaterialProfileImportRow,type MaterialProfileImportTarget} from "@/app/material-profile-import-actions";

const parseLine=(line:string,d:string)=>{const out:string[]=[];let value="",quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(ch===d&&!quoted){out.push(value.trim());value="";}else value+=ch;}out.push(value.trim());return out;};
const norm=(v:string)=>String(v||"").trim().toLocaleLowerCase("es-CL").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/_/g," ").replace(/\s+/g," ");
const aliases:Record<string,string[]>={
 selected:["seleccionar","seleccion","asignar","x"],authorized_qty:["maximo autorizado","maximo","cantidad maxima","cantidad","max entrega"],period_type:["periodicidad","periodo"],
 material_id:["material id","material_id","id material"],family:["familia"],supplier_code:["codigo","codigo proveedor"],material:["material","producto"],presentation:["presentacion"],unit:["unidad"]
};

export default function MaterialProfileCsvImportPanel(){
 const inputRef=useRef<HTMLInputElement|null>(null);
 const [query,setQuery]=useState(""),[targets,setTargets]=useState<MaterialProfileImportTarget[]>([]),[target,setTarget]=useState<MaterialProfileImportTarget|null>(null);
 const [rows,setRows]=useState<MaterialProfileImportRow[]>([]),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[fileName,setFileName]=useState("");
 async function search(){setBusy(true);setMessage("");setPreview(null);try{const r=await findMaterialProfileImportTargets(query);setTargets(r);if(!r.length)setMessage("Sin coincidencias. Busca por RUT, cliente, contrato o instalación.");}catch(e:any){setMessage(e?.message||"No fue posible buscar");}finally{setBusy(false)}}
 function choose(t:MaterialProfileImportTarget){setTarget(t);setTargets([]);setRows([]);setPreview(null);setFileName("");setMessage("");if(inputRef.current)inputRef.current.value="";}
 async function load(file:File){if(!target)return;setBusy(true);setMessage("");setPreview(null);try{const txt=(await file.text()).replace(/^\uFEFF/,"");const lines=txt.split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw new Error("El archivo no contiene materiales");const d=lines[0].includes(";")?";":",";const headers=parseLine(lines[0],d).map(norm);const idx=(k:string)=>headers.findIndex(h=>(aliases[k]||[]).includes(h));if(idx("material_id")<0||idx("selected")<0||idx("authorized_qty")<0)throw new Error("Usa la plantilla descargada desde ALEMSI. Debe contener Seleccionar, Máximo autorizado y material_id.");const parsed=lines.slice(1).map(line=>{const values=parseLine(line,d),get=(k:string)=>idx(k)>=0?(values[idx(k)]||"").trim():"";return{selected:get("selected"),authorized_qty:get("authorized_qty"),period_type:get("period_type"),material_id:get("material_id"),family:get("family"),supplier_code:get("supplier_code"),material:get("material"),presentation:get("presentation"),unit:get("unit")};}).filter(r=>r.material_id||r.material);if(!parsed.length)throw new Error("No se encontraron filas válidas");setRows(parsed);setFileName(file.name);setPreview(await previewMaterialProfileImport(target,parsed));}catch(e:any){setMessage(e?.message||"No se pudo analizar el archivo");}finally{setBusy(false)}}
 async function confirm(){if(!target||!rows.length||!preview)return;setBusy(true);setMessage("");try{const r=await confirmMaterialProfileImport(target,rows);setMessage(`Carga confirmada: ${r.changed} cambios aplicados · ${r.skipped} sin cambios.`);setRows([]);setPreview(null);setFileName("");if(inputRef.current)inputRef.current.value="";}catch(e:any){setMessage(e?.message||"No se pudo confirmar la carga");}finally{setBusy(false)}}
 return <div className="clientCsvImport materialBulkImport">
  <div className="csvImportPanelHead"><div><h3>Carga masiva de materiales autorizados</h3><small>Busca el destino, descarga el maestro, marca X y máximo, luego vuelve a cargarlo.</small></div></div>
  {!target?<><div className="clientCsvTop"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void search();}}} placeholder="RUT, cliente, contrato o instalación"/><button type="button" disabled={busy||query.trim().length<2} onClick={()=>void search()}>{busy?"Buscando...":"Buscar"}</button></div>
   {targets.length>0&&<div className="profileAddResults">{targets.map((t,i)=><button type="button" key={`${t.kind}-${t.contract_id}-${t.installation_id||i}`} onClick={()=>choose(t)}><span><b>{t.installation||t.contract}</b><small>{t.client}{t.rut?` · ${t.rut}`:""} · {t.contract}{t.installation?" · Instalación específica":" · Contrato completo"}</small></span><strong>Seleccionar</strong></button>)}</div>}
  </>:<><div className="note"><b>{target.installation||target.contract}</b><br/><span>{target.client}{target.rut?` · ${target.rut}`:""} · {target.contract}{target.installation?" · Solo esta instalación":" · Todas las instalaciones por perfil de contrato"}</span></div>
   <div className="clientCsvActions"><a className="mastersBack" href={`/api/material-profile-template?kind=${target.kind}&contract_id=${encodeURIComponent(target.contract_id)}${target.installation_id?`&installation_id=${encodeURIComponent(target.installation_id)}`:""}`} download>Descargar maestro para Excel</a><button type="button" className="clearFilters" disabled={busy} onClick={()=>{setTarget(null);setRows([]);setPreview(null);setMessage("");}}>Cambiar destino</button></div>
   <div className="clientCsvTop" style={{marginTop:12}}><input ref={inputRef} type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void load(f);}}/><span>{busy?"Procesando...":fileName||"Subir maestro completado"}</span></div>
   {preview&&<><div className="clientCsvSummary"><span>{preview.total} filas</span><span>{preview.ready} asignar</span><span>{preview.update} actualizar/quitar</span><span>{preview.unchanged} sin cambios</span><span>{preview.review} revisar</span><span>{preview.duplicates} duplicados</span></div>
    <div className="clientCsvTable"><table><thead><tr><th>Fila</th><th>Material</th><th>Resultado</th><th>Detalle</th></tr></thead><tbody>{preview.details.map((d:any)=><tr key={d.index}><td>{d.index}</td><td>{d.material}</td><td><b>{d.status}</b></td><td>{d.reason}</td></tr>)}</tbody></table></div>
    {(preview.review>0||preview.duplicates>0)&&<p className="warning">Corrige las filas REVISAR o DUPLICADO antes de confirmar. No se guardará nada mientras existan observaciones.</p>}
    <div className="clientCsvActions"><button type="button" disabled={busy||preview.review>0||preview.duplicates>0} onClick={()=>void confirm()}>{busy?"Guardando...":"Confirmar carga segura"}</button><button type="button" className="clearFilters" disabled={busy} onClick={()=>{setRows([]);setPreview(null);setFileName("");if(inputRef.current)inputRef.current.value="";}}>Cancelar archivo</button></div></>}
  </>}
  {message&&<p className="note" role="status">{message}</p>}
 </div>;
}
