"use client";
import {useMemo,useState} from "react";
import {derivePurchaseOrder} from "@/app/actions";
const money=(n:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(n||0);
export default function PurchaseOrdersModule({orders,role}:{orders:any[];role:string}){
 const canOperate=["Admin Total","Gerencia","Admin"].includes(role);
 const [emailOrder,setEmailOrder]=useState<any|null>(null),[to,setTo]=useState(""),[cc,setCc]=useState(""),[subject,setSubject]=useState(""),[body,setBody]=useState("");
 const openEmail=(o:any)=>{const email=o.suppliers?.purchase_order_email||"";setEmailOrder(o);setTo(email);setCc("");setSubject(`Orden de Compra ${o.order_number||"ALEMSI"}`);setBody(`Estimados,\n\nAdjuntamos/derivamos Orden de Compra ${o.order_number||""} para su gestión.\n\nSaludos,\nALEMSI`)};
 const mailHref=useMemo(()=>emailOrder?`mailto:${encodeURIComponent(to)}?cc=${encodeURIComponent(cc)}&subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`:"",[emailOrder,to,cc,subject,body]);
 if(emailOrder)return <section className="panel"><div className="catalogIntro"><div><h2>Enviar orden de compra</h2><p>{emailOrder.order_number||"OC sin folio"} · {emailOrder.suppliers?.legal_name||"Proveedor"}</p></div><button type="button" className="clearFilters" onClick={()=>setEmailOrder(null)}>← Volver a órdenes de compra</button></div><div style={{marginTop:16}}><div className="surveyCampaignFilters"><label>Para<input type="email" value={to} onChange={e=>setTo(e.target.value)} placeholder="correo proveedor"/></label><label>CC<input value={cc} onChange={e=>setCc(e.target.value)} placeholder="correo interno opcional"/></label></div><label style={{display:"grid",gap:5,marginTop:10}}>Asunto<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label style={{display:"grid",gap:5,marginTop:10}}>Mensaje<textarea rows={6} value={body} onChange={e=>setBody(e.target.value)}/></label><div className="contractActions" style={{marginTop:12,display:"flex",gap:8,flexWrap:"wrap"}}><a href={mailHref} className="linkBtn">Abrir correo para enviar</a><a href={`/ordenes-compra/${emailOrder.id}`} rel="noreferrer" className="linkBtn">Abrir OC / PDF</a></div><p className="note">Esta vista corresponde únicamente a la OC seleccionada. Al volver regresarás al listado de órdenes de compra.</p></div></section>;
 return <section className="panel"><div className="catalogIntro"><div><h2>Órdenes de compra</h2><p>Selecciona una OC para verla, enviarla o derivarla a Finanzas.</p></div></div><div className="table" style={{marginTop:16}}>{orders.length?orders.map(o=><div className="row" key={o.id} style={{alignItems:"center",gap:10}}><span style={{minWidth:180}}><b>{o.order_number||"OC sin folio"}</b><small>{o.suppliers?.legal_name||"Proveedor"}</small>{o.suppliers?.purchase_order_email&&<small>{o.suppliers.purchase_order_email}</small>}</span><strong>{money(Number(o.total_net||0))} neto</strong><em>{o.status}</em><span className="contractActions" style={{display:"flex",flexWrap:"wrap",gap:6}}><a className="linkBtn" href={`/ordenes-compra/${o.id}`}>Ver OC</a><button type="button" onClick={()=>openEmail(o)}>Enviar OC</button>{canOperate&&<form action={derivePurchaseOrder}><input type="hidden" name="purchase_order_id" value={o.id}/><button>Derivar a Finanzas</button></form>}</span></div>):<div className="empty"><b>Sin órdenes de compra</b><span>Las nuevas OC aparecerán aquí.</span></div>}</div><p className="note"><b>Flujo:</b> revisar OC → enviar → derivar a Finanzas → factura y recepción → cotejo.</p></section>;
}
