"use client";
import {useMemo,useState} from "react";
import {inviteUser,setUserInstallationAccess,updateUserProfile} from "@/app/actions";
import type {ClientInstallationGroup} from "./ClientInstallationsModule";
export type UserProfileRow={id:string;full_name?:string|null;email?:string|null;role:string;active:boolean;created_at?:string};
export type UserAccessRow={id:string;user_id:string;installation_id:string;active:boolean;can_view_master:boolean;can_survey:boolean};
const roles=[
 {value:"Admin Total",label:"Admin Total"},
 {value:"Gerencia",label:"Gerencia"},
 {value:"Admin",label:"Operaciones"},
 {value:"Finanzas",label:"Finanzas"},
 {value:"Bodega",label:"Bodega"},
 {value:"Supervisora",label:"Supervisora"},
];
const roleLabel=(role:string)=>roles.find(item=>item.value===role)?.label||role;
export default function UsersModule({users,clients,access,currentUserId}:{users:UserProfileRow[];clients:ClientInstallationGroup[];access:UserAccessRow[];currentUserId:string}){
 const [selected,setSelected]=useState(users[0]?.id||"");const [search,setSearch]=useState("");const [showNew,setShowNew]=useState(false);const user=users.find(item=>item.id===selected)||users[0];
 const assigned=new Set(access.filter(item=>item.user_id===user?.id&&item.active).map(item=>item.installation_id));
 const installations=useMemo(()=>clients.flatMap(client=>client.contracts.flatMap(contract=>contract.installations.map(installation=>({client:client.legal_name,contract:contract.name,...installation})))).filter(item=>!search||[item.client,item.contract,item.name,item.region,item.city,item.commune].join(" ").toLocaleLowerCase("es-CL").includes(search.toLocaleLowerCase("es-CL"))),[clients,search]);
 if(!user)return <section className="panel"><h2>Usuarios</h2><div className="empty"><b>No hay perfiles disponibles</b></div></section>;
 return <section className="panel usersModule"><div className="catalogIntro"><div><h2>Usuarios y permisos</h2><p>Administra nombre, correo, perfil de uso, estado y acceso a instalaciones.</p></div><div className="userHeaderActions"><span className="catalogCount">{users.length} usuarios · {access.filter(item=>item.active).length} asignaciones</span><button type="button" onClick={()=>setShowNew(v=>!v)}>+ Nuevo usuario</button></div></div>
 {showNew&&<form action={inviteUser} className="adminForm userInviteForm"><h3>Crear e invitar usuario</h3><label>Nombre<input name="full_name" required placeholder="Nombre completo"/></label><label>Correo<input name="email" type="email" required placeholder="usuario@correo.cl"/></label><label>Perfil de uso<select name="role" defaultValue="Supervisora">{roles.map(role=><option key={role.value} value={role.value}>{role.label}</option>)}</select></label><label>Estado<select name="active" defaultValue="true"><option value="true">Activo</option><option value="false">Inactivo</option></select></label><button>Crear y enviar invitación</button><small>El perfil Operaciones utiliza internamente el rol técnico “Admin” para conservar compatibilidad con los permisos existentes.</small></form>}
 <div className="userLayout"><aside className="userList">{users.map(item=><button type="button" key={item.id} className={item.id===user.id?"selected":""} onClick={()=>setSelected(item.id)}><b>{item.full_name||"Nombre pendiente"}</b><span>{item.email||"Correo pendiente"}</span><small>{roleLabel(item.role)} · {item.active?"Activo":"Inactivo"}</small></button>)}</aside>
 <div className="userEditor"><form action={updateUserProfile} className="adminForm userProfileForm"><input type="hidden" name="user_id" value={user.id}/><label>Nombre<input name="full_name" required defaultValue={user.full_name||""}/></label><label>Correo<input name="email" type="email" required defaultValue={user.email||""} disabled={user.id===currentUserId}/>{user.id===currentUserId&&<><input type="hidden" name="email" value={user.email||""}/><small>Por seguridad, tu propio correo de Admin Total no se cambia desde esta ficha.</small></>}</label><label>Perfil de uso<select name="role" defaultValue={user.role}>{roles.map(role=><option key={role.value} value={role.value}>{role.label}</option>)}</select></label><label>Estado<select name="active" defaultValue={String(user.active)} disabled={user.id===currentUserId}><option value="true">Activo</option><option value="false">Inactivo</option></select>{user.id===currentUserId&&<input type="hidden" name="active" value="true"/>}</label><button>Guardar usuario</button></form>
 <div className="assignmentHead"><div><h3>Instalaciones asignadas</h3><p>Las supervisoras verán solamente las instalaciones activas que tengan asignadas.</p></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente, contrato o instalación"/></div>
 <div className="assignmentList">{installations.map(item=>{const isAssigned=assigned.has(item.id);return <article key={item.id}><span><b>{item.name}</b><small>{item.client} · {item.contract}<br/>{[item.commune,item.city,item.region].filter(Boolean).join(" · ")||"Ubicación pendiente"}</small></span><form action={setUserInstallationAccess}><input type="hidden" name="user_id" value={user.id}/><input type="hidden" name="installation_id" value={item.id}/><input type="hidden" name="granted" value={String(!isAssigned)}/><button className={isAssigned?"removeAccess":""}>{isAssigned?"Retirar":"Asignar"}</button></form></article>})}</div></div></div>
 <p className="catalogNote">El correo identifica la cuenta de acceso. Los cambios quedan trazados y el perfil Operaciones mantiene los permisos existentes del rol técnico Admin.</p></section>;
}
