"use client";
import {useMemo,useState} from "react";
import {setUserInstallationAccess} from "@/app/actions";
import {inviteMaterialUser,setTemporaryPassword,updateMaterialUser} from "@/app/user-actions";
import {setUserCapabilityOverride} from "@/app/user-permission-actions";
import {setAdditionalServiceUserAccess} from "@/app/additional-services-actions";
import {CAPABILITIES,roleCan,type Capability} from "@/lib/authorization";
import type {ClientInstallationGroup} from "./ClientInstallationsModule";
export type UserProfileRow={id:string;full_name?:string|null;email?:string|null;role:string;active:boolean;created_at?:string};
export type UserAccessRow={id:string;user_id:string;installation_id:string;active:boolean;can_view_master:boolean;can_survey:boolean};
export type UserPermissionOverride={id:string;user_id:string;module_code:string;can_view:boolean};
export type AdditionalServiceRow={service_code:string;display_name:string;status:string;access_mode:string};
export type AdditionalServiceUserAccessRow={id:string;service_code:string;user_id:string;active:boolean};
const capabilityLabels:Record<Capability,string>={[CAPABILITIES.SURVEY_REGISTER]:"Registrar levantamientos",[CAPABILITIES.SURVEY_LINK_MANAGE]:"Generar y enviar enlaces de conteo",[CAPABILITIES.SUPPLY_MANAGE]:"Gestionar abastecimiento",[CAPABILITIES.PURCHASE_ORDER_MANAGE]:"Gestionar órdenes de compra",[CAPABILITIES.RECEIPT_REGISTER]:"Registrar recepción",[CAPABILITIES.INVENTORY_ADJUST]:"Registrar ajustes de inventario",[CAPABILITIES.DISPATCH_MANAGE]:"Gestionar despachos",[CAPABILITIES.DELIVERY_REGISTER]:"Registrar entregas",[CAPABILITIES.ROUTE_ACCESS]:"Acceder a rutas",[CAPABILITIES.ROUTE_MANAGE]:"Crear y asignar rutas",[CAPABILITIES.RENDITION_SUBMIT]:"Enviar rendiciones",[CAPABILITIES.RENDITION_REVIEW]:"Revisar rendiciones",[CAPABILITIES.RENDITION_OBSERVE]:"Observar rendiciones",[CAPABILITIES.RENDITION_APPROVE]:"Aprobar o rechazar rendiciones",[CAPABILITIES.RENDITION_PAY]:"Registrar pago de rendiciones"};
const roles=[
 {value:"Admin Total",label:"Admin Total"},
 {value:"Gerencia",label:"Gerencia"},
 {value:"Admin",label:"Admin"},
 {value:"Operaciones",label:"Operaciones"},
 {value:"Finanzas",label:"Finanzas"},
 {value:"Bodega",label:"Bodega"},
 {value:"Supervisora",label:"Supervisora"},
];
const roleLabel=(role:string)=>roles.find(item=>item.value===role)?.label||role;
export default function UsersModule({users,clients,access,currentUserId,permissionOverrides,additionalServices,additionalServiceUserAccess}:{users:UserProfileRow[];clients:ClientInstallationGroup[];access:UserAccessRow[];currentUserId:string;permissionOverrides:UserPermissionOverride[];additionalServices:AdditionalServiceRow[];additionalServiceUserAccess:AdditionalServiceUserAccessRow[]}){
 const [selected,setSelected]=useState(users[0]?.id||"");const [search,setSearch]=useState("");const [showNew,setShowNew]=useState(false);const [inviteMessage,setInviteMessage]=useState("");const [inviteBusy,setInviteBusy]=useState(false);const [editMessage,setEditMessage]=useState("");const [editBusy,setEditBusy]=useState(false);const [passwordBusy,setPasswordBusy]=useState(false);const [passwordMessage,setPasswordMessage]=useState("");const [testBusy,setTestBusy]=useState(false);const [testMessage,setTestMessage]=useState("");const user=users.find(item=>item.id===selected)||users[0];
 const assigned=new Set(access.filter(item=>item.user_id===user?.id&&item.active).map(item=>item.installation_id));
 const userOverrides=permissionOverrides.filter(item=>item.user_id===user?.id);
 const installations=useMemo(()=>clients.flatMap(client=>client.contracts.flatMap(contract=>contract.installations.map(installation=>({client:client.legal_name,contract:contract.name,...installation})))).filter(item=>!search||[item.client,item.contract,item.name,item.region,item.city,item.commune].join(" ").toLocaleLowerCase("es-CL").includes(search.toLocaleLowerCase("es-CL"))),[clients,search]);
 if(!user)return <section className="panel"><h2>Usuarios</h2><div className="empty"><b>No hay perfiles disponibles</b></div></section>;
 const submitInvite=async(formData:FormData)=>{setInviteBusy(true);setInviteMessage("Creando usuario...");const result=await inviteMaterialUser(formData);setInviteMessage(result.ok?(result.message||"Usuario creado correctamente"):`Error: ${result.error||"No se pudo crear el usuario"}`);if(result.ok)setShowNew(false);setInviteBusy(false)};
 const submitEdit=async(formData:FormData)=>{setEditBusy(true);setEditMessage("Guardando...");const result=await updateMaterialUser(formData);setEditMessage(result.ok?(result.message||"Usuario actualizado"):`Error: ${result.error||"No se pudo actualizar el usuario"}`);setEditBusy(false)};
 const submitTemporaryPassword=async(formData:FormData)=>{setPasswordBusy(true);setPasswordMessage("Asignando clave temporal...");const result=await setTemporaryPassword(formData);setPasswordMessage(result.ok?(result.message||"Clave temporal asignada"):`Error: ${result.error||"No se pudo asignar la clave temporal"}`);setPasswordBusy(false)};
 const testEmail=async()=>{if(!user.email){setTestMessage("Error: el usuario seleccionado no tiene correo");return}setTestBusy(true);setTestMessage(`Probando envío a ${user.email}...`);try{const response=await fetch("/api/email/test",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:user.email})});const result=await response.json().catch(()=>({}));setTestMessage(result.ok?`Correo de prueba enviado a ${result.email||user.email}. Revisa la bandeja de entrada y spam.`:`Error: ${result.error||"No se pudo completar la prueba SMTP"}`)}catch{setTestMessage("Error: no fue posible ejecutar la prueba de correo")}finally{setTestBusy(false)}};
 return <section className="panel usersModule"><div className="catalogIntro"><div><h2>Usuarios y permisos</h2><p>Administra nombre, correo, perfil de uso, estado y acceso a instalaciones.</p></div><div className="userHeaderActions"><span className="catalogCount">{users.length} usuarios · {access.filter(item=>item.active).length} asignaciones</span><button type="button" onClick={()=>{setShowNew(v=>!v);setInviteMessage("")}}>+ Nuevo usuario</button></div></div>
 {inviteMessage&&<p className="note">{inviteMessage}</p>}
 {showNew&&<form action={submitInvite} className="adminForm userInviteForm"><h3>Crear usuario</h3><label>Nombre<input name="full_name" required placeholder="Nombre completo"/></label><label>Correo<input name="email" type="email" required placeholder="usuario@correo.cl"/></label><label>Perfil de uso<select name="role" defaultValue="Supervisora">{roles.map(role=><option key={role.value} value={role.value}>{role.label}</option>)}</select></label><label>Estado<select name="active" defaultValue="true"><option value="true">Activo</option><option value="false">Inactivo</option></select></label><button disabled={inviteBusy}>{inviteBusy?"Creando...":"Crear usuario con ALEMSI2026"}</button><small>El usuario queda creado directamente en Supabase Auth. Acceso inicial: correo + ALEMSI2026.</small></form>}
 <div className="userLayout"><aside className="userList">{users.map(item=><button type="button" key={item.id} className={item.id===user.id?"selected":""} onClick={()=>{setSelected(item.id);setEditMessage("");setPasswordMessage("");setTestMessage("")}}><b>{item.full_name||"Nombre pendiente"}</b><span>{item.email||"Correo pendiente"}</span><small>{roleLabel(item.role)} · {item.active?"Activo":"Inactivo"}</small></button>)}</aside>
 <div className="userEditor">{editMessage&&<p className="note">{editMessage}</p>}<form key={user.id} action={submitEdit} className="adminForm userProfileForm"><input type="hidden" name="user_id" value={user.id}/><label>Nombre<input name="full_name" required defaultValue={user.full_name||""}/></label><label>Correo<input name="email" type="email" required defaultValue={user.email||""} disabled={user.id===currentUserId}/>{user.id===currentUserId&&<><input type="hidden" name="email" value={user.email||""}/><small>Por seguridad, tu propio correo de Admin Total no se cambia desde esta ficha.</small></>}</label><label>Perfil de uso<select name="role" defaultValue={user.role}>{roles.map(role=><option key={role.value} value={role.value}>{role.label}</option>)}</select></label><label>Estado<select name="active" defaultValue={String(user.active)} disabled={user.id===currentUserId}><option value="true">Activo</option><option value="false">Inactivo</option></select>{user.id===currentUserId&&<input type="hidden" name="active" value="true"/>}</label><button disabled={editBusy}>{editBusy?"Guardando...":"Guardar usuario"}</button></form>
 <details className="adminForm"><summary style={{cursor:"pointer",fontWeight:800,color:"#0b2f4a",fontSize:18}}>Configurar permisos</summary><p style={{marginTop:12}}>El perfil <b>{roleLabel(user.role)}</b> define la base. Admin Total puede agregar o bloquear funciones individuales. El alcance por instalaciones se administra por separado.</p><div style={{display:"grid",gap:8}}>{(Object.values(CAPABILITIES) as Capability[]).map(capability=>{const override=userOverrides.find(item=>item.module_code===capability);const base=roleCan(user.role,capability);const mode=override?(override.can_view?"allow":"deny"):"inherit";const effective=override?override.can_view:base;return <form key={capability} action={setUserCapabilityOverride} style={{display:"grid",gridTemplateColumns:"minmax(220px,1fr) minmax(170px,220px) auto",gap:8,alignItems:"center",padding:"10px 0",borderBottom:"1px solid #dbe7ec"}}><input type="hidden" name="user_id" value={user.id}/><input type="hidden" name="capability" value={capability}/><span><b>{capabilityLabels[capability]}</b><small style={{display:"block"}}>{effective?"Permitido":"Bloqueado"} · {override?"Excepción individual":`Según perfil ${roleLabel(user.role)}`}</small></span><select name="mode" defaultValue={mode} disabled={user.id===currentUserId}><option value="inherit">Según perfil ({base?"permitido":"bloqueado"})</option><option value="allow">Permitir individualmente</option><option value="deny">Bloquear individualmente</option></select><button disabled={user.id===currentUserId}>Guardar</button></form>})}</div>{user.id===currentUserId&&<small style={{display:"block",marginTop:12}}>Tu cuenta Admin Total está protegida y no admite excepciones desde esta ficha.</small>}</details>
 <details className="adminForm"><summary style={{cursor:"pointer",fontWeight:800,color:"#0b2f4a",fontSize:18}}>Servicios adicionales</summary><p style={{marginTop:12}}>Admin Total define aquí qué servicios adicionales puede usar este usuario.</p><div style={{display:"grid",gap:8}}>{additionalServices.map(service=>{const assigned=additionalServiceUserAccess.some(item=>item.user_id===user.id&&item.service_code===service.service_code&&item.active);return <form key={service.service_code} action={setAdditionalServiceUserAccess}><input type="hidden" name="user_id" value={user.id}/><input type="hidden" name="service_code" value={service.service_code}/><input type="hidden" name="active" value={String(!assigned)}/><span><b>{service.display_name}</b> · {assigned?"Autorizado":"Sin autorización"} · {service.status}</span> <button className={assigned?"removeAccess":""}>{assigned?"Retirar":"Autorizar"}</button></form>})}</div></details><form action={submitTemporaryPassword} className="adminForm"><input type="hidden" name="user_id" value={user.id}/><h3>Clave temporal</h3><p>Asigna la clave temporal genérica <b>ALEMSI2026</b> al usuario seleccionado para ingresar con su correo.</p><button disabled={passwordBusy||!user.email}>{passwordBusy?"Asignando...":"Asignar ALEMSI2026"}</button>{passwordMessage&&<small>{passwordMessage}</small>}</form>
 <div className="adminForm"><h3>Prueba de correo</h3><p>Envía un mensaje real usando el SMTP configurado en este Preview. La prueba solo puede ejecutarla Admin Total.</p><button type="button" disabled={testBusy||!user.email} onClick={testEmail}>{testBusy?"Probando SMTP...":`Probar correo${user.email?` a ${user.email}`:""}`}</button>{testMessage&&<small>{testMessage}</small>}</div>
 <div className="assignmentHead"><div><h3>Instalaciones asignadas</h3><p>Las supervisoras verán solamente las instalaciones activas que tengan asignadas.</p></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente, contrato o instalación"/></div>
 <div className="assignmentList">{installations.map(item=>{const isAssigned=assigned.has(item.id);return <article key={item.id}><span><b>{item.name}</b><small>{item.client} · {item.contract}<br/>{[item.commune,item.city,item.region].filter(Boolean).join(" · ")||"Ubicación pendiente"}</small></span><form action={setUserInstallationAccess}><input type="hidden" name="user_id" value={user.id}/><input type="hidden" name="installation_id" value={item.id}/><input type="hidden" name="granted" value={String(!isAssigned)}/><button className={isAssigned?"removeAccess":""}>{isAssigned?"Retirar":"Asignar"}</button></form></article>})}</div></div></div>
 <p className="catalogNote">El correo identifica la cuenta de acceso. Los cambios quedan trazados. Admin y Operaciones son perfiles independientes.</p></section>;
}
