"use client";
import {useState} from "react";
import {submitSurveyToken} from "./actions";

type Material={material_id:string;name:string;presentation?:string|null;unit?:string|null;authorized_qty:number};
export default function TokenSurveyForm({token,materials,installation}:{token:string;materials:Material[];installation:string}){
  const [values,setValues]=useState<Record<string,number>>({});const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");const [done,setDone]=useState(false);
  async function submit(){setSaving(true);setMessage("");try{const fd=new FormData();fd.set("token",token);fd.set("lines",JSON.stringify(materials.map(m=>({material_id:m.material_id,physical_remainder:Number(values[m.material_id]||0)}))));await submitSurveyToken(fd);setDone(true);setMessage("Conteo confirmado correctamente. La información ya quedó enviada a ALEMSI.");}catch(e:any){setMessage(e?.message||"No se pudo confirmar el conteo");}finally{setSaving(false)}}
  if(done)return <div style={{padding:22,border:"1px solid #b9d8d4",borderRadius:12,background:"#f3fbf9"}}><h2>Conteo enviado</h2><p>{message}</p><p>Puedes cerrar esta página.</p></div>;
  return <div><div style={{display:"grid",gap:10}}>{materials.map(m=>{const rem=Number(values[m.material_id]||0);return <article key={m.material_id} style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) 130px 130px",gap:12,alignItems:"center",padding:14,border:"1px solid #d7e2e7",borderRadius:10}}><div><b>{m.name}</b><small style={{display:"block",color:"#607684"}}>{[m.presentation,m.unit].filter(Boolean).join(" · ")}</small></div><div><small style={{display:"block"}}>Máximo</small><b>{m.authorized_qty}</b></div><label><small style={{display:"block"}}>Remanente físico</small><input type="number" min="0" step="any" value={rem} onChange={e=>setValues(v=>({...v,[m.material_id]:Math.max(0,Number(e.target.value)||0)}))} style={{width:"100%",padding:9}}/></label></article>})}</div><div style={{marginTop:18,padding:16,borderTop:"2px solid #0b6f69"}}><p><b>{installation}</b></p><p style={{fontSize:13,color:"#607684"}}>Registra únicamente lo que queda físicamente. La carencia se calcula automáticamente en ALEMSI.</p>{message&&<p><b>{message}</b></p>}<button type="button" disabled={saving} onClick={submit} style={{padding:"12px 18px",background:"#0b6f69",color:"white",border:0,borderRadius:8,fontWeight:700}}>{saving?"Enviando...":"Confirmar conteo"}</button></div></div>;
}
