import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {documentAlert,mileageAlert,remainingKm} from "@/modules/flota/domain";
import {updateVehicle} from "../actions";
import FleetInspectionCamera from "../FleetInspectionCamera";
import FleetDocumentForm from "../FleetDocumentForm";
import {REQUIRED_FLEET_PHOTOS} from "@/modules/flota/domain";
import {reportPossibleDeterioration,reviewDeterioration,saveFuelEntry,saveMaintenance} from "../operation-actions";
import "../flota.css";

type View="resumen"|"documentos"|"operacion"|"historial";
const dateTime=(v:string|null)=>v?new Intl.DateTimeFormat("es-CL",{dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"—";
const km=(v:number|null)=>v==null?"—":new Intl.NumberFormat("es-CL").format(v)+" km";
export default async function VehiclePage({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{vista?:string}>}){
 const {id}=await params;const q=await searchParams;const notice=(q as any).notice;const view=(["resumen","documentos","operacion","historial"].includes(q.vista||"")?q.vista:"resumen") as View;
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const {data:p}=await supabase.from("user_profiles").select("full_name,role,active").eq("id",user.id).single();if(!p?.active)redirect("/");
 const {data:allowed}=await supabase.rpc("has_additional_service_access",{p_service_code:"flota"});if(p.role!=="Admin Total"&&!allowed)redirect("/");
 const [{data:v,error:vehicleError},{data:docs,error:docsError},{data:uses,error:usesError},{data:maintenance,error:maintenanceError},{data:damage,error:damageError},{data:photos,error:photosError},{data:fuel,error:fuelError},{data:locations,error:locationsError}]=await Promise.all([
  supabase.from("fleet_vehicles").select("*").eq("id",id).maybeSingle(),
  supabase.from("fleet_documents").select("*").eq("vehicle_id",id).order("created_at",{ascending:false}),
  supabase.from("fleet_assignments").select("*").eq("vehicle_id",id).order("taken_at",{ascending:false}),
  supabase.from("fleet_maintenance").select("*").eq("vehicle_id",id).order("service_date",{ascending:false}),
  supabase.from("fleet_deterioration_events").select("*").eq("vehicle_id",id).order("created_at",{ascending:false}),
  supabase.from("fleet_photos").select("id,assignment_id,phase,position,storage_path,captured_at").eq("vehicle_id",id).order("captured_at",{ascending:true}),
  supabase.from("fleet_fuel_entries").select("*").eq("vehicle_id",id).order("recorded_at",{ascending:false}),
  supabase.from("fleet_locations").select("*").eq("vehicle_id",id).order("recorded_at",{ascending:false})
 ]);
 if(vehicleError||docsError||usesError||maintenanceError||damageError||photosError||fuelError||locationsError)throw new Error("No fue posible cargar el expediente completo de Flota.");
 if(!v)notFound();
 const signedPhotos=await Promise.all((photos??[]).map(async(photo:any)=>{
  const {data,error}=await supabase.storage.from("fleet-photos").createSignedUrl(String(photo.storage_path),3600);
  return {...photo,url:error?null:data?.signedUrl??null};
 }));
 const signedDocuments=await Promise.all((docs??[]).map(async(document:any)=>{if(!document.storage_path)return {...document,fileUrl:null};const {data,error}=await supabase.storage.from("fleet-documents").createSignedUrl(String(document.storage_path),3600);return {...document,fileUrl:error?null:data?.signedUrl??null};}));
 let coverUrl:string|null=null;
 if(v.cover_photo_path){
  if(String(v.cover_photo_path).startsWith("/"))coverUrl=String(v.cover_photo_path);
  else{const {data:cover}=await supabase.storage.from("fleet-photos").createSignedUrl(String(v.cover_photo_path),3600);coverUrl=cover?.signedUrl??null;}
 }
 const currentUse=(uses??[]).find((x:any)=>!x.returned_at);const currentDocs=(docs??[]).filter((x:any)=>x.is_current);const openDamage=(damage??[]).filter((x:any)=>["Posible deterioro","Deterioro confirmado"].includes(x.status));
 const oil=mileageAlert(Number(v.current_km),v.next_oil_change_km==null?null:Number(v.next_oil_change_km));const left=remainingKm(Number(v.current_km),v.next_oil_change_km==null?null:Number(v.next_oil_change_km));
 const fuelChronological=[...(fuel??[])].sort((a:any,b:any)=>String(a.recorded_at).localeCompare(String(b.recorded_at)));let previousFull:any=null;let litersSinceFull=0;const efficiencyById=new Map<string,number>();for(const entry of fuelChronological){if(previousFull)litersSinceFull+=Number(entry.liters);if(entry.tank_full){if(previousFull&&Number(entry.odometer_km)>Number(previousFull.odometer_km)&&litersSinceFull>0)efficiencyById.set(entry.id,(Number(entry.odometer_km)-Number(previousFull.odometer_km))/litersSinceFull);previousFull=entry;litersSinceFull=0;}}
 const noticeLabels:Record<string,string>={updated:"Datos del vehículo actualizados.",duplicate:"La patente ya pertenece a otro vehículo.","edit-error":"No fue posible actualizar el vehículo.",taken:"Toma e inspección 7/7 guardadas correctamente.",returned:"Devolución e inspección 7/7 guardadas correctamente.","already-in-use":"El vehículo ya fue tomado por otra sesión. Se recargó su estado actual.","already-returned":"Esta devolución ya estaba registrada. Se recargó el historial.","assignment-missing":"No se encontró la asignación solicitada.","document-saved":"Documento original y período guardados correctamente.","fuel-saved":"Carga de combustible guardada.","maintenance-saved":"Mantención guardada.","damage-saved":"Posible deterioro registrado para revisión humana.","damage-reviewed":"Revisión de deterioro actualizada."};
 return <main className="fleetPage"><header className="fleetHero"><div><p className="fleetEyebrow">ALEMSI · FLOTA</p><h1>{v.plate} · {v.label}</h1><p>{v.brand||""} {v.model||""}{v.year?" · "+v.year:""}</p></div><div className="fleetHeroActions"><Link className="fleetBtn fleetBtnGhost" href="/flota">Volver a Flota</Link></div></header>
 <section className="fleetVehicleProfileHero" aria-label={"Fotografía de "+v.plate}>
  {coverUrl==="/flota/fleet-profiles.webp"?<div className={"fleetProfileSprite fleetProfileSprite"+v.plate} role="img" aria-label={"Fotografía "+v.plate}/>:coverUrl?<img src={coverUrl} alt={"Fotografía de perfil "+v.plate}/>:<div className="fleetPhotoPending"><span>FOTO DEL VEHÍCULO</span><small>Sin fotografía de perfil</small></div>}
  <div className="fleetVehicleProfileInfo"><span className={"fleetStatus "+(v.status==="Disponible"?"fleetStatusOk":v.status==="En uso"?"fleetStatusWarning":"fleetStatusCritical")}>{v.status}</span><strong>{v.plate}</strong><span>{v.label}</span></div>
 </section>
 {notice&&noticeLabels[notice]&&<div className={"fleetNotice "+(["edit-error","duplicate","assignment-missing"].includes(notice)?"fleetNoticeError":"")}>{noticeLabels[notice]}</div>}
 {p.role==="Admin Total"&&<details className="fleetCreate"><summary>Editar datos del vehículo</summary><form action={updateVehicle} className="fleetCreateGrid"><input type="hidden" name="vehicle_id" value={v.id}/><label>Patente<input name="plate" defaultValue={v.plate} required maxLength={10}/></label><label>Nombre o identificación<input name="label" defaultValue={v.label} required maxLength={80}/></label><label>Tipo de vehículo<input name="vehicle_type" defaultValue={v.vehicle_type||""} maxLength={40}/></label><label>Marca<input name="brand" defaultValue={v.brand||""} maxLength={60}/></label><label>Modelo<input name="model" defaultValue={v.model||""} maxLength={60}/></label><label>N° chasis / VIN<input name="chassis_vin" defaultValue={v.chassis_vin||""} maxLength={40}/></label><label>Año<input name="year" type="number" min="1950" max="2100" defaultValue={v.year||""}/></label><label>Kilometraje actual<input name="current_km" type="number" min="0" defaultValue={v.current_km} required/></label><button className="fleetBtn fleetBtnPrimary">Guardar cambios</button></form></details>}
 <nav className="fleetTabs" aria-label="Expediente del vehículo">{(["resumen","documentos","operacion","historial"] as View[]).map(x=><Link key={x} className={"fleetTab "+(view===x?"fleetTabActive":"")} href={"/flota/"+id+"?vista="+x}>{x.toUpperCase()}</Link>)}</nav>
{view==="resumen"&&<><section className="fleetActionPanel fleetActionPanelCamera"><div><span className="fleetStepLabel">ACCIÓN PRINCIPAL</span><h2>{currentUse?"Devolver vehículo":"Tomar vehículo"}</h2><p>{currentUse?"Completa la inspección 7/7 de devolución. Las fotografías quedan asociadas a este uso.":"Toca cada figura para abrir la cámara y completa las 7 fotografías antes de confirmar."}</p></div><FleetInspectionCamera vehicleId={v.id} plate={v.plate} driverName={p.full_name||"Usuario"} currentKm={Number(v.current_km)} assignmentId={currentUse?.id} startKm={currentUse?Number(currentUse.start_km):undefined} mode={currentUse?"return":"take"}/></section><section className="fleetDetailGrid">
  <article className="fleetDetailCard"><h3>Estado actual</h3><strong>{v.status}</strong>{currentUse?<p><b>{currentUse.driver_name}</b><br/>RUT {currentUse.driver_rut}<br/>Desde {dateTime(currentUse.taken_at)}<br/>Inicio {km(currentUse.start_km)}</p>:<p className="fleetMuted">Sin asignación abierta.</p>}</article>
  <article className="fleetDetailCard"><h3>Kilometraje</h3><strong>{km(Number(v.current_km))}</strong><p>Próximo aceite: {km(v.next_oil_change_km)}</p><span className={"fleetStatus "+(oil==="critical"?"fleetStatusCritical":oil==="warning"?"fleetStatusWarning":"fleetStatusOk")}>{left==null?"Sin programación":left<=0?"Servicio requerido":km(left)+" restantes"}</span></article>
  <article className="fleetDetailCard"><h3>Atenciones</h3><strong>{openDamage.length}</strong><p>deterioro(s) abiertos</p><p>{currentDocs.filter((d:any)=>documentAlert(d.expires_at)!=="ok").length} documento(s) próximos a vencer o sin vigencia.</p></article>
 </section></>}
 {view==="documentos"&&<section><div className="fleetSectionHead"><h2>Expediente documental</h2><p>Original privado, lectura dirigida, confirmación humana y renovaciones sin sobrescribir versiones anteriores.</p></div>
 <details className="fleetCreate" open={currentDocs.length===0}><summary>+ Agregar / renovar documento</summary><FleetDocumentForm vehicleId={v.id} plate={v.plate} vin={v.chassis_vin||""}/></details>
 <h2>Documentos registrados</h2>{signedDocuments.length===0?<div className="fleetEmpty"><h3>Sin documentos registrados</h3><p>Selecciona el archivo original, léelo, confirma los datos y guarda el período.</p></div>:<div className="fleetDocumentsTable"><div className="fleetDocumentsHeader"><span>Período</span><span>Documento</span><span>Vigencia</span><span>Estado</span><span>Acciones</span></div>{signedDocuments.map((d:any)=><article className="fleetDocRow" key={d.id}><span>Versión {d.version}<small>{d.valid_from||"Sin inicio"} → {d.expires_at||"Sin vencimiento"}</small></span><div><strong>{String(d.kind).replaceAll("_"," ")}</strong><small>{d.source_file_name||"Sin archivo original"}</small></div><span>{d.is_current?"Período vigente":"Histórico"}</span><span className={"fleetStatus "+(!d.is_current?"":documentAlert(d.expires_at)==="critical"?"fleetStatusCritical":documentAlert(d.expires_at)==="warning"?"fleetStatusWarning":"fleetStatusOk")}>{!d.is_current?"Histórico":documentAlert(d.expires_at)==="ok"?"Vigente":"Requiere atención"}</span><div>{d.fileUrl?<a className="fleetBtn fleetBtnGhost" href={d.fileUrl} target="_blank" rel="noreferrer">Ver archivo</a>:<span className="fleetMuted">Archivo no disponible</span>}</div>{d.services?.length>0&&<div className="fleetDocServices">{d.services.slice(0,6).map((x:string)=><span key={x}>✓ {x}</span>)}</div>}</article>)}</div>}</section>}
 {view==="operacion"&&<section><div className="fleetSectionHead"><h2>Operación del vehículo</h2><p>Combustible, mantenciones y revisiones de deterioro permanecen separados de Materiales y Rendiciones.</p></div>
  <div className="fleetOperationGrid"><details className="fleetCreate"><summary>+ Registrar combustible</summary><form action={saveFuelEntry} className="fleetCreateGrid"><input type="hidden" name="vehicle_id" value={v.id}/>{currentUse&&<input type="hidden" name="assignment_id" value={currentUse.id}/>}<label>Litros<input name="liters" type="number" min="0.01" step="0.01" required/></label><label>Monto CLP<input name="amount" type="number" min="0" step="1" required/></label><label>Odómetro<input name="odometer_km" type="number" min="0" defaultValue={v.current_km} required/></label><label>Nivel<select name="fuel_level" defaultValue=""><option value="">Sin lectura</option>{["FULL","3/4","1/2","1/4","RESERVA"].map(x=><option key={x}>{x}</option>)}</select></label><label className="fleetCheck"><input name="tank_full" type="checkbox"/> Tanque lleno confirmado</label><label>Comprobante (imagen)<input name="receipt" type="file" accept="image/jpeg,image/png,image/webp"/></label><button className="fleetBtn fleetBtnPrimary">Guardar combustible</button></form></details>
  <details className="fleetCreate"><summary>+ Registrar mantención</summary><form action={saveMaintenance} className="fleetCreateGrid"><input type="hidden" name="vehicle_id" value={v.id}/><label>Fecha<input name="service_date" type="date" required/></label><label>Trabajo realizado<input name="activity" required/></label><label>Proveedor / taller<input name="provider"/></label><label>Kilometraje<input name="odometer_km" type="number" min="0" defaultValue={v.current_km}/></label><label>Costo CLP<input name="cost" type="number" min="0" step="1"/></label><label>Próximo servicio km<input name="next_km" type="number" min="0"/></label><label>Próximo servicio fecha<input name="next_date" type="date"/></label><label>Comprobante (imagen)<input name="receipt" type="file" accept="image/jpeg,image/png,image/webp"/></label><label className="fleetWide">Detalle<textarea name="notes"/></label><button className="fleetBtn fleetBtnPrimary">Guardar mantención</button></form></details>
  <details className="fleetCreate"><summary>+ Marcar posible deterioro</summary><form action={reportPossibleDeterioration} className="fleetCreateGrid"><input type="hidden" name="vehicle_id" value={v.id}/><label>Uso<select name="assignment_id" required><option value="">Seleccionar</option>{(uses??[]).filter((x:any)=>x.returned_at).map((x:any)=><option key={x.id} value={x.id}>{dateTime(x.taken_at)} · {x.driver_name}</option>)}</select></label><label>Posición<select name="position" required>{REQUIRED_FLEET_PHOTOS.map(x=><option key={x}>{x}</option>)}</select></label><label className="fleetWide">Observación humana<textarea name="note" placeholder="Posible deterioro · Requiere revisión"/></label><button className="fleetBtn fleetBtnPrimary">Enviar a revisión</button></form></details></div>
  <h2>Combustible</h2><div className="fleetTable">{(fuel??[]).map((entry:any)=><article key={entry.id}><div><strong>{Number(entry.liters).toLocaleString("es-CL")} L · $ {Number(entry.amount).toLocaleString("es-CL")}</strong><span>{dateTime(entry.recorded_at)} · {km(entry.odometer_km)} · {entry.tank_full?"Lleno":"Parcial"}</span></div><b>{efficiencyById.has(entry.id)?efficiencyById.get(entry.id)!.toLocaleString("es-CL",{maximumFractionDigits:2})+" km/L":"Rendimiento pendiente de ciclo FULL→FULL"}</b></article>)}{!fuel?.length&&<p className="fleetMuted">Sin cargas registradas.</p>}</div>
  <h2>Mantenciones</h2><div className="fleetTable">{(maintenance??[]).map((entry:any)=><article key={entry.id}><div><strong>{entry.activity}</strong><span>{entry.service_date} · {km(entry.odometer_km)} · {entry.notes||"Sin detalle"}</span></div><b>{entry.cost==null?"Sin costo informado":"$ "+Number(entry.cost).toLocaleString("es-CL")}</b></article>)}{!maintenance?.length&&<p className="fleetMuted">Sin mantenciones registradas.</p>}</div>
  <h2>Deterioros y revisiones</h2><div className="fleetTable">{(damage??[]).map((entry:any)=><article key={entry.id}><div><strong>{entry.status} · {entry.position||"Sin posición"}</strong><span>{dateTime(entry.created_at)} · {entry.review_note||"Requiere revisión"}</span></div>{["Admin Total","Admin","Gerencia","Operaciones"].includes(p.role)&&<form action={reviewDeterioration} className="fleetInlineReview"><input type="hidden" name="vehicle_id" value={v.id}/><input type="hidden" name="event_id" value={entry.id}/><select name="status" defaultValue={entry.status}><option value="Deterioro confirmado">Confirmado</option><option value="Sin deterioro">No corresponde</option><option value="Ya existente">Ya existía</option><option value="Reparado">Reparado/cerrado</option></select><input name="note" placeholder="Conclusión humana"/><button className="fleetBtn fleetBtnGhost">Guardar revisión</button></form>}</article>)}{!damage?.length&&<p className="fleetMuted">Sin revisiones de deterioro.</p>}</div>
 </section>}
 {view==="historial"&&<section><h2>Historial cronológico</h2>
  <div className="fleetAssignmentHistory">{(uses??[]).map((use:any)=>{const evidence=signedPhotos.filter((photo:any)=>photo.assignment_id===use.id);return <article className="fleetAssignmentCard" key={use.id}><header><div><small>{dateTime(use.taken_at)}</small><h3>{use.returned_at?"Uso terminado":"Uso en curso"}</h3><p><b>{use.driver_name}</b> · RUT {use.driver_rut}<br/>{km(use.start_km)}{use.end_km==null?"":" → "+km(use.end_km)}{use.end_km==null?"":" · Distancia "+km(Number(use.end_km)-Number(use.start_km))}</p></div><span className={"fleetStatus "+(use.returned_at?"fleetStatusOk":"fleetStatusWarning")}>{use.returned_at?"Devuelto":"En uso"}</span></header>
   {(["Toma","Devolución"] as const).map(phase=>{const phasePhotos=evidence.filter((photo:any)=>photo.phase===phase);if(!phasePhotos.length)return null;return <details className="fleetEvidence" key={phase}><summary>{phase} · {phasePhotos.length}/7 fotografías · {dateTime(phasePhotos[0]?.captured_at)}</summary><div className="fleetEvidenceGrid">{phasePhotos.map((photo:any)=><figure key={photo.id}>{photo.url?<a href={photo.url} target="_blank" rel="noreferrer"><img src={photo.url} alt={phase+" · "+photo.position}/></a>:<div className="fleetPhotoUnavailable">Archivo no disponible</div>}<figcaption><strong>{photo.position}</strong><span>{dateTime(photo.captured_at)}</span></figcaption></figure>)}</div></details>})}
   {!evidence.length&&<p className="fleetMuted">Este uso histórico no tiene fotografías registradas.</p>}</article>})}</div>
  <div className="fleetTimeline">{[...(docs??[]).map((x:any)=>({at:x.created_at,title:"Documento · "+String(x.kind).replaceAll("_"," ")+" · versión "+x.version,body:(x.valid_from||"Sin inicio")+" → "+(x.expires_at||"Sin vencimiento")+(x.is_current?" · Vigente":" · Histórico")})),...(fuel??[]).map((x:any)=>({at:x.recorded_at,title:"Combustible · "+Number(x.liters).toLocaleString("es-CL")+" L",body:km(x.odometer_km)+" · "+(x.tank_full?"Lleno confirmado":"Carga parcial")+" · $ "+Number(x.amount).toLocaleString("es-CL")})),...(maintenance??[]).map((x:any)=>({at:x.service_date,title:"Mantención · "+x.activity,body:(x.cost!=null?"$ "+Number(x.cost).toLocaleString("es-CL")+" · ":"")+km(x.odometer_km)+(x.notes?" · "+x.notes:"")})),...(damage??[]).map((x:any)=>({at:x.created_at,title:"Deterioro · "+x.status,body:(x.position?x.position+" · ":"")+(x.review_note||x.ai_summary||"Revisión visual")})),...(locations??[]).map((x:any)=>({at:x.recorded_at,title:"Ubicación puntual · "+x.event_type,body:Number(x.latitude).toFixed(5)+", "+Number(x.longitude).toFixed(5)+(x.accuracy_m!=null?" · precisión "+Math.round(Number(x.accuracy_m))+" m":"")}))].sort((a,b)=>String(b.at).localeCompare(String(a.at))).map((e,i)=><article key={i}><small>{dateTime(e.at)}</small><h3>{e.title}</h3><p>{e.body}</p></article>)}</div>{!(uses?.length||docs?.length||fuel?.length||maintenance?.length||damage?.length||locations?.length)&&<div className="fleetEmpty"><p>Aún no existen eventos para este vehículo.</p></div>}</section>}
 </main>;
}
