import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {documentAlert,mileageAlert,remainingKm} from "@/modules/flota/domain";
import {returnVehicle,takeVehicle,updateVehicle,saveFleetDocument} from "../actions";
import {FLEET_DOCUMENT_TEMPLATES} from "@/modules/flota/document-reader";
import "../flota.css";

type View="resumen"|"documentos"|"historial";
const dateTime=(v:string|null)=>v?new Intl.DateTimeFormat("es-CL",{dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"—";
const km=(v:number|null)=>v==null?"—":new Intl.NumberFormat("es-CL").format(v)+" km";
export default async function VehiclePage({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{vista?:string}>}){
 const {id}=await params;const q=await searchParams;const notice=(q as any).notice;const view=(["resumen","documentos","historial"].includes(q.vista||"")?q.vista:"resumen") as View;
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const {data:p}=await supabase.from("user_profiles").select("full_name,role,active").eq("id",user.id).single();if(!p?.active)redirect("/");
 const {data:allowed}=await supabase.rpc("has_additional_service_access",{p_service_code:"flota"});if(p.role!=="Admin Total"&&!allowed)redirect("/");
 const [{data:v},{data:docs},{data:uses},{data:maintenance},{data:damage}]=await Promise.all([
  supabase.from("fleet_vehicles").select("*").eq("id",id).maybeSingle(),
  supabase.from("fleet_documents").select("*").eq("vehicle_id",id).order("created_at",{ascending:false}),
  supabase.from("fleet_assignments").select("*").eq("vehicle_id",id).order("taken_at",{ascending:false}),
  supabase.from("fleet_maintenance").select("*").eq("vehicle_id",id).order("service_date",{ascending:false}),
  supabase.from("fleet_deterioration_events").select("*").eq("vehicle_id",id).order("created_at",{ascending:false})
 ]);if(!v)notFound();
 const currentUse=(uses??[]).find((x:any)=>!x.returned_at);const currentDocs=(docs??[]).filter((x:any)=>x.is_current);const openDamage=(damage??[]).filter((x:any)=>["Posible deterioro","Deterioro confirmado"].includes(x.status));
 const oil=mileageAlert(Number(v.current_km),v.next_oil_change_km==null?null:Number(v.next_oil_change_km));const left=remainingKm(Number(v.current_km),v.next_oil_change_km==null?null:Number(v.next_oil_change_km));
 return <main className="fleetPage"><header className="fleetHero"><div><p className="fleetEyebrow">ALEMSI · FLOTA</p><h1>{v.plate} · {v.label}</h1><p>{v.brand||""} {v.model||""}{v.year?" · "+v.year:""}</p></div><div className="fleetHeroActions"><Link className="fleetBtn fleetBtnGhost" href="/flota">Volver a Flota</Link></div></header>
 {notice&&<div className={"fleetNotice "+(notice==="edit-error"||notice==="duplicate"?"fleetNoticeError":"")}>{notice==="updated"?"Datos del vehículo actualizados.":notice==="duplicate"?"La patente ya pertenece a otro vehículo.":"No fue posible actualizar el vehículo."}</div>}
 {p.role==="Admin Total"&&<details className="fleetCreate"><summary>Editar datos del vehículo</summary><form action={updateVehicle} className="fleetCreateGrid"><input type="hidden" name="vehicle_id" value={v.id}/><label>Patente<input name="plate" defaultValue={v.plate} required maxLength={10}/></label><label>Nombre o identificación<input name="label" defaultValue={v.label} required maxLength={80}/></label><label>Tipo de vehículo<input name="vehicle_type" defaultValue={v.vehicle_type||""} maxLength={40}/></label><label>Marca<input name="brand" defaultValue={v.brand||""} maxLength={60}/></label><label>Modelo<input name="model" defaultValue={v.model||""} maxLength={60}/></label><label>N° chasis / VIN<input name="chassis_vin" defaultValue={v.chassis_vin||""} maxLength={40}/></label><label>Año<input name="year" type="number" min="1950" max="2100" defaultValue={v.year||""}/></label><label>Kilometraje actual<input name="current_km" type="number" min="0" defaultValue={v.current_km} required/></label><button className="fleetBtn fleetBtnPrimary">Guardar cambios</button></form></details>}
 <nav className="fleetTabs" aria-label="Expediente del vehículo">{(["resumen","documentos","historial"] as View[]).map(x=><Link key={x} className={"fleetTab "+(view===x?"fleetTabActive":"")} href={"/flota/"+id+"?vista="+x}>{x.toUpperCase()}</Link>)}</nav>
{view==="resumen"&&<><section className="fleetActionPanel"><div><span className="fleetStepLabel">ACCIÓN PRINCIPAL</span><h2>{currentUse?"Devolver vehículo":"Tomar vehículo"}</h2><p>{currentUse?"Registra el kilometraje final y cualquier observación antes de cerrar el uso.":"Registra quién lo toma y el kilometraje visible. La inspección fotográfica 7/7 se incorporará en el siguiente bloque."}</p></div>
 {currentUse?<form action={returnVehicle} className="fleetActionForm"><input type="hidden" name="vehicle_id" value={v.id}/><input type="hidden" name="assignment_id" value={currentUse.id}/><label>Kilometraje final<input name="end_km" type="number" min={currentUse.start_km} defaultValue={v.current_km} required/></label><label>Observación<textarea name="comment" placeholder="Sin observaciones"/></label><button className="fleetBtn fleetBtnPrimary">Confirmar devolución</button></form>:
 <form action={takeVehicle} className="fleetActionForm"><input type="hidden" name="vehicle_id" value={v.id}/><label>Conductor<input value={p.full_name||"Usuario"} readOnly/></label><label>RUT<input name="driver_rut" required placeholder="12.345.678-9"/></label><label>Kilometraje inicial<input name="start_km" type="number" min={v.current_km} defaultValue={v.current_km} required/></label><label>Observación<textarea name="comment" placeholder="Sin observaciones"/></label><button className="fleetBtn fleetBtnPrimary">Confirmar toma</button></form>}</section><section className="fleetDetailGrid">
  <article className="fleetDetailCard"><h3>Estado actual</h3><strong>{v.status}</strong>{currentUse?<p><b>{currentUse.driver_name}</b><br/>RUT {currentUse.driver_rut}<br/>Desde {dateTime(currentUse.taken_at)}<br/>Inicio {km(currentUse.start_km)}</p>:<p className="fleetMuted">Sin asignación abierta.</p>}</article>
  <article className="fleetDetailCard"><h3>Kilometraje</h3><strong>{km(Number(v.current_km))}</strong><p>Próximo aceite: {km(v.next_oil_change_km)}</p><span className={"fleetStatus "+(oil==="critical"?"fleetStatusCritical":oil==="warning"?"fleetStatusWarning":"fleetStatusOk")}>{left==null?"Sin programación":left<=0?"Servicio requerido":km(left)+" restantes"}</span></article>
  <article className="fleetDetailCard"><h3>Atenciones</h3><strong>{openDamage.length}</strong><p>deterioro(s) abiertos</p><p>{currentDocs.filter((d:any)=>documentAlert(d.expires_at)!=="ok").length} documento(s) próximos a vencer o sin vigencia.</p></article>
 </section></>}
 {view==="documentos"&&<section><div className="fleetSectionHead"><h2>Expediente documental</h2><p>Acceso rápido, vigencias y renovaciones. El lector dirigido usa plantillas específicas y los datos siempre se confirman antes de operar.</p></div>
 <details className="fleetCreate" open={currentDocs.length===0}><summary>+ Agregar / renovar documento</summary><form action={saveFleetDocument} className="fleetCreateGrid"><input type="hidden" name="vehicle_id" value={v.id}/>
 <label>Tipo<select name="kind" required defaultValue=""><option value="" disabled>Seleccionar</option>{FLEET_DOCUMENT_TEMPLATES.map(t=><option key={t.kind} value={t.kind}>{t.kind.replaceAll("_"," ")}</option>)}</select></label>
 <label>Archivo para lectura<input name="document_file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"/></label>
 <div className="fleetReaderHint"><strong>LECTOR DIRIGIDO</strong><span>Preparado para identificar tipo, patente/VIN, fechas y campos prioritarios. La conexión al motor visual queda pendiente; por ahora confirma los datos leídos antes de guardar.</span></div>
 <label>Patente del documento<input name="document_plate" defaultValue={v.plate}/></label><label>VIN / Chasis<input name="document_vin" defaultValue={v.chassis_vin||""}/></label>
 <label>Vigente desde<input name="valid_from" type="date"/></label><label>Vence<input name="expires_at" type="date"/></label>
 <label>Aseguradora<input name="insurer"/></label><label>N° póliza<input name="policy_number"/></label><label>Teléfono asistencia<input name="assistance_phone"/></label>
 <label className="fleetWide">Servicios / coberturas<input name="services" placeholder="Grúa, auto de reemplazo, asistencia legal..."/></label>
 <label className="fleetWide">Instrucciones<textarea name="instructions" placeholder="Indicaciones rápidas para usar el seguro o asistencia"/></label>
 <button className="fleetBtn fleetBtnPrimary">Confirmar y guardar período</button></form></details>
 <h2>Documentos vigentes</h2>{currentDocs.length===0?<div className="fleetEmpty"><h3>Sin documentos registrados</h3><p>Agrega el primer documento. Las renovaciones conservarán las versiones anteriores.</p></div>:currentDocs.map((d:any)=><article className="fleetDocRow" key={d.id}><div><strong>{String(d.kind).replaceAll("_"," ")}</strong><small>Versión {d.version}{d.policy_number?" · "+d.policy_number:""}</small></div><span>{d.valid_from||"—"} → {d.expires_at||"Sin vencimiento"}</span><span className={"fleetStatus "+(documentAlert(d.expires_at)==="critical"?"fleetStatusCritical":documentAlert(d.expires_at)==="warning"?"fleetStatusWarning":"fleetStatusOk")}>{documentAlert(d.expires_at)==="ok"?"Vigente":"Requiere atención"}</span><div className="fleetDocServices">{(d.services??[]).slice(0,6).map((x:string)=><span key={x}>✓ {x}</span>)}</div></article>)}</section>}
 {view==="historial"&&<section><h2>Historial cronológico</h2><div className="fleetTimeline">{[...(uses??[]).map((x:any)=>({at:x.taken_at,title:"Uso de vehículo",body:x.driver_name+" · "+km(x.start_km)+(x.returned_at?" → "+km(x.end_km):" · En curso")})),...(maintenance??[]).map((x:any)=>({at:x.service_date,title:x.activity,body:(x.cost!=null?"$ "+Number(x.cost).toLocaleString("es-CL")+" · ":"")+km(x.odometer_km)})),...(damage??[]).map((x:any)=>({at:x.created_at,title:x.status,body:x.review_note||x.ai_summary||"Revisión visual"}))].sort((a,b)=>String(b.at).localeCompare(String(a.at))).map((e,i)=><article key={i}><small>{dateTime(e.at)}</small><h3>{e.title}</h3><p>{e.body}</p></article>)}</div>{!(uses?.length||maintenance?.length||damage?.length)&&<div className="fleetEmpty"><p>Aún no existen eventos para este vehículo.</p></div>}</section>}
 </main>;
}
