"use client";
import {useMemo,useState} from "react";
import type {FleetDocumentTemplate,FleetDocumentKind} from "@/modules/flota/document-reader";

type Doc={id:string;kind:string;version:number;valid_from:string|null;expires_at:string|null;policy_number:string|null;reader_status:string;services:string[]|null;confirmed_data:Record<string,unknown>|null;source_file_name:string|null;file_url:string|null;is_current:boolean};
const labels:Record<string,string>={PADRON:"Padrón",REVISION_TECNICA:"Revisión técnica",PERMISO_CIRCULACION:"Permiso de circulación",SOAP:"SOAP",SEGURO_AUTOMOTRIZ:"Seguro automotriz",MANTENCION:"Cambio de aceite",OTRO:"Otro"};
const dateLabel=(value:string|null)=>value?new Intl.DateTimeFormat("es-CL").format(new Date(value+"T12:00:00")):"—";
const fieldLabels:Record<string,string>={vin:"VIN / Chasis",year:"Año",brand:"Marca",color:"Color",model:"Modelo",owner:"Propietario",plate:"Patente",engine:"Motor",issued_at:"Fecha de emisión",owner_rut:"RUT propietario",valid_from:"Vigente desde",expires_at:"Vencimiento",vehicle_type:"Tipo de vehículo",result:"Resultado",reviewed_at:"Fecha de revisión",plant:"Planta revisora",municipality:"Municipalidad",period:"Período",amount:"Monto",insurer:"Aseguradora",policy_number:"N.º de póliza",deductible:"Deducible",assistance_phone:"Teléfono de asistencia",service_date:"Fecha del servicio",odometer_km:"Kilometraje del servicio",activity:"Actividad",next_service_km:"Próximo servicio (km)",services:"Servicios / coberturas",instructions:"Instrucciones"};
const fieldLabel=(key:string)=>fieldLabels[key]??key.replaceAll("_"," ");
function alert(expires:string|null){if(!expires)return "ok";const days=Math.ceil((new Date(expires+"T23:59:59").getTime()-Date.now())/86400000);return days<=5?"critical":days<=20?"warning":"ok";}
export default function FleetDocumentManager({vehicle,templates,documents,saveAction}:{vehicle:{id:string;plate:string;chassis_vin:string|null};templates:FleetDocumentTemplate[];documents:Doc[];saveAction:(data:FormData)=>void}){
 const [kind,setKind]=useState<FleetDocumentKind | "">("");const [file,setFile]=useState<File|null>(null);const [values,setValues]=useState<Record<string,string>>({plate:vehicle.plate,vin:vehicle.chassis_vin||""});const [reading,setReading]=useState(false);const [message,setMessage]=useState("");const [selected,setSelected]=useState<Doc|null>(null);
 const template=useMemo(()=>templates.find(x=>x.kind===kind),[kind,templates]);
 async function readDocument(){if(!file||!kind)return;setReading(true);setMessage("Leyendo documento…");try{const fd=new FormData();fd.set("file",file);fd.set("kind",kind);fd.set("vehicle_id",vehicle.id);const res=await fetch("/api/flota/leer-documento",{method:"POST",body:fd});const body=await res.json();if(!res.ok)throw new Error(body.error||"No se pudo leer.");const next={...values};for(const [key,value] of Object.entries(body.data||{}))if(value!=null)next[key]=Array.isArray(value)?value.join(", "):String(value);setValues(next);setMessage(body.requires_review?"Lectura completada. Revisa especialmente patente/VIN antes de guardar.":"Lectura completada. Confirma los datos antes de guardar.");}catch(error){setMessage(error instanceof Error?error.message:"No se pudo leer el documento.");}finally{setReading(false);}}
 const current=documents.filter(x=>x.is_current);
 return <section>
  <details className="fleetCreate" open={current.length===0}><summary>+ Agregar / renovar documento</summary>
   <form action={saveAction} className="fleetCreateGrid" encType="multipart/form-data">
    <input type="hidden" name="vehicle_id" value={vehicle.id}/><input type="hidden" name="confirmed_data_json" value={JSON.stringify(values)}/>
    <label>Tipo<select name="kind" required value={kind} onChange={e=>{setKind(e.target.value as FleetDocumentKind);setValues({plate:vehicle.plate,vin:vehicle.chassis_vin||""});setMessage("");}}><option value="" disabled>Seleccionar</option>{templates.map(t=><option key={t.kind} value={t.kind}>{labels[t.kind]||t.kind}</option>)}</select></label>
    <label>Archivo original<input name="document_file" type="file" required accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>
    <div className="fleetReaderHint"><strong>LECTOR DIRIGIDO</strong><span>{message||"Selecciona tipo y archivo. La lectura propone datos; tú los confirmas antes de guardar."}</span><button type="button" className="fleetBtn fleetBtnGhost" disabled={!file||!kind||reading} onClick={readDocument}>{reading?"Leyendo…":"Leer documento"}</button></div>
    {template?.fields.map(field=><label key={field.key} className={field.key==="activity"?"fleetWide":""}>{field.label}<input name={"field_"+field.key} required={field.required} value={values[field.key]||""} onChange={e=>setValues({...values,[field.key]:e.target.value})} type={field.key.includes("date")||field.key.endsWith("_at")||field.key==="valid_from"||field.key==="expires_at"?"date":field.key.includes("km")||field.key==="amount"||field.key==="year"?"number":"text"}/></label>)}
    {template?.serviceTerms?.length?<label className="fleetWide">Servicios / coberturas<input value={values.services||""} onChange={e=>setValues({...values,services:e.target.value})} placeholder="Grúa, auto de reemplazo, asistencia legal..."/></label>:null}
    {template?<label className="fleetWide">Instrucciones<textarea value={values.instructions||""} onChange={e=>setValues({...values,instructions:e.target.value})} placeholder="Observaciones o instrucciones operativas"/></label>:null}
    <button className="fleetBtn fleetBtnPrimary" disabled={!template||!file}>Confirmar y guardar documento</button>
   </form>
  </details>
  <h2>Documentos registrados</h2>
  {current.length===0?<div className="fleetEmpty"><h3>Sin documentos registrados</h3><p>Carga el archivo original, confirma los datos y guarda el período.</p></div>:
   <div>{current.map(doc=>{const state=alert(doc.expires_at);return <article className="fleetDocRow" key={doc.id}><button type="button" className="fleetDocNameButton" onClick={()=>setSelected(doc)}><strong>{labels[doc.kind]||doc.kind}</strong><small>Versión {doc.version}</small></button><span>Emisión: {dateLabel(doc.valid_from)}<br/>Vencimiento: {doc.expires_at?dateLabel(doc.expires_at):"Sin vencimiento"}</span><span className={"fleetStatus "+(state==="critical"?"fleetStatusCritical":state==="warning"?"fleetStatusWarning":"fleetStatusOk")}>{state==="critical"?(doc.expires_at&&new Date(doc.expires_at+"T23:59:59").getTime()<Date.now()?"Vencido":"Vence pronto"):state==="warning"?"Próximo a vencer":"Vigente"}</span>{doc.file_url?<a className="fleetBtn fleetBtnGhost" href={doc.file_url} target="_blank" rel="noreferrer">Abrir original</a>:<span className="fleetMuted">Sin archivo</span>}</article>})}</div>}
  {selected&&<div className="fleetDocumentDetail"><div className="fleetSectionHead"><div><p className="fleetEyebrow">DETALLE DEL DOCUMENTO</p><h2>{labels[selected.kind]||selected.kind}</h2></div><button type="button" className="fleetBtn fleetBtnGhost" onClick={()=>setSelected(null)}>Volver a lista</button></div><div className="fleetDetailGrid">{Object.entries(selected.confirmed_data||{}).filter(([,v])=>v!==null&&v!==""&&!(Array.isArray(v)&&v.length===0)).map(([key,value])=><article className="fleetDetailCard" key={key}><h3>{fieldLabel(key)}</h3><p>{Array.isArray(value)?value.join(", "):String(value)}</p></article>)}</div><p><b>Archivo:</b> {selected.source_file_name||"Sin nombre registrado"}</p>{selected.file_url?<a className="fleetBtn fleetBtnPrimary" href={selected.file_url} target="_blank" rel="noreferrer">Abrir documento original</a>:null}</div>}
 </section>;
}
