"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";

const clean=(value:FormDataEntryValue|null,max=1000)=>String(value??"").trim().slice(0,max);
async function fleetContext(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const [{data:profile},{data:allowed}]=await Promise.all([supabase.from("user_profiles").select("role,active").eq("id",user.id).single(),supabase.rpc("has_additional_service_access",{p_service_code:"flota"})]);if(!profile?.active||!allowed)throw new Error("No tienes acceso a Flota.");return{supabase,user,profile};}
async function uploadEvidence(supabase:any,file:FormDataEntryValue|null,folder:string){if(!(file instanceof File)||!file.size)return null;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>8*1024*1024)throw new Error("El comprobante debe ser JPG, PNG o WEBP de hasta 8 MB.");const ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";const path=`evidence/${folder}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from("fleet-photos").upload(path,await file.arrayBuffer(),{contentType:file.type,upsert:false});if(error)throw new Error("No fue posible guardar el comprobante.");return path;}

export async function saveFuelEntry(formData:FormData){const{supabase,user}=await fleetContext();const vehicleId=clean(formData.get("vehicle_id"),80),assignmentId=clean(formData.get("assignment_id"),80)||null;const odometer=Number(formData.get("odometer_km")),liters=Number(formData.get("liters")),amount=Number(formData.get("amount"));const fuelLevel=clean(formData.get("fuel_level"),10)||null,tankFull=formData.get("tank_full")==="on";if(!vehicleId||!Number.isInteger(odometer)||odometer<0||!Number.isFinite(liters)||liters<=0||!Number.isInteger(amount)||amount<0)throw new Error("Revisa litros, monto y odómetro.");const receipt=await uploadEvidence(supabase,formData.get("receipt"),`fuel/${vehicleId}`);const {error}=await supabase.from("fleet_fuel_entries").insert({vehicle_id:vehicleId,assignment_id:assignmentId,odometer_km:odometer,liters,amount,fuel_level:fuelLevel,tank_full:tankFull,receipt_storage_path:receipt,recorded_by:user.id});if(error){if(receipt)await supabase.storage.from("fleet-photos").remove([receipt]);throw new Error("No fue posible guardar la carga de combustible.");}revalidatePath(`/flota/${vehicleId}`);redirect(`/flota/${vehicleId}?vista=operacion&notice=fuel-saved`);}

export async function saveMaintenance(formData:FormData){const{supabase,user}=await fleetContext();const vehicleId=clean(formData.get("vehicle_id"),80),activity=clean(formData.get("activity"),300),provider=clean(formData.get("provider"),200),serviceDate=clean(formData.get("service_date"),10);const odometerRaw=clean(formData.get("odometer_km"),20),costRaw=clean(formData.get("cost"),30),nextKmRaw=clean(formData.get("next_km"),20);const odometer=odometerRaw?Number(odometerRaw):null,cost=costRaw?Number(costRaw):null,nextKm=nextKmRaw?Number(nextKmRaw):null,nextDate=clean(formData.get("next_date"),10)||null,detail=clean(formData.get("notes"),1200);if(!vehicleId||!activity||!serviceDate||odometer!=null&&(!Number.isInteger(odometer)||odometer<0)||cost!=null&&(!Number.isFinite(cost)||cost<0)||nextKm!=null&&(!Number.isInteger(nextKm)||nextKm<0))throw new Error("Revisa los datos de mantención.");const document=await uploadEvidence(supabase,formData.get("receipt"),`maintenance/${vehicleId}`);const notes=[provider?`Proveedor/taller: ${provider}`:"",detail].filter(Boolean).join("\n")||null;const {error}=await supabase.from("fleet_maintenance").insert({vehicle_id:vehicleId,activity,service_date:serviceDate,odometer_km:odometer,cost,next_date:nextDate,next_km:nextKm,document_storage_path:document,notes,recorded_by:user.id});if(error){if(document)await supabase.storage.from("fleet-photos").remove([document]);throw new Error("No fue posible guardar la mantención.");}if(nextKm!=null)await supabase.from("fleet_vehicles").update({next_oil_change_km:nextKm,updated_at:new Date().toISOString()}).eq("id",vehicleId);revalidatePath("/flota");revalidatePath(`/flota/${vehicleId}`);redirect(`/flota/${vehicleId}?vista=operacion&notice=maintenance-saved`);}

export async function reportPossibleDeterioration(formData:FormData){const{supabase}=await fleetContext();const vehicleId=clean(formData.get("vehicle_id"),80),assignmentId=clean(formData.get("assignment_id"),80),position=clean(formData.get("position"),40),note=clean(formData.get("note"),800);if(!vehicleId||!assignmentId||!position)throw new Error("Selecciona uso y posición.");const {error}=await supabase.from("fleet_deterioration_events").insert({vehicle_id:vehicleId,assignment_id:assignmentId,position,status:"Posible deterioro",review_note:note||"Requiere revisión"});if(error)throw new Error("No fue posible registrar la revisión.");revalidatePath(`/flota/${vehicleId}`);redirect(`/flota/${vehicleId}?vista=operacion&notice=damage-saved`);}

export async function reviewDeterioration(formData:FormData){const{supabase,user,profile}=await fleetContext();if(!["Admin Total","Admin","Gerencia","Operaciones"].includes(profile.role))throw new Error("Tu perfil no puede resolver deterioros.");const vehicleId=clean(formData.get("vehicle_id"),80),eventId=clean(formData.get("event_id"),80),status=clean(formData.get("status"),40),note=clean(formData.get("note"),800);const allowed=new Set(["Deterioro confirmado","Sin deterioro","Ya existente","Reparado"]);if(!vehicleId||!eventId||!allowed.has(status))throw new Error("Resolución inválida.");const now=new Date().toISOString();const {error}=await supabase.from("fleet_deterioration_events").update({status,review_note:note||null,reviewed_by:user.id,reviewed_at:now,repaired_at:status==="Reparado"?now:null}).eq("id",eventId).eq("vehicle_id",vehicleId);if(error)throw new Error("No fue posible guardar la revisión.");revalidatePath(`/flota/${vehicleId}`);redirect(`/flota/${vehicleId}?vista=operacion&notice=damage-reviewed`);}
