"use client";
import {useEffect,useRef,useState} from "react";
import {addRenditionExpense,type RenditionExpenseResult} from "./actions";
type ReadData={expense_date?:string;document_type?:string;provider_name?:string;provider_rut?:string;document_number?:string;description?:string;presented_amount?:number|null};
const MAX_IMAGE_SIDE=1200;
const TARGET_BYTES=100*1024;
const MIN_QUALITY=0.42;
async function optimizeImage(file:File):Promise<File>{
 if(!file.type.startsWith("image/"))return file;
 const bitmap=await createImageBitmap(file);const scale=Math.min(1,MAX_IMAGE_SIDE/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");
 canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext("2d");
 if(!ctx){bitmap.close();throw new Error("No se pudo preparar la fotografía.");}ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
 const toBlob=(q:number)=>new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("No se pudo optimizar la fotografía.")),"image/webp",q));
 let q=.82,blob=await toBlob(q);while(blob.size>TARGET_BYTES&&q>MIN_QUALITY){q=Math.max(MIN_QUALITY,q-.1);blob=await toBlob(q);}
 const base=file.name.replace(/\.[^.]+$/,"")||"comprobante";return new File([blob],base+".webp",{type:"image/webp",lastModified:Date.now()});
}
export default function ExpenseForm({renditionId}:{renditionId:string}){
 const formRef=useRef<HTMLFormElement>(null);const previewUrl=useRef<string|null>(null);const [optimizedFile,setOptimizedFile]=useState<File|null>(null);const [optimizing,setOptimizing]=useState(false);const [reading,setReading]=useState(false);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");const [saveResult,setSaveResult]=useState<RenditionExpenseResult|null>(null);const [preview,setPreview]=useState<string|null>(null);const [data,setData]=useState<ReadData>({document_type:"Boleta"});
 useEffect(()=>()=>{if(previewUrl.current)URL.revokeObjectURL(previewUrl.current)},[]);
 async function readReceipt(file:File){setMessage("");if(file.type==="application/pdf"){setMessage("El PDF se guardará como respaldo. Para lectura automática usa una foto JPG, PNG o WEBP.");return;}setReading(true);try{const fd=new FormData();fd.set("file",file);const res=await fetch("/api/rendiciones/leer-comprobante",{method:"POST",body:fd});const json=await res.json();if(!res.ok)throw new Error(json.error||"No se pudo leer el comprobante.");setData(json.data||{});setMessage("Lectura terminada. Revisa y corrige los datos antes de guardar.");}catch(e){setMessage(e instanceof Error?e.message:"No se pudo leer. Completa los datos manualmente.");}finally{setReading(false);}}
 async function selected(file?:File){if(!file)return;setOptimizing(true);try{const prepared=await optimizeImage(file);setOptimizedFile(prepared);if(previewUrl.current)URL.revokeObjectURL(previewUrl.current);if(prepared.type.startsWith("image/")){previewUrl.current=URL.createObjectURL(prepared);setPreview(previewUrl.current)}else setPreview(null);await readReceipt(prepared);}catch(e){setMessage(e instanceof Error?e.message:"No se pudo preparar el comprobante.");}finally{setOptimizing(false);}}
 async function submit(fd:FormData){if(saving)return;setSaving(true);setSaveResult(null);try{if(optimizedFile)fd.set("document_file",optimizedFile,optimizedFile.name);else fd.delete("document_file");const result=await addRenditionExpense({ok:false,message:""},fd);setSaveResult(result);if(result.ok){formRef.current?.reset();setData({document_type:"Boleta"});setOptimizedFile(null);if(previewUrl.current)URL.revokeObjectURL(previewUrl.current);previewUrl.current=null;setPreview(null);setMessage("Gasto guardado. Puedes agregar otro gasto o continuar después.");}}catch(e){setSaveResult({ok:false,message:e instanceof Error?e.message:"No se pudo guardar el gasto. Intenta nuevamente."});}finally{setSaving(false);}}
 return <form ref={formRef} action={submit} encType="multipart/form-data" className="renditionExpenseForm"><input type="hidden" name="rendition_id" value={renditionId}/>
  <div className="renditionReceiptDrop"><div className="renditionStep"><span>1</span><div><b>Comprobante opcional</b><p>Sube una foto/PDF para completar datos automáticamente, o ingresa el gasto manualmente.</p></div></div><input name="document_file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" capture="environment" onChange={e=>void selected(e.target.files?.[0])}/>{preview&&<img src={preview} alt="Vista previa del comprobante" className="renditionReceiptPreview"/>}<div className={(reading||optimizing)?"renditionReading":"renditionReaderMessage"}>{optimizing?<><span className="renditionPulse"/>Optimizando fotografía…</>:reading?<><span className="renditionPulse"/>Analizando comprobante…</>:message}</div></div>
  <div className="renditionStep"><span>2</span><div><b>Completa el gasto</b><p>Los datos pueden venir del comprobante o ingresarse manualmente. Al agregarlo queda guardado.</p></div></div>
  <div className="renditionExpenseFields"><label>Fecha<input name="expense_date" type="date" required value={data.expense_date||""} onChange={e=>setData({...data,expense_date:e.target.value})}/></label><label>Tipo de documento<select name="document_type" value={data.document_type||"Boleta"} onChange={e=>setData({...data,document_type:e.target.value})}>{["Factura","Boleta","Transferencia","Otro","Sin documento"].map(x=><option key={x}>{x}</option>)}</select></label><label>N.º documento<input name="document_number" value={data.document_number||""} onChange={e=>setData({...data,document_number:e.target.value})}/></label><label>Proveedor<input name="provider_name" value={data.provider_name||""} onChange={e=>setData({...data,provider_name:e.target.value})}/></label><label>RUT proveedor<input name="provider_rut" value={data.provider_rut||""} onChange={e=>setData({...data,provider_rut:e.target.value})}/></label><label>Categoría<select name="category" required defaultValue=""><option value="" disabled>Seleccionar categoría</option>{["Estacionamiento","Alojamiento","Colación/Alimentación","Compras/Materiales","Insumos varios","Movilización/Uber","Peajes","Otros"].map(x=><option key={x}>{x}</option>)}</select></label><label className="renditionFieldWide">Descripción<input name="description" required value={data.description||""} onChange={e=>setData({...data,description:e.target.value})}/></label><label>Total pagado<input name="presented_amount" type="number" min="1" step="1" required value={data.presented_amount??""} onChange={e=>setData({...data,presented_amount:Number(e.target.value)||null})}/></label></div>
  {saveResult?.message&&<div role="status" className={saveResult.ok?"renditionSaveOk":"renditionSaveError"}>{saveResult.message}</div>}<button className="renditionBtn renditionBtnPrimary" disabled={saving||reading||optimizing}>{saving?"Guardando…":"Agregar gasto"}</button>
 </form>;
}