"use client";
import {useRef,useState} from "react";
import {addRenditionExpense,type RenditionExpenseResult} from "./actions";
type ReadData={expense_date?:string;document_type?:string;provider_name?:string;provider_rut?:string;document_number?:string;description?:string;presented_amount?:number|null};
export default function ExpenseForm({renditionId}:{renditionId:string}){
 const formRef=useRef<HTMLFormElement>(null);const [reading,setReading]=useState(false);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");const [saveResult,setSaveResult]=useState<RenditionExpenseResult|null>(null);const [preview,setPreview]=useState<string|null>(null);const [data,setData]=useState<ReadData>({document_type:"Boleta"});
 async function readReceipt(file:File){setMessage("");if(file.type==="application/pdf"){setMessage("El PDF se guardará como respaldo. Para lectura automática usa una foto JPG, PNG o WEBP.");return;}setReading(true);try{const fd=new FormData();fd.set("file",file);const res=await fetch("/api/rendiciones/leer-comprobante",{method:"POST",body:fd});const json=await res.json();if(!res.ok)throw new Error(json.error||"No se pudo leer el comprobante.");setData(json.data||{});setMessage("Lectura terminada. Revisa y corrige los datos antes de guardar.");}catch(e){setMessage(e instanceof Error?e.message:"No se pudo leer. Completa los datos manualmente.");}finally{setReading(false);}}
 function selected(file?:File){if(!file)return;setPreview(file.type.startsWith("image/")?URL.createObjectURL(file):null);void readReceipt(file);}
 async function submit(fd:FormData){if(saving)return;setSaving(true);setSaveResult(null);try{const result=await addRenditionExpense({ok:false,message:""},fd);setSaveResult(result);if(result.ok){formRef.current?.reset();setData({document_type:"Boleta"});setPreview(null);setMessage("");}}catch(e){setSaveResult({ok:false,message:e instanceof Error?e.message:"No se pudo guardar el gasto. Intenta nuevamente."});}finally{setSaving(false);}}
 return <form ref={formRef} action={submit} encType="multipart/form-data" className="renditionExpenseForm"><input type="hidden" name="rendition_id" value={renditionId}/>
  <div className="renditionReceiptDrop"><div className="renditionStep"><span>1</span><div><b>Foto o comprobante</b><p>Toma la foto primero. El sistema intentará completar los datos.</p></div></div><input name="document_file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" capture="environment" required onChange={e=>selected(e.target.files?.[0])}/>{preview&&<img src={preview} alt="Vista previa del comprobante" className="renditionReceiptPreview"/>}<div className={reading?"renditionReading":"renditionReaderMessage"}>{reading?<><span className="renditionPulse"/>Analizando comprobante…</>:message}</div></div>
  <div className="renditionStep"><span>2</span><div><b>Revisa los datos detectados</b><p>Corrige cualquier dato antes de guardar.</p></div></div>
  <div className="renditionExpenseFields"><label>Fecha<input name="expense_date" type="date" required value={data.expense_date||""} onChange={e=>setData({...data,expense_date:e.target.value})}/></label><label>Tipo de documento<select name="document_type" value={data.document_type||"Boleta"} onChange={e=>setData({...data,document_type:e.target.value})}>{["Factura","Boleta","Transferencia","Otro","Sin documento"].map(x=><option key={x}>{x}</option>)}</select></label><label>N.º documento<input name="document_number" value={data.document_number||""} onChange={e=>setData({...data,document_number:e.target.value})}/></label><label>Proveedor<input name="provider_name" value={data.provider_name||""} onChange={e=>setData({...data,provider_name:e.target.value})}/></label><label>RUT proveedor<input name="provider_rut" value={data.provider_rut||""} onChange={e=>setData({...data,provider_rut:e.target.value})}/></label><label>Categoría<select name="category" required defaultValue=""><option value="" disabled>Seleccionar categoría</option>{["Estacionamiento","Alojamiento","Colación/Alimentación","Compras/Materiales","Insumos varios","Movilización/Uber","Peajes","Otros"].map(x=><option key={x}>{x}</option>)}</select></label><label className="renditionFieldWide">Descripción<input name="description" required value={data.description||""} onChange={e=>setData({...data,description:e.target.value})}/></label><label>Total pagado<input name="presented_amount" type="number" min="1" step="1" required value={data.presented_amount??""} onChange={e=>setData({...data,presented_amount:Number(e.target.value)||null})}/></label></div>
  {saveResult?.message&&<div role="status" className={saveResult.ok?"renditionSaveOk":"renditionSaveError"}>{saveResult.message}</div>}<button className="renditionBtn renditionBtnPrimary" disabled={saving||reading}>{saving?"Guardando…":"Guardar gasto"}</button>
 </form>;
}