import {redirect} from "next/navigation";
import Link from "next/link";
import {createClient} from "@/lib/supabase/server";
import {createRendition} from "./actions";
import {CAPABILITIES,roleCan,type Capability} from "@/lib/authorization";
const money=(v:number|null|undefined)=>Number(v||0).toLocaleString("es-CL");
function badge(s:string|null|undefined){const v=(s||"").toUpperCase();if(["APROBADA","PAGADA"].includes(v))return "renditionBadge renditionBadgeOk";if(v==="RECHAZADA")return "renditionBadge renditionBadgeError";if(["ENVIADA","OBSERVADA"].includes(v))return "renditionBadge renditionBadgeWarning";return "renditionBadge renditionBadgeNeutral";}
function date(v:string|null|undefined){if(!v)return "—";const a=v.split("-");return a.length===3?a[2]+"/"+a[1]+"/"+a[0]:v;}
export default async function Page(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const {data:p}=await supabase.from("user_profiles").select("id,full_name,email,role,active").eq("id",user.id).single();if(!p?.active)redirect("/");
 const {data:access}=await supabase.rpc("has_additional_service_access",{p_service_code:"rendiciones"});const admin=p.role==="Admin Total";if(!access&&!admin)redirect("/");
 const {data:perm}=await supabase.from("user_module_permissions").select("module_code,can_view").eq("user_id",user.id).in("module_code",[CAPABILITIES.RENDITION_SUBMIT,CAPABILITIES.RENDITION_REVIEW]);const effective=(cap:Capability)=>{if(admin)return true;const o=(perm??[]).find((x:any)=>x.module_code===cap);return o?Boolean(o.can_view):roleCan(p.role,cap)};const canSubmit=effective(CAPABILITIES.RENDITION_SUBMIT),manager=effective(CAPABILITIES.RENDITION_REVIEW);
 let q=supabase.from("renditions").select("id,folio,creator_user_id,person_name,person_rut,period_start,period_end,status,service_mode,total_presented,observations,review_observation,created_at").order("created_at",{ascending:false});if(manager)q=q.neq("status","Borrador");else q=q.eq("creator_user_id",user.id);
 const {data:rows}=await q;const list=rows??[];const total=list.reduce((n:number,r:any)=>n+Number(r.total_presented||0),0);const pending=list.filter((r:any)=>["Enviada","Observada"].includes(r.status)).length;const approved=list.filter((r:any)=>["Aprobada","Pagada"].includes(r.status)).length;
 return <main className="renditionsPage"><header className="renditionsHero"><div><div className="renditionsEyebrow">ALEMSI · RENDICIONES</div><h1>{manager?"Rendiciones de Gastos":"Mis Rendiciones"}</h1><p>{manager?"Bandeja de gestión y revisión.":"Crea una rendición y consulta el estado de las que ya enviaste."}</p></div><div className="renditionsHeroActions"><Link className="renditionBtn renditionBtnGhost" href="/">Volver</Link>{canSubmit&&<a className="renditionBtn renditionBtnPrimary" href="#nueva-rendicion">+ Nueva rendición</a>}</div></header>
 {manager&&<section className="renditionsMetrics"><article className="renditionMetric"><span>Total rendido</span><strong>$ {money(total)}</strong></article><article className="renditionMetric"><span>Pendientes</span><strong>{pending}</strong></article><article className="renditionMetric"><span>Aprobadas</span><strong>{approved}</strong></article></section>}
 {canSubmit&&<details id="nueva-rendicion" className="renditionCreatePanel"><summary>+ Nueva rendición</summary><form action={createRendition} className="renditionFormGrid"><label>Nombre<input name="person_name" defaultValue={p.full_name||""} required/></label><label>RUT<input name="person_rut" required/></label><label>Correo<input name="person_email" type="email" defaultValue={p.email||""}/></label><label>Desde<input name="period_start" type="date" required/></label><label>Hasta<input name="period_end" type="date" required/></label><label>Fondos recibidos<input name="company_funds" type="number" min="0" defaultValue="0"/></label><label className="renditionFieldWide">Observaciones<textarea name="observations"/></label><div className="renditionFieldWide"><button className="renditionBtn renditionBtnPrimary">Crear rendición</button></div></form></details>}
 <section className="renditionsBoard"><div className="renditionsBoardHead"><div><h2>{manager?"Bandeja de rendiciones":"Mis rendiciones"}</h2><p>Selecciona una línea para abrir el expediente.</p></div></div>{list.length===0&&<div className="renditionEmpty">Sin rendiciones registradas.</div>}
 {list.length>0&&<div className="renditionList"><div className={"renditionListHead "+(!manager?"renditionListSimple":"")}><span>Rendición</span><span>Fecha</span>{manager&&<span>Quién rinde</span>}<span>Observación</span>{manager&&<span>Monto</span>}<span>Estado</span><span></span></div>{list.map((r:any)=><Link key={r.id} className={"renditionListRow "+(!manager?"renditionListSimple":"")} href={"/rendiciones/"+r.id}><span className="renditionListFolio"><b>{r.folio}</b></span><span>{date(r.period_start)}</span>{manager&&<span><b>{r.person_name}</b><small>{r.person_rut}</small></span>}<span className={r.review_observation?"renditionListObservation renditionListObservationActive":"renditionListObservation"}>{r.review_observation||r.observations||"Sin observaciones"}</span>{manager&&<span className="renditionListAmount">$ {money(r.total_presented)}</span>}<span><span className={badge(r.status)}>{r.status}</span></span><span className="renditionListOpen">Ver ›</span></Link>)}</div>}</section></main>;
}