import {redirect} from "next/navigation";
import Link from "next/link";
import {createClient} from "@/lib/supabase/server";
import ExpenseForm from "./ExpenseForm";
import {createRendition,editRenditionExpense,markRenditionPaid,reviewExpense,submitRendition} from "./actions";

const money=(v:number|null|undefined)=>Number(v||0).toLocaleString("es-CL");
const card={border:"1px solid #c8dce8",borderRadius:14,padding:16,margin:"12px 0",background:"#fff"} as const;
const cats=["Estacionamiento","Alojamiento","Colación/Alimentación","Compras/Materiales","Insumos varios","Movilización/Uber","Peajes","Otros"];

export default async function RendicionesPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const {data:profile}=await supabase.from("user_profiles").select("id,full_name,email,role,active").eq("id",user.id).single();if(!profile?.active)redirect("/");
 const {data:allowed}=await supabase.rpc("has_additional_service_access",{p_service_code:"rendiciones"});const admin=profile.role==="Admin Total";if(!allowed&&!admin)redirect("/");
 const {data:service}=await supabase.from("additional_services").select("status").eq("service_code","rendiciones").single();
 const {data:rows}=await supabase.from("renditions").select("id,folio,person_name,person_rut,person_email,period_start,period_end,status,service_mode,previous_balance,company_funds,total_presented,total_authorized,amount_paid,observations,review_observation,payment_observation,created_at,rendition_expenses(id,expense_date,category,document_type,provider_name,provider_rut,document_number,description,presented_amount,authorized_amount,review_observation,review_status,document_id)").order("created_at",{ascending:false});
 const ids=(rows??[]).flatMap((r:any)=>(r.rendition_expenses??[]).map((g:any)=>g.document_id).filter(Boolean));const docs=new Map<string,{name:string;url:string}>();
 if(ids.length){const {data:d}=await supabase.from("documents").select("id,file_name,storage_path").in("id",ids);for(const x of d??[]){const {data:s}=await supabase.storage.from("rendition-documents").createSignedUrl(x.storage_path,3600);if(s?.signedUrl)docs.set(x.id,{name:x.file_name,url:s.signedUrl});}}
 const finance=profile.role==="Finanzas",management=profile.role==="Gerencia",reviewer=finance||management||admin,canCreate=Boolean(allowed)||admin;
 return <main style={{maxWidth:1180,margin:"0 auto",padding:16,color:"#173650"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><small>ALEMSI · RENDICIONES {(service?.status==="DEMO"||service?.status==="INACTIVO")?"· MODO DEMO":""}</small><h1>Rendiciones</h1><p>Comprobante primero, datos después. La lectura automática siempre queda editable.</p></div><Link href="/">Volver</Link></header>
  {canCreate&&<section style={card}><h2>Nueva rendición</h2><form action={createRendition} style={{display:"grid",gap:9}}><input name="person_name" defaultValue={profile.full_name||""} placeholder="Nombre" required/><input name="person_rut" placeholder="RUT" required/><input name="person_email" type="email" defaultValue={profile.email||""} placeholder="Correo"/><label>Desde <input name="period_start" type="date" required/></label><label>Hasta <input name="period_end" type="date" required/></label><label>Fondos recibidos <input name="company_funds" type="number" min="0" defaultValue="0"/></label><textarea name="observations" placeholder="Observaciones"/><button>Crear rendición</button></form></section>}
  <section><h2>{reviewer?"Bandeja de rendiciones":"Mis rendiciones"}</h2>{(rows??[]).map((r:any)=><article key={r.id} style={card}>
   <div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><div><b>{r.folio}</b>{r.service_mode==="DEMO"&&<strong> · DEMO</strong>}<div>{r.person_name} · RUT {r.person_rut} · {r.period_start} a {r.period_end}</div></div><strong>{r.status}</strong></div>
   <p>Fondos: <b>$ {money(r.company_funds)}</b> · Saldo anterior: <b>$ {money(r.previous_balance)}</b> · Presentado: <b>$ {money(r.total_presented)}</b> · Autorizado: <b>$ {money(r.total_authorized)}</b> · Pagado: <b>$ {money(r.amount_paid)}</b></p>
   <details open={["Borrador","Observada","Enviada"].includes(r.status)}><summary style={{fontWeight:800,cursor:"pointer"}}>Abrir expediente · {r.rendition_expenses?.length||0} gasto(s)</summary>
    <div style={{overflowX:"auto",marginTop:10}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:920}}><thead><tr>{["Fecha","Documento","Proveedor","Descripción","Importe","Comprobante","Estado","Observación / acción"].map(x=><th key={x} style={{textAlign:"left",padding:8,borderBottom:"2px solid #c8dce8"}}>{x}</th>)}</tr></thead><tbody>
    {(r.rendition_expenses??[]).map((g:any)=>{const doc=g.document_id?docs.get(g.document_id):null;return <tr key={g.id}>
     <td style={{padding:8,verticalAlign:"top"}}>{g.expense_date}</td><td style={{padding:8,verticalAlign:"top"}}>{g.document_type} {g.document_number||""}</td><td style={{padding:8,verticalAlign:"top"}}>{g.provider_name||"—"}<br/><small>{g.provider_rut||""}</small></td><td style={{padding:8,verticalAlign:"top"}}>{g.description}<br/><small>{g.category}</small></td><td style={{padding:8,verticalAlign:"top",fontWeight:800}}>$ {money(g.presented_amount)}</td><td style={{padding:8,verticalAlign:"top"}}>{doc?<a href={doc.url} target="_blank" rel="noreferrer"><b>Ver comprobante</b></a>:"Sin respaldo"}</td><td style={{padding:8,verticalAlign:"top"}}><b>{g.review_status||"Pendiente"}</b></td>
     <td style={{padding:8,verticalAlign:"top"}}>{g.review_observation&&<p>{g.review_observation}</p>}
      {canCreate&&["Borrador","Observada"].includes(r.status)&&<details><summary>Editar línea</summary><form action={editRenditionExpense} style={{display:"grid",gap:5,minWidth:230}}><input type="hidden" name="rendition_id" value={r.id}/><input type="hidden" name="expense_id" value={g.id}/><input name="expense_date" type="date" defaultValue={g.expense_date} required/><select name="document_type" defaultValue={g.document_type}>{["Factura","Boleta","Transferencia","Otro","Sin documento"].map(x=><option key={x}>{x}</option>)}</select><input name="document_number" defaultValue={g.document_number||""} placeholder="N.º documento"/><input name="provider_name" defaultValue={g.provider_name||""} placeholder="Proveedor"/><input name="provider_rut" defaultValue={g.provider_rut||""} placeholder="RUT"/><select name="category" defaultValue={g.category}>{cats.map(x=><option key={x}>{x}</option>)}</select><input name="description" defaultValue={g.description} required/><input name="presented_amount" type="number" min="1" defaultValue={Number(g.presented_amount)} required/><button>Guardar cambios</button></form></details>}
      {reviewer&&r.status==="Enviada"&&<form action={reviewExpense} style={{display:"grid",gap:5,minWidth:230}}><input type="hidden" name="rendition_id" value={r.id}/><input type="hidden" name="expense_id" value={g.id}/><textarea name="observation" placeholder="Observación de esta línea"/>{!management&&<input name="authorized_amount" type="number" min="0" max={Number(g.presented_amount)} defaultValue={Number(g.presented_amount)}/>}<div style={{display:"flex",gap:5,flexWrap:"wrap"}}><button name="decision" value="OBSERVE">Observar</button>{!management&&<><button name="decision" value="APPROVE">Aprobar</button><button name="decision" value="REJECT">Rechazar</button></>}</div></form>}
     </td></tr>})}</tbody></table>{(r.rendition_expenses??[]).length===0&&<p>Sin gastos registrados.</p>}</div>
   </details>
   {canCreate&&["Borrador","Observada"].includes(r.status)&&<div style={{marginTop:14,borderTop:"1px solid #c8dce8",paddingTop:12}}><h3>Agregar gasto</h3><ExpenseForm renditionId={r.id}/><form action={submitRendition} style={{marginTop:10}}><input type="hidden" name="rendition_id" value={r.id}/><button disabled={(r.rendition_expenses?.length||0)===0}>{(r.rendition_expenses?.length||0)===0?"Agrega un gasto para enviar":"Enviar a Finanzas"}</button></form></div>}
   {(finance||admin)&&r.status==="Aprobada"&&Number(r.total_authorized)>0&&<form action={markRenditionPaid} style={{display:"grid",gap:8,marginTop:14,borderTop:"1px solid #c8dce8",paddingTop:12}}><h3>Registrar pago</h3><input type="hidden" name="rendition_id" value={r.id}/><input name="amount_paid" type="number" min="1" max={Number(r.total_authorized)} defaultValue={Number(r.total_authorized)} required/><input name="payment_observation" placeholder="Referencia u observación de pago"/><button>Marcar como pagada</button></form>}
  </article>)}{(rows??[]).length===0&&<p>Sin rendiciones registradas.</p>}</section>
 </main>
}
