import {redirect} from "next/navigation";
import Link from "next/link";
import {createClient} from "@/lib/supabase/server";
import ExpenseForm from "./ExpenseForm";
import {createRendition,editRenditionExpense,markRenditionPaid,reviewExpense,submitRendition} from "./actions";

const money=(v:number|null|undefined)=>Number(v||0).toLocaleString("es-CL");
const cats=["Estacionamiento","Alojamiento","Colación/Alimentación","Compras/Materiales","Insumos varios","Movilización/Uber","Peajes","Otros"];
function statusClass(status:string|null|undefined){const value=(status||"").trim().toLocaleUpperCase("es-CL");if(["APROBADA","APROBADO","PAGADA","PAGADO"].includes(value))return "renditionBadge renditionBadgeOk";if(["RECHAZADA","RECHAZADO"].includes(value))return "renditionBadge renditionBadgeError";if(["ENVIADA","ENVIADO","PENDIENTE","OBSERVADA","OBSERVADO"].includes(value))return "renditionBadge renditionBadgeWarning";return "renditionBadge renditionBadgeNeutral";}

export default async function RendicionesPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const {data:profile}=await supabase.from("user_profiles").select("id,full_name,email,role,active").eq("id",user.id).single();if(!profile?.active)redirect("/");
 const {data:allowed}=await supabase.rpc("has_additional_service_access",{p_service_code:"rendiciones"});const admin=profile.role==="Admin Total";if(!allowed&&!admin)redirect("/");
 const {data:service}=await supabase.from("additional_services").select("status").eq("service_code","rendiciones").single();
 const {data:rows}=await supabase.from("renditions").select("id,folio,person_name,person_rut,person_email,period_start,period_end,status,service_mode,previous_balance,company_funds,total_presented,total_authorized,amount_paid,observations,review_observation,payment_observation,created_at,rendition_expenses(id,expense_date,category,document_type,provider_name,provider_rut,document_number,description,presented_amount,authorized_amount,review_observation,review_status,document_id)").order("created_at",{ascending:false});
 const ids=(rows??[]).flatMap((r:any)=>(r.rendition_expenses??[]).map((g:any)=>g.document_id).filter(Boolean));const docs=new Map<string,{name:string;url:string}>();
 if(ids.length){const {data:d}=await supabase.from("documents").select("id,file_name,storage_path").in("id",ids);for(const x of d??[]){const {data:s}=await supabase.storage.from("rendition-documents").createSignedUrl(x.storage_path,3600);if(s?.signedUrl)docs.set(x.id,{name:x.file_name,url:s.signedUrl});}}
 const finance=profile.role==="Finanzas",management=profile.role==="Gerencia",reviewer=finance||management||admin,canCreate=Boolean(allowed)||admin;
 const renditions=rows??[];const totalPresented=renditions.reduce((sum:number,r:any)=>sum+Number(r.total_presented||0),0);const pending=renditions.filter((r:any)=>["Enviada","Observada"].includes(r.status)).length;const approved=renditions.filter((r:any)=>["Aprobada","Pagada"].includes(r.status)).length;
 return <main className="renditionsPage">
  <header className="renditionsHero"><div><div className="renditionsEyebrow">ALEMSI · RENDICIONES {(service?.status==="DEMO"||service?.status==="INACTIVO")?"· MODO DEMO":""}</div><h1>Rendiciones de Gastos</h1><p>Registra, respalda y revisa gastos con trazabilidad completa.</p></div><div className="renditionsHeroActions"><Link className="renditionBtn renditionBtnGhost" href="/">Volver</Link>{canCreate&&<a className="renditionBtn renditionBtnPrimary" href="#nueva-rendicion">+ Nueva rendición</a>}</div></header>
  <section className="renditionsMetrics"><article className="renditionMetric"><span>Total rendido</span><strong>$ {money(totalPresented)}</strong><small>{renditions.length} rendición(es)</small></article><article className="renditionMetric"><span>Pendientes</span><strong>{pending}</strong><small>Por revisar o corregir</small></article><article className="renditionMetric"><span>Aprobadas</span><strong>{approved}</strong><small>Incluye rendiciones pagadas</small></article></section>
  {canCreate&&<details id="nueva-rendicion" className="renditionCreatePanel"><summary>+ Crear nueva rendición</summary><form action={createRendition} className="renditionFormGrid"><label>Nombre<input name="person_name" defaultValue={profile.full_name||""} required/></label><label>RUT<input name="person_rut" required/></label><label>Correo<input name="person_email" type="email" defaultValue={profile.email||""}/></label><label>Desde<input name="period_start" type="date" required/></label><label>Hasta<input name="period_end" type="date" required/></label><label>Fondos recibidos<input name="company_funds" type="number" min="0" defaultValue="0"/></label><label className="renditionFieldWide">Observaciones<textarea name="observations"/></label><div className="renditionFieldWide"><button className="renditionBtn renditionBtnPrimary">Crear rendición</button></div></form></details>}
  <section className="renditionsBoard"><div className="renditionsBoardHead"><div><h2>{reviewer?"Bandeja de rendiciones":"Mis rendiciones"}</h2><p>{reviewer?"Revisa montos, respaldos y estados sin perder el contexto.":"Consulta tus rendiciones y continúa las que estén pendientes."}</p></div></div>
   {renditions.length===0&&<div className="renditionEmpty">Sin rendiciones registradas.</div>}
   {renditions.map((r:any)=><article key={r.id} className="renditionCard">
    <div className="renditionCardTop"><div><div className="renditionFolio">{r.folio}{r.service_mode==="DEMO"&&<span className="renditionDemo">DEMO</span>}</div><div className="renditionPerson">{r.person_name}</div><div className="renditionMeta">RUT {r.person_rut} · {r.period_start} a {r.period_end}</div></div><span className={statusClass(r.status)}>{r.status}</span></div>
    <div className="renditionMoneyGrid"><div><span>Fondos</span><strong>$ {money(r.company_funds)}</strong></div><div><span>Saldo anterior</span><strong>$ {money(r.previous_balance)}</strong></div><div><span>Presentado</span><strong>$ {money(r.total_presented)}</strong></div><div><span>Autorizado</span><strong>$ {money(r.total_authorized)}</strong></div><div><span>Pagado</span><strong>$ {money(r.amount_paid)}</strong></div></div>
    <details className="renditionCase" open={["Borrador","Observada","Enviada"].includes(r.status)}><summary><span>Abrir expediente</span><small>{r.rendition_expenses?.length||0} gasto(s)</small></summary><div className="renditionExpenseList">
     {(r.rendition_expenses??[]).map((g:any)=>{const doc=g.document_id?docs.get(g.document_id):null;return <article key={g.id} className="renditionExpense">
      <div className="renditionExpenseMain"><div><span className="renditionLabel">Fecha</span><strong>{g.expense_date}</strong></div><div><span className="renditionLabel">Documento</span><strong>{g.document_type} {g.document_number||""}</strong><small>{g.provider_name||"—"}{g.provider_rut?" · "+g.provider_rut:""}</small></div><div><span className="renditionLabel">Descripción</span><strong>{g.description}</strong><small>{g.category}</small></div><div className="renditionExpenseAmount"><span>Importe</span><strong>$ {money(g.presented_amount)}</strong></div><div className="renditionExpenseStatus"><span className={statusClass(g.review_status||"Pendiente")}>{g.review_status||"Pendiente"}</span></div></div>
      <div className="renditionExpenseActions">{doc?<a className="renditionBtn renditionBtnOutline" href={doc.url} target="_blank" rel="noreferrer">Ver comprobante</a>:<span className="renditionNoDoc">Sin respaldo</span>}{g.review_observation&&<div className="renditionObservation"><b>Observación:</b> {g.review_observation}</div>}
       {canCreate&&["Borrador","Observada"].includes(r.status)&&<details className="renditionInlineDetails"><summary>Editar gasto</summary><form action={editRenditionExpense} className="renditionCompactForm"><input type="hidden" name="rendition_id" value={r.id}/><input type="hidden" name="expense_id" value={g.id}/><label>Fecha<input name="expense_date" type="date" defaultValue={g.expense_date} required/></label><label>Tipo<select name="document_type" defaultValue={g.document_type}>{["Factura","Boleta","Transferencia","Otro","Sin documento"].map(x=><option key={x}>{x}</option>)}</select></label><label>N.º documento<input name="document_number" defaultValue={g.document_number||""}/></label><label>Proveedor<input name="provider_name" defaultValue={g.provider_name||""}/></label><label>RUT<input name="provider_rut" defaultValue={g.provider_rut||""}/></label><label>Categoría<select name="category" defaultValue={g.category}>{cats.map(x=><option key={x}>{x}</option>)}</select></label><label className="renditionFieldWide">Descripción<input name="description" defaultValue={g.description} required/></label><label>Importe<input name="presented_amount" type="number" min="1" defaultValue={Number(g.presented_amount)} required/></label><div className="renditionFieldWide"><button className="renditionBtn renditionBtnPrimary">Guardar cambios</button></div></form></details>}
       {reviewer&&r.status==="Enviada"&&<form action={reviewExpense} className="renditionReviewForm"><input type="hidden" name="rendition_id" value={r.id}/><input type="hidden" name="expense_id" value={g.id}/><textarea name="observation" placeholder="Observación de esta línea"/>{!management&&<input name="authorized_amount" aria-label="Monto autorizado" type="number" min="0" max={Number(g.presented_amount)} defaultValue={Number(g.presented_amount)}/>}<div className="renditionDecisionButtons"><button className="renditionBtn renditionBtnWarning" name="decision" value="OBSERVE">Observar</button>{!management&&<><button className="renditionBtn renditionBtnSuccess" name="decision" value="APPROVE">Aprobar</button><button className="renditionBtn renditionBtnDanger" name="decision" value="REJECT">Rechazar</button></>}</div></form>}
      </div>
     </article>})}
     {(r.rendition_expenses??[]).length===0&&<div className="renditionEmpty">Sin gastos registrados.</div>}
    </div></details>
    {canCreate&&["Borrador","Observada"].includes(r.status)&&<details className="renditionAddExpense"><summary>+ Agregar gasto</summary><div className="renditionAddExpenseBody"><ExpenseForm renditionId={r.id}/><form action={submitRendition} className="renditionSubmit"><input type="hidden" name="rendition_id" value={r.id}/><button className="renditionBtn renditionBtnPrimary" disabled={(r.rendition_expenses?.length||0)===0}>{(r.rendition_expenses?.length||0)===0?"Agrega un gasto para enviar":"Enviar a Finanzas"}</button></form></div></details>}
    {(finance||admin)&&r.status==="Aprobada"&&Number(r.total_authorized)>0&&<form action={markRenditionPaid} className="renditionPayment"><h3>Registrar pago</h3><input type="hidden" name="rendition_id" value={r.id}/><label>Monto<input name="amount_paid" type="number" min="1" max={Number(r.total_authorized)} defaultValue={Number(r.total_authorized)} required/></label><label>Referencia u observación<input name="payment_observation"/></label><button className="renditionBtn renditionBtnSuccess">Marcar como pagada</button></form>}
   </article>)}
  </section>
 </main>;
}