"use server";
import {revalidatePath} from "next/cache";
import {createClient} from "@/lib/supabase/server";

async function ctx(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sesión no válida");const {data:profile}=await supabase.from("user_profiles").select("role,active,full_name,email").eq("id",user.id).single();if(!profile?.active||!["Admin Total","Gerencia"].includes(profile.role))throw new Error("No autorizado");return{supabase,user,profile};}
async function log(s:any,u:any,p:any,action:string,table:string,id:string,data:any){await s.from("activity_log").insert({actor_id:u.id,actor_name:p.full_name||p.email,module:"Clientes e instalaciones",action,entity_table:table,entity_id:id,new_data:data});}
const norm=(v:unknown)=>String(v??"").trim().toLocaleLowerCase("es-CL").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ");
const normRut=(v:unknown)=>String(v??"").replace(/[^0-9kK]/g,"").toUpperCase();

export async function createClientContract(formData:FormData){const {supabase,user,profile}=await ctx();const legal_name=String(formData.get("legal_name")||"").trim(),rut=String(formData.get("rut")||"").trim()||null,name=String(formData.get("contract_name")||"").trim(),business_center=String(formData.get("business_center")||"").trim()||null,net_budget=Math.max(0,Number(formData.get("net_budget")||0));if(!legal_name||!name)throw new Error("Cliente y contrato son obligatorios");const {data:all}=await supabase.from("clients").select("id,legal_name,rut");if(rut&&((all||[]).some((x:any)=>normRut(x.rut)===normRut(rut))))throw new Error("Ya existe un cliente con este RUT");if(!rut&&((all||[]).some((x:any)=>!x.rut&&norm(x.legal_name)===norm(legal_name))))throw new Error("Ya existe un cliente sin RUT con este mismo nombre");const {data:client,error}=await supabase.from("clients").insert({legal_name,rut,business_center,active:true}).select("id,legal_name,rut,business_center").single();if(error)throw error;const {data:contract,error:ce}=await supabase.from("contracts").insert({client_id:client.id,name,net_budget,active:true}).select("id,name,net_budget").single();if(ce){await supabase.from("clients").update({active:false}).eq("id",client.id);throw ce;}await log(supabase,user,profile,"Crear cliente y contrato","clients",client.id,{client,contract});revalidatePath("/");}

export async function updateContractBudget(formData:FormData){const {supabase,user,profile}=await ctx();const contract_id=String(formData.get("contract_id")||"").trim();const raw=String(formData.get("net_budget")??"").trim();if(!contract_id)throw new Error("Contrato no válido");if(raw==="")throw new Error("Ingresa el flujo económico mensual autorizado");const net_budget=Number(raw);if(!Number.isFinite(net_budget)||net_budget<0)throw new Error("El monto autorizado debe ser un número igual o mayor a 0");const {data:old,error:oldError}=await supabase.from("contracts").select("id,name,net_budget").eq("id",contract_id).single();if(oldError||!old)throw new Error("Contrato no encontrado");const {data,error}=await supabase.from("contracts").update({net_budget,updated_at:new Date().toISOString()}).eq("id",contract_id).select("id,name,net_budget").single();if(error)throw error;await log(supabase,user,profile,"Actualizar flujo económico mensual del contrato","contracts",contract_id,{old_net_budget:Number(old.net_budget||0),new_net_budget:Number(data.net_budget||0),contract_name:data.name});revalidatePath("/");}

export async function createContractInstallation(formData:FormData){const {supabase,user,profile}=await ctx();const contract_id=String(formData.get("contract_id")||""),name=String(formData.get("name")||"").trim();if(!contract_id||!name)throw new Error("Contrato e instalación son obligatorios");const address=String(formData.get("address")||"").trim()||null;const {data:existing,error:ee}=await supabase.from("installations").select("id,name,address").eq("contract_id",contract_id);if(ee)throw ee;const duplicate=(existing||[]).find((x:any)=>norm(x.name)===norm(name)||(address&&norm(x.address)===norm(address)));if(duplicate)throw new Error(`La instalación ya existe: ${duplicate.name}`);const row={contract_id,name,region:String(formData.get("region")||"").trim()||null,city:String(formData.get("city")||"").trim()||null,commune:String(formData.get("commune")||"").trim()||null,address,collaborator_count:Math.max(0,Number(formData.get("collaborator_count")||0)),active:true};const {data,error}=await supabase.from("installations").insert(row).select("id,name,contract_id,region,city,commune,address,collaborator_count").single();if(error)throw error;await log(supabase,user,profile,"Crear instalación","installations",data.id,data);revalidatePath("/");}
