"use client";
import {useEffect,useMemo,useState} from "react";
import master from "@/data/master.json";
import type {AppState,Contract,Installation,MaterialRequest,RequestLine} from "@/types";
import {clearState,loadState,saveState} from "@/lib/storage";

type Client={name:string;budget4m:number;totalUnits4m:number;authorizedProducts:number};
type Product=Record<string,unknown>&{id?:string;name?:string;product?:string;price?:number|null;netPrice?:number|null};
const clients=(master.clients as Client[]).map((c,i)=>({...c,id:`c${i+1}`}));
const rawProducts=master.products as any[];
const products=rawProducts.map((p,i)=>({id:String(p.id||`p${i+1}`),name:String(p.name||p.product||p.descripcion||`Producto ${i+1}`),price:Number(p.price??p.netPrice??p.precio??0)||null,...p}));
const initialContracts:Contract[]=clients.map((c,i)=>({id:`ct${i+1}`,clientId:c.id,name:`Contrato ${c.name}`,periodLabel:"Base inicial · 4 meses",budget4m:c.budget4m,startDate:"",endDate:"",active:true}));
const fallback:AppState={contracts:initialContracts,installations:{},requests:[],budgetOverrides:{}};
const clp=(n:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(n||0);

export default function Page(){
 const [tab,setTab]=useState("inicio"); const [state,setState]=useState<AppState>(fallback); const [ready,setReady]=useState(false);
 const [selectedContract,setSelectedContract]=useState(initialContracts[0]?.id||""); const [modal,setModal]=useState<string|null>(null);
 useEffect(()=>{setState(loadState(fallback));setReady(true)},[]); useEffect(()=>{if(ready)saveState(state)},[state,ready]);
 const contract=state.contracts.find(c=>c.id===selectedContract)||state.contracts[0]; const client=clients.find(c=>c.id===contract?.clientId);
 const inst=contract?state.installations[contract.id]||[]:[]; const reqs=contract?state.requests.filter(r=>r.contractId===contract.id):[];
 const spent=reqs.filter(r=>r.status!=="Borrador").reduce((s,r)=>s+r.total,0); const budget=contract?(state.budgetOverrides[contract.id]??contract.budget4m):0; const available=Math.max(0,budget-spent); const pct=budget?Math.min(100,(spent/budget)*100):0;
 const saveBudget=(v:number)=>setState(s=>({...s,budgetOverrides:{...s.budgetOverrides,[contract.id]:v}}));
 const addInstallation=(x:Omit<Installation,"id"|"active">)=>{const ni={...x,id:crypto.randomUUID(),active:true};setState(s=>({...s,installations:{...s.installations,[contract.id]:[...(s.installations[contract.id]||[]),ni]}}));setModal(null)};
 const addRequest=(r:MaterialRequest)=>{setState(s=>({...s,requests:[r,...s.requests]}));setModal(null)};
 return <div className="app"><header className="top"><div><div className="brand">Control de Materiales</div><div className="sub">Sistema editable · Demo de producción v0.1</div></div><div className="small">Fuente inicial: {master.sourceSheet}</div></header><div className="shell"><aside className="side">{[["inicio","Inicio"],["contratos","Clientes / Contratos"],["instalaciones","Instalaciones"],["maestro","Maestro"],["solicitudes","Solicitudes"]].map(([k,l])=><button key={k} className={`navbtn ${tab===k?"active":""}`} onClick={()=>setTab(k)}>{l}</button>)}</aside><main className="main">
 {tab==="inicio"&&<Inicio contracts={state.contracts} requests={state.requests} onOpen={(id)=>{setSelectedContract(id);setTab("contratos")}}/>}
 {tab==="contratos"&&contract&&<ContratoView contract={contract} client={client} budget={budget} spent={spent} available={available} pct={pct} installations={inst.length} requests={reqs.length} onSelect={setSelectedContract} selected={selectedContract} onBudget={saveBudget}/>} 
 {tab==="instalaciones"&&contract&&<Instalaciones contract={contract} items={inst} onAdd={()=>setModal("inst")} onToggle={(id)=>setState(s=>({...s,installations:{...s.installations,[contract.id]:inst.map(x=>x.id===id?{...x,active:!x.active}:x)}}))}/>} 
 {tab==="maestro"&&contract&&<Maestro clientName={client?.name||""} budget={budget}/>} 
 {tab==="solicitudes"&&contract&&<Solicitudes contract={contract} installations={inst} requests={reqs} budget={budget} spent={spent} onNew={()=>setModal("req")}/>} 
 <div className="toolbar"><button className="btn danger" onClick={()=>{if(confirm("¿Restablecer los datos editados de esta demo?")){clearState();location.reload()}}}>Restablecer demo</button></div>
 </main></div>
 {modal==="inst"&&<InstallationModal onClose={()=>setModal(null)} onSave={addInstallation}/>} 
 {modal==="req"&&contract&&<RequestModal contract={contract} installations={inst.filter(x=>x.active)} available={available} onClose={()=>setModal(null)} onSave={addRequest}/>} 
 </div>
}

function Inicio({contracts,requests,onOpen}:{contracts:Contract[];requests:MaterialRequest[];onOpen:(id:string)=>void}){const total=contracts.reduce((s,c)=>s+c.budget4m,0);const used=requests.filter(r=>r.status!=="Borrador").reduce((s,r)=>s+r.total,0);return <><h1 className="title">Control global de materiales</h1><p className="muted">Primero cliente y contrato. Cada instalación consume de una bolsa global de 4 meses.</p><div className="grid g4"><K label="Contratos" value={contracts.length}/><K label="Presupuesto base" value={clp(total)}/><K label="Solicitado" value={clp(used)}/><K label="Solicitudes" value={requests.length}/></div><div className="sectionHead"><h2>Clientes / contratos</h2></div><div className="tableWrap"><table><thead><tr><th>Cliente / contrato</th><th>Base 4 meses</th><th>Estado</th><th></th></tr></thead><tbody>{contracts.map(c=><tr key={c.id}><td><b>{clients.find(x=>x.id===c.clientId)?.name}</b><div className="small muted">{c.name}</div></td><td>{clp(c.budget4m)}</td><td><span className="pill ok">Activo</span></td><td className="right"><button className="btn" onClick={()=>onOpen(c.id)}>Abrir</button></td></tr>)}</tbody></table></div></>}
function K({label,value}:{label:string;value:string|number}){return <div className="card kpi"><span className="muted">{label}</span><b>{value}</b></div>}
function ContratoView({contract,client,budget,spent,available,pct,installations,requests,onSelect,selected,onBudget}:{contract:Contract;client?:Client;budget:number;spent:number;available:number;pct:number;installations:number;requests:number;onSelect:(x:string)=>void;selected:string;onBudget:(n:number)=>void}){return <><h1 className="title">Cliente y contrato</h1><div className="toolbar"><select value={selected} onChange={e=>onSelect(e.target.value)}>{initialContracts.map(c=><option key={c.id} value={c.id}>{clients.find(x=>x.id===c.clientId)?.name}</option>)}</select></div><div className="grid g4"><K label="Presupuesto 4 meses" value={clp(budget)}/><K label="Consumido" value={clp(spent)}/><K label="Disponible" value={clp(available)}/><K label="Instalaciones" value={installations}/></div><div className="card" style={{marginTop:14}}><div className="grid g2"><div><b>{client?.name}</b><p className="muted small">{contract.name}</p><span className="pill ok">{contract.periodLabel}</span></div><div><div className="field"><label>Presupuesto global editable para 4 meses</label><input type="number" value={budget} onChange={e=>onBudget(Number(e.target.value)||0)}/></div><p className="small muted">Este monto es global del contrato. No se divide rígidamente por instalación.</p></div></div><div style={{marginTop:16}}><div className="bar"><span style={{width:`${pct}%`}}/></div><p className="small muted">Utilización: {pct.toFixed(1)}% · {requests} solicitudes registradas.</p></div></div></>}
function Instalaciones({contract,items,onAdd,onToggle}:{contract:Contract;items:Installation[];onAdd:()=>void;onToggle:(id:string)=>void}){return <><h1 className="title">Instalaciones</h1><p className="muted">Sucursales u oficinas que consumen del presupuesto global del contrato.</p><div className="toolbar"><button className="btn primary" onClick={onAdd}>+ Agregar instalación</button></div>{!items.length?<div className="notice warning">Aún no se han cargado las instalaciones reales de este contrato.</div>:<div className="tableWrap"><table><thead><tr><th>Instalación</th><th>Ciudad</th><th>Comuna</th><th>Dirección</th><th>Estado</th><th></th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><b>{i.name}</b></td><td>{i.city}</td><td>{i.commune}</td><td>{i.address}</td><td><span className={`pill ${i.active?"ok":""}`}>{i.active?"Activa":"Inactiva"}</span></td><td><button className="btn" onClick={()=>onToggle(i.id)}>{i.active?"Desactivar":"Activar"}</button></td></tr>)}</tbody></table></div>}</>}
function Maestro({clientName,budget}:{clientName:string;budget:number}){return <><h1 className="title">Maestro de materiales</h1><p className="muted">Catálogo inicial proveniente del Excel. En la siguiente iteración se habilitará autorización y edición por contrato.</p><div className="grid g2"><K label="Productos en maestro" value={products.length}/><K label={`Base global · ${clientName}`} value={clp(budget)}/></div><div className="sectionHead"><h2>Productos</h2></div><div className="tableWrap"><table><thead><tr><th>Producto</th><th>Presentación / código</th><th>Precio neto</th></tr></thead><tbody>{products.map((p:any)=><tr key={p.id}><td><b>{p.name}</b></td><td>{p.presentation||p.presentacion||p.code||p.codigo||"—"}</td><td>{p.price?clp(p.price):<span className="pill warn">Pendiente</span>}</td></tr>)}</tbody></table></div></>}
function Solicitudes({contract,installations,requests,budget,spent,onNew}:{contract:Contract;installations:Installation[];requests:MaterialRequest[];budget:number;spent:number;onNew:()=>void}){const avail=Math.max(0,budget-spent);return <><h1 className="title">Solicitudes por instalación</h1><p className="muted">La revisión física y el remanente se registran antes del pedido.</p><div className="grid g4"><K label="Presupuesto 4 meses" value={clp(budget)}/><K label="Consumido" value={clp(spent)}/><K label="Disponible" value={clp(avail)}/><K label="Instalaciones activas" value={installations.filter(x=>x.active).length}/></div><div className="toolbar"><button className="btn primary" onClick={onNew} disabled={!installations.some(x=>x.active)}>+ Nueva solicitud</button>{!installations.some(x=>x.active)&&<span className="small muted">Primero agrega una instalación.</span>}</div><div className="tableWrap"><table><thead><tr><th>Fecha</th><th>Instalación</th><th>Revisión</th><th>Estado</th><th>Total</th><th>Observaciones</th></tr></thead><tbody>{requests.length?requests.map(r=><tr key={r.id}><td>{new Date(r.createdAt).toLocaleDateString("es-CL")}</td><td>{installations.find(i=>i.id===r.installationId)?.name||"—"}</td><td><span className={`pill ${r.reviewed?"ok":"warn"}`}>{r.reviewed?"Revisada":"Sin revisión"}</span></td><td>{r.status}</td><td>{clp(r.total)}</td><td>{r.notes||"—"}</td></tr>):<tr><td colSpan={6} className="muted">Sin solicitudes todavía.</td></tr>}</tbody></table></div></>}
function InstallationModal({onClose,onSave}:{onClose:()=>void;onSave:(x:any)=>void}){const [f,setF]=useState({name:"",city:"",commune:"",address:""});return <div className="modalBg"><div className="modal"><h2>Nueva instalación</h2><div className="grid g2">{Object.entries({name:"Nombre instalación",city:"Ciudad",commune:"Comuna",address:"Dirección"}).map(([k,l])=><div className="field" key={k}><label>{l}</label><input value={(f as any)[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></div>)}</div><div className="toolbar"><button className="btn" onClick={onClose}>Cancelar</button><button className="btn primary" disabled={!f.name.trim()} onClick={()=>onSave(f)}>Guardar instalación</button></div></div></div>}
function RequestModal({contract,installations,available,onClose,onSave}:{contract:Contract;installations:Installation[];available:number;onClose:()=>void;onSave:(r:MaterialRequest)=>void}){const [installationId,setInstallationId]=useState(installations[0]?.id||"");const [reviewed,setReviewed]=useState(false);const [reviewDate,setReviewDate]=useState(new Date().toISOString().slice(0,10));const [notes,setNotes]=useState("");const [lines,setLines]=useState<RequestLine[]>(products.slice(0,12).map((p:any)=>({productId:p.id,productName:p.name,unitPrice:p.price||null,baseQty:0,remainder:0,requestedQty:0,lineTotal:0})));
 const total=lines.reduce((s,l)=>s+l.lineTotal,0); const update=(idx:number,key:"remainder"|"requestedQty",v:number)=>setLines(ls=>ls.map((l,i)=>i===idx?{...l,[key]:v,lineTotal:key==="requestedQty"?(l.unitPrice||0)*v:(l.unitPrice||0)*l.requestedQty}:l)); const can=reviewed&&installationId&&total>0&&total<=available;
 return <div className="modalBg"><div className="modal"><h2>Nueva solicitud</h2><div className="notice"><b>Paso obligatorio:</b> confirmar revisión física de la instalación y registrar remanentes antes de solicitar.</div><div className="grid g2" style={{marginTop:14}}><div className="field"><label>Instalación</label><select value={installationId} onChange={e=>setInstallationId(e.target.value)}>{installations.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></div><div className="field"><label>Fecha revisión</label><input type="date" value={reviewDate} onChange={e=>setReviewDate(e.target.value)}/></div></div><label style={{display:"flex",gap:8,margin:"14px 0",alignItems:"center"}}><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> Confirmo que revisé físicamente los materiales restantes en esta instalación.</label><div className="tableWrap"><table><thead><tr><th>Material</th><th>Precio</th><th>Remanente</th><th>Solicitar</th><th>Total</th></tr></thead><tbody>{lines.map((l,i)=><tr key={l.productId}><td>{l.productName}</td><td>{l.unitPrice?clp(l.unitPrice):"Pendiente"}</td><td><input type="number" min={0} value={l.remainder} onChange={e=>update(i,"remainder",Number(e.target.value)||0)} style={{width:90}}/></td><td><input type="number" min={0} value={l.requestedQty} onChange={e=>update(i,"requestedQty",Number(e.target.value)||0)} style={{width:90}} disabled={!l.unitPrice}/></td><td>{clp(l.lineTotal)}</td></tr>)}</tbody></table></div><div className="grid g2" style={{marginTop:14}}><div className="field"><label>Observaciones</label><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></div><div className="card"><div className="small muted">Disponible contrato</div><b>{clp(available)}</b><div className="small muted" style={{marginTop:10}}>Solicitud actual</div><b>{clp(total)}</b><div className="small muted" style={{marginTop:10}}>Saldo proyectado</div><b>{clp(Math.max(0,available-total))}</b></div></div>{total>available&&<div className="notice warning">La solicitud supera el presupuesto global disponible.</div>}<div className="toolbar"><button className="btn" onClick={onClose}>Cancelar</button><button className="btn primary" disabled={!can} onClick={()=>onSave({id:crypto.randomUUID(),contractId:contract.id,installationId,createdAt:new Date().toISOString(),reviewed,reviewDate,notes,lines:lines.filter(l=>l.requestedQty>0),total,status:"Solicitada"})}>Guardar solicitud</button></div></div></div>}
