"use server";
import {revalidatePath} from "next/cache";
import {createClient} from "@/lib/supabase/server";

async function supplierContext(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sesión no válida");const {data:profile}=await supabase.from("user_profiles").select("role,active,full_name,email").eq("id",user.id).single();if(!profile?.active||!["Admin Total","Gerencia","Admin"].includes(profile.role))throw new Error("No autorizado para administrar proveedores");return{supabase,user,profile};}
const text=(formData:FormData,key:string)=>String(formData.get(key)||"").trim()||null;
const numberOrNull=(formData:FormData,key:string)=>{const raw=String(formData.get(key)||"").trim();return raw===""?null:Number(raw)};
const normalizeRut=(value:string)=>String(value||"").toUpperCase().replace(/[^0-9K]/g,"");
const clean=(v:any)=>String(v??"").trim();

export async function saveSupplier(formData:FormData){const {supabase,user,profile}=await supplierContext();const id=String(formData.get("id")||"").trim();const legal_name=String(formData.get("legal_name")||"").trim();if(!legal_name)throw new Error("La razón social o nombre del proveedor es obligatorio");const payload={legal_name,fantasy_name:text(formData,"fantasy_name"),rut:text(formData,"rut"),address:text(formData,"address"),region:text(formData,"region"),city:text(formData,"city"),commune:text(formData,"commune"),contact_name:text(formData,"contact_name"),phone:text(formData,"phone"),commercial_email:text(formData,"commercial_email"),purchase_order_email:text(formData,"purchase_order_email"),billing_email:text(formData,"billing_email"),dispatch_email:text(formData,"dispatch_email"),website:text(formData,"website"),payment_terms:text(formData,"payment_terms"),lead_time_days:numberOrNull(formData,"lead_time_days"),minimum_order_net:numberOrNull(formData,"minimum_order_net"),conditions:text(formData,"conditions"),notes:text(formData,"notes"),active:String(formData.get("active")||"")==="true",updated_at:new Date().toISOString()};let result:any;let action="Crear proveedor";let old_data:any=null;if(id){const old=await supabase.from("suppliers").select("*").eq("id",id).single();old_data=old.data;result=await supabase.from("suppliers").update(payload).eq("id",id).select("*").single();action="Editar proveedor"}else result=await supabase.from("suppliers").insert(payload).select("*").single();if(result.error||!result.data)throw result.error||new Error("No se pudo guardar el proveedor");await supabase.from("activity_log").insert({actor_id:user.id,actor_name:profile.full_name||profile.email,module:"Proveedores",action,entity_table:"suppliers",entity_id:result.data.id,old_data,new_data:result.data});revalidatePath("/");return{ok:true,supplier:result.data};}

type CsvSupplier={name?:string;email?:string;rut?:string;phone?:string;commune?:string;address?:string;business_activity?:string};
export async function importSuppliersCsvRows(rows:CsvSupplier[]){const {supabase,user,profile}=await supplierContext();if(!Array.isArray(rows)||!rows.length)throw new Error("El CSV no contiene registros");const {data:existing,error}=await supabase.from("suppliers").select("*");if(error)throw error;const byRut=new Map((existing||[]).filter((s:any)=>normalizeRut(s.rut)).map((s:any)=>[normalizeRut(s.rut),s]));const seen=new Set<string>();let created=0,updated=0,unchanged=0,review=0,duplicates=0;const details:any[]=[];
for(const raw of rows){const rut=normalizeRut(clean(raw.rut)),name=clean(raw.name);if(!rut||!name){review++;details.push({name:name||"Sin nombre",rut:clean(raw.rut),status:"REVISAR",reason:"Nombre o RUT faltante"});continue}if(seen.has(rut)){duplicates++;details.push({name,rut:clean(raw.rut),status:"DUPLICADO CSV",reason:"El RUT aparece más de una vez en el archivo"});continue}seen.add(rut);const current:any=byRut.get(rut);if(!current){const payload:any={legal_name:name,rut:clean(raw.rut),active:true,updated_at:new Date().toISOString()};if(clean(raw.email))payload.commercial_email=clean(raw.email);if(clean(raw.phone))payload.phone=clean(raw.phone);if(clean(raw.commune))payload.commune=clean(raw.commune);if(clean(raw.address))payload.address=clean(raw.address);const ins=await supabase.from("suppliers").insert(payload).select("*").single();if(ins.error){review++;details.push({name,rut:clean(raw.rut),status:"REVISAR",reason:ins.error.message});continue}created++;byRut.set(rut,ins.data);await supabase.from("activity_log").insert({actor_id:user.id,actor_name:profile.full_name||profile.email,module:"Proveedores",action:"Importar proveedor CSV",entity_table:"suppliers",entity_id:ins.data.id,new_data:ins.data});details.push({name,rut:clean(raw.rut),status:"NUEVO"});continue}
const incomingAddress=clean(raw.address),oldAddress=clean(current.address);if(incomingAddress&&oldAddress&&incomingAddress.toLocaleLowerCase("es-CL")!==oldAddress.toLocaleLowerCase("es-CL")){review++;details.push({name,rut:clean(raw.rut),status:"REVISAR",reason:"Mismo RUT con dirección diferente: posible sucursal"});continue}
const patch:any={};const candidates:any={legal_name:name,commercial_email:clean(raw.email),phone:clean(raw.phone),commune:clean(raw.commune),address:incomingAddress};for(const [key,value] of Object.entries(candidates)){if(value&&clean(current[key])!==value)patch[key]=value}if(!Object.keys(patch).length){unchanged++;details.push({name,rut:clean(raw.rut),status:"SIN CAMBIOS"});continue}patch.updated_at=new Date().toISOString();const up=await supabase.from("suppliers").update(patch).eq("id",current.id).select("*").single();if(up.error){review++;details.push({name,rut:clean(raw.rut),status:"REVISAR",reason:up.error.message});continue}updated++;await supabase.from("activity_log").insert({actor_id:user.id,actor_name:profile.full_name||profile.email,module:"Proveedores",action:"Actualizar proveedor CSV",entity_table:"suppliers",entity_id:current.id,old_data:current,new_data:up.data});details.push({name,rut:clean(raw.rut),status:"ACTUALIZADO"});}
revalidatePath("/");return{ok:true,created,updated,unchanged,review,duplicates,total:rows.length,details};}
