import Image from "next/image";
import {notFound,redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import PrintButton from "./PrintButton";
const fmt=(v:string)=>new Intl.DateTimeFormat("es-CL",{timeZone:"America/Santiago",day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(v)).replaceAll("/","-");
export default async function DispatchGuidePage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const {data:d}=await supabase.from("dispatches").select("id,internal_number,guide_number,status,observations,recipient_name,recipient_rut,recipient_role,recipient_signature,created_at,delivered_at,installations(name,address,commune,city,region,contracts(name,clients(legal_name,rut))),dispatch_lines(id,required_qty,delivered_qty,materials(name,supplier_code,presentation,unit))").eq("id",id).single();if(!d)notFound();
 const installation:any=d.installations,contract:any=installation?.contracts,client:any=contract?.clients;
 return <main className="guidePage"><div className="printControls"><PrintButton/><span>En el diálogo selecciona “Guardar como PDF”.</span></div><article className="internalGuide"><header><Image src="/alemsi-logo.png" width={190} height={75} alt="ALEMSI"/><div><b>ALEMSI</b><span>GUÍA DE ENTREGA DE MATERIALES</span><small>Guía interna/logística - No constituye DTE tributario del SII</small></div><section><b>N.º interno</b><strong>{d.internal_number||d.guide_number}</strong><span>Fecha: {fmt(d.created_at)}</span></section></header><div className="guideData"><p><small>Cliente</small><b>{client?.legal_name||"—"}</b></p><p><small>RUT cliente</small><b>{client?.rut||"—"}</b></p><p><small>Contrato</small><b>{contract?.name||"—"}</b></p><p><small>Instalación</small><b>{installation?.name||"—"}</b></p><p><small>Dirección</small><b>{installation?.address||"—"}</b></p><p><small>Comuna / Ciudad / Región</small><b>{[installation?.commune,installation?.city,installation?.region].filter(Boolean).join(" / ")||"—"}</b></p></div><table><thead><tr><th>Ítem</th><th>Código</th><th>Producto</th><th>Presentación</th><th>Unidad</th><th>Cantidad</th></tr></thead><tbody>{(d.dispatch_lines||[]).map((l:any,index:number)=><tr key={l.id}><td>{index+1}</td><td>{l.materials?.supplier_code||"—"}</td><td>{l.materials?.name}</td><td>{l.materials?.presentation||"—"}</td><td>{l.materials?.unit||"—"}</td><td>{Number(l.required_qty)}</td></tr>)}</tbody></table><div className="guideObservation"><b>Observaciones</b><p>{d.observations||""}</p></div><footer><h3>RECIBÍ CONFORME</h3><div><p><small>Nombre</small><b>{d.recipient_name||"________________________________"}</b></p><p><small>RUT</small><b>{d.recipient_rut||"________________"}</b></p><p><small>Cargo/Receptor</small><b>{d.recipient_role||"________________"}</b></p><p><small>Fecha</small><b>{d.delivered_at?fmt(d.delivered_at):"____-____-________"}</b></p><p><small>Hora</small><b>{d.delivered_at?new Intl.DateTimeFormat("es-CL",{timeZone:"America/Santiago",hour:"2-digit",minute:"2-digit"}).format(new Date(d.delivered_at)):"____:____"}</b></p><p className="signature"><small>Firma</small>{d.recipient_signature?<img src={d.recipient_signature} alt="Firma receptor"/>:<b>________________________</b>}</p></div></footer></article></main>;
}
