import Image from "next/image";
import {notFound,redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import PrintButton from "./PrintButton";
const fmt=(v:string)=>new Intl.DateTimeFormat("es-CL",{timeZone:"America/Santiago",day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(v)).replaceAll("/","-");
const guideCss=`
.internalGuide{padding:9mm 10mm 8mm;font-size:9pt;line-height:1.2}.internalGuide header{grid-template-columns:145px 1fr 165px;gap:12px;padding-bottom:7px}.internalGuide header img{width:145px;height:auto}.internalGuide header>div{gap:2px}.internalGuide header>div b{font-size:16pt;line-height:1}.internalGuide header>div span{font-size:10pt}.internalGuide header>div small{font-size:7.5pt}.internalGuide header section{padding:6px;font-size:8pt}.internalGuide header section strong{font-size:13pt;margin:2px 0}.guideData{margin:8px 0;grid-template-columns:2fr 1fr 2fr}.guideData p{grid-template-columns:auto 1fr;gap:5px;padding:4px 6px;min-height:25px;align-items:center}.guideData p:nth-child(3){border-right:0}.guideData .guideWide{grid-column:1/-1;border-right:0;border-bottom:0}.guideData small,.internalGuide footer small{font-size:7.5pt;font-weight:700}.guideData b{font-size:8.5pt;overflow-wrap:anywhere}.internalGuide .guideLines{table-layout:fixed;min-width:0;width:100%}.internalGuide .guideLines thead{display:table-header-group}.internalGuide .guideLines th{font-size:7.5pt;padding:3px 4px;line-height:1.1;border:1px solid #aeb8bd}.internalGuide .guideLines td{font-size:8pt;padding:3px 4px;line-height:1.12;border:1px solid #b9c2c7;vertical-align:top;overflow-wrap:anywhere}.internalGuide .guideLines td b{font-size:8pt;font-weight:600}.internalGuide .guideLines td small{display:block;margin-top:1px;color:#61737d;font-size:6.8pt}.guideColItem{width:6%}.guideColCode{width:14%}.guideColPresentation{width:15%}.guideColUnit{width:10%}.guideColQty{width:9%}.guideQty{text-align:center;font-weight:800;white-space:nowrap}.guideBottom{break-inside:avoid;page-break-inside:avoid}.guideObservation{min-height:44px;margin-top:7px;padding:5px 7px;font-size:8pt}.guideObservation p{margin:3px 0 0}.internalGuide footer{margin-top:7px;padding:6px 8px}.internalGuide footer h3{margin:0 0 5px;font-size:9pt}.internalGuide footer>div{grid-template-columns:2fr 1fr 1.5fr;gap:5px 10px}.internalGuide footer p{gap:3px;min-height:30px;font-size:8pt}.internalGuide footer .signature{grid-column:3;grid-row:1/3}.internalGuide footer .signature img{max-width:135px;max-height:55px}.guidePageMark{text-align:center;margin-top:5px;color:#7a878e;font-size:6.8pt}
@media print{.internalGuide{padding:7mm 8mm 6mm;font-size:8.5pt}.internalGuide header{grid-template-columns:125px 1fr 150px;gap:9px;padding-bottom:5px}.internalGuide header img{width:125px}.internalGuide header>div b{font-size:14pt}.internalGuide header>div span{font-size:9pt}.internalGuide header>div small{font-size:7pt}.guideData{margin:6px 0}.guideData p{padding:3px 5px;min-height:22px}.guideData small{font-size:7pt}.guideData b{font-size:8pt}.internalGuide .guideLines th{font-size:7pt;padding:2.5px 3px}.internalGuide .guideLines td{font-size:7.6pt;padding:2.5px 3px;line-height:1.08}.internalGuide .guideLines td b{font-size:7.6pt}.internalGuide .guideLines td small{font-size:6.5pt}.guideObservation{min-height:36px;margin-top:5px;padding:4px 6px}.internalGuide footer{margin-top:5px;padding:5px 7px}.internalGuide footer p{min-height:26px}.guidePageMark{margin-top:3px}}
`;
export default async function DispatchGuidePage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const {data:d}=await supabase.from("dispatches").select("id,internal_number,guide_number,status,observations,recipient_name,recipient_rut,recipient_role,recipient_signature,created_at,delivered_at,installations(name,address,commune,city,region,contracts(name,clients(legal_name,rut))),dispatch_lines(id,required_qty,delivered_qty,materials(name,family,supplier_code,presentation,unit))").eq("id",id).single();if(!d)notFound();
 const installation:any=d.installations,contract:any=installation?.contracts,client:any=contract?.clients;
 return <main className="guidePage"><style dangerouslySetInnerHTML={{__html:guideCss}}/><div className="printControls"><PrintButton/><span>En el diálogo selecciona “Guardar como PDF”.</span></div><article className="internalGuide"><header><Image src="/alemsi-logo.png" width={160} height={62} alt="ALEMSI"/><div><b>ALEMSI</b><span>GUÍA DE ENTREGA DE MATERIALES</span><small>Documento interno/logístico - No constituye DTE tributario del SII</small></div><section><b>N.º interno</b><strong>{d.internal_number||d.guide_number}</strong><span>Fecha: {fmt(d.created_at)}</span></section></header><div className="guideData"><p><small>Cliente</small><b>{client?.legal_name||"—"}</b></p><p><small>RUT cliente</small><b>{client?.rut||"—"}</b></p><p><small>Contrato</small><b>{contract?.name||"—"}</b></p><p><small>Instalación</small><b>{installation?.name||"—"}</b></p><p className="guideWide"><small>Dirección de entrega</small><b>{[installation?.address,installation?.commune,installation?.city,installation?.region].filter(Boolean).join(" · ")||"—"}</b></p></div><table className="guideLines"><colgroup><col className="guideColItem"/><col className="guideColCode"/><col/><col className="guideColPresentation"/><col className="guideColUnit"/><col className="guideColQty"/></colgroup><thead><tr><th>N.º</th><th>Código</th><th>Descripción del material</th><th>Presentación</th><th>Unidad</th><th>Cant.</th></tr></thead><tbody>{(d.dispatch_lines||[]).map((l:any,index:number)=><tr key={l.id}><td>{index+1}</td><td>{l.materials?.supplier_code||"—"}</td><td><b>{l.materials?.name||"Material"}</b>{l.materials?.family&&<small>{l.materials.family}</small>}</td><td>{l.materials?.presentation||"—"}</td><td>{l.materials?.unit||"—"}</td><td className="guideQty">{Number(l.required_qty)}</td></tr>)}</tbody></table><div className="guideBottom"><div className="guideObservation"><b>Observaciones</b><p>{d.observations||"Sin observaciones"}</p></div><footer><h3>RECIBÍ CONFORME</h3><div><p><small>Nombre</small><b>{d.recipient_name||"________________________________"}</b></p><p><small>RUT</small><b>{d.recipient_rut||"________________"}</b></p><p><small>Cargo / receptor</small><b>{d.recipient_role||"________________"}</b></p><p><small>Fecha / hora</small><b>{d.delivered_at?`${fmt(d.delivered_at)} · ${new Intl.DateTimeFormat("es-CL",{timeZone:"America/Santiago",hour:"2-digit",minute:"2-digit"}).format(new Date(d.delivered_at))}`:"____-____-________ · ____:____"}</b></p><p className="signature"><small>Firma</small>{d.recipient_signature?<img src={d.recipient_signature} alt="Firma receptor"/>:<b>________________________</b>}</p></div></footer></div><div className="guidePageMark">Guía interna ALEMSI · {d.internal_number||d.guide_number}</div></article></main>;
}
