import JSZip from "jszip";
import {NextResponse} from "next/server";
import {createClient} from "@/lib/supabase/server";
export const runtime="nodejs";
const esc=(v:unknown)=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
const money=(v:unknown)=>Number(v||0);
const dateTime=(v:unknown)=>{if(!v)return {date:"",time:""};const d=new Date(String(v));if(Number.isNaN(d.getTime()))return {date:String(v),time:""};return {date:new Intl.DateTimeFormat("es-CL",{dateStyle:"short",timeZone:"America/Santiago"}).format(d),time:new Intl.DateTimeFormat("es-CL",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"America/Santiago"}).format(d)}};
const cell=(v:unknown,style=0)=>typeof v==="number"?`<c s="${style}"><v>${v}</v></c>`:`<c t="inlineStr" s="${style}"><is><t xml:space="preserve">${esc(v)}</t></is></c>`;
export async function GET(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"Sesión requerida"},{status:401});
 const {data:profile}=await supabase.from("user_profiles").select("role,active").eq("id",user.id).single();if(!profile?.active||!["Gerencia","Finanzas"].includes(profile.role))return NextResponse.json({error:"Sin permiso para exportar rendiciones"},{status:403});
 const {data:renditions,error}=await supabase.from("renditions").select("id,folio,person_rut,person_name,period_start,period_end,status,previous_balance,company_funds,total_presented,total_authorized,amount_paid,observations,review_observation,submitted_at,reviewed_at,reviewed_by,paid_at,paid_by,payment_observation,payment_document_id,created_at").neq("status","Borrador").order("created_at",{ascending:true});if(error)throw new Error(error.message);
 const ids=(renditions??[]).map(r=>r.id);const {data:expenses,error:expenseError}=ids.length?await supabase.from("rendition_expenses").select("id,rendition_id,expense_date,category,document_type,document_number,provider_name,provider_rut,description,presented_amount,authorized_amount,review_observation,review_status,reviewed_by,reviewed_at,created_at").in("rendition_id",ids).order("created_at",{ascending:true}):{data:[] as any[],error:null};if(expenseError)throw new Error(expenseError.message);
 const userIds=Array.from(new Set<string>((renditions??[]).flatMap(r=>[r.reviewed_by,r.paid_by]).concat((expenses??[]).map(e=>e.reviewed_by)).filter((id):id is string=>Boolean(id))));const names=new Map<string,string>();if(userIds.length){const {data:users}=await supabase.from("user_profiles").select("id,full_name").in("id",userIds);for(const u of users??[])names.set(u.id,u.full_name||u.id);}
 const byRendition=new Map<string,any[]>();for(const e of expenses??[]){const list=byRendition.get(e.rendition_id)??[];list.push(e);byRendition.set(e.rendition_id,list);}
 const headers=["ITEM","TIPO","Fecha","T. DOC","N. DOC","RAZÓN SOCIAL","Descripción","MONTO","OBSERVACIÓN","APROBAR","OBS","RECHAZA","N° RENDICIÓN","RUT QUIEN RINDE","NOMBRE QUIEN RINDE","MOTIVO RENDICIÓN","MONTO RENDICIÓN","MONTO AUTORIZADO RENDICIÓN","FECHA DESDE","FECHA HASTA","ESTADO RENDICIÓN","FECHA ENVÍO","FECHA APROBACIÓN","HORA APROBACIÓN","QUIÉN APROBÓ/REVISÓ","FECHA REVISIÓN ITEM","HORA REVISIÓN ITEM","QUIÉN REVISÓ ITEM","FONDOS / CAJA CHICA","SALDO ANTERIOR","MONTO PAGADO","FECHA PAGO","HORA PAGO","QUIÉN REGISTRÓ PAGO","REF. PAGO","OBSERVACIÓN PAGO"];
 const rows:any[][]=[];for(const r of renditions??[]){const approval=dateTime(r.reviewed_at),payment=dateTime(r.paid_at);const items=byRendition.get(r.id)??[];if(!items.length)items.push({});items.forEach((e:any,i:number)=>{const itemReview=dateTime(e.reviewed_at);rows.push([i+1,e.category||"",e.expense_date||"",e.document_type||"",e.document_number||"",e.provider_name||"",e.description||"",money(e.presented_amount),e.review_observation||"",e.review_status==="Aprobada"?money(e.authorized_amount):"",e.review_status==="Observada"?"OBS":"",e.review_status==="Rechazada"?"RECHAZADA":"",r.folio||"",r.person_rut||"",r.person_name||"",r.observations||"",money(r.total_presented),money(r.total_authorized),r.period_start||"",r.period_end||"",r.status||"",dateTime(r.submitted_at).date,approval.date,approval.time,names.get(r.reviewed_by)||"",itemReview.date,itemReview.time,names.get(e.reviewed_by)||"",money(r.company_funds),money(r.previous_balance),money(r.amount_paid),payment.date,payment.time,names.get(r.paid_by)||"",r.payment_document_id||"",r.payment_observation||""]);});}
 const all=[headers,...rows];const sheetRows=all.map((row,ri)=>`<row r="${ri+1}">${row.map(v=>cell(v,ri===0?1:0)).join("")}</row>`).join("");
 const cols=headers.map((_,i)=>`<col min="${i+1}" max="${i+1}" width="${[7,22,12,12,14,28,34,14,30,14,10,12,20,18,26,34,18,20,14,14,18,14,18,16,28,18,16,28,18,16,16,14,12,28,38,34][i]}" customWidth="1"/>`).join("");
 const zip=new JSZip();zip.file("[Content_Types].xml",`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>`);
 zip.folder("_rels")!.file(".rels",`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`);
 zip.folder("xl")!.file("workbook.xml",`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Rendiciones" sheetId="1" r:id="rId1"/></sheets></workbook>`);
 zip.folder("xl")!.folder("_rels")!.file("workbook.xml.rels",`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`);
 zip.folder("xl")!.file("styles.xml",`<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Arial"/></font><font><b/><sz val="11"/><name val="Arial"/></font></fonts><fills count="1"><fill><patternFill patternType="none"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="2"><xf fontId="0" fillId="0" borderId="0"/><xf fontId="1" fillId="0" borderId="0" applyFont="1"/></cellXfs></styleSheet>`);
 zip.folder("xl")!.folder("worksheets")!.file("sheet1.xml",`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${cols}</cols><sheetData>${sheetRows}</sheetData><autoFilter ref="A1:AJ${all.length}"/></worksheet>`);
 const buffer=await zip.generateAsync({type:"uint8array",compression:"DEFLATE"});const stamp=new Date().toISOString().slice(0,10);return new NextResponse(Buffer.from(buffer),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":`attachment; filename="rendiciones-alemsi-${stamp}.xlsx"`,"Cache-Control":"no-store"}});
}
