"use client";
import {useState} from "react";
import type {Campaign,ClientProfile,LocalPurchase,MaterialState,Product,Survey,SurveyLine} from "@/lib/materiales-domain";
import {activeCampaign,campaignSurveys,clp,isoDate,now,uid} from "@/lib/materiales-store";
import {Progress} from "../Common";
export default function SurveyModule({state,setState,profile,products}:{state:MaterialState;setState:(x:MaterialState)=>void;profile:ClientProfile;products:Product[]}){
 const c=activeCampaign(state,profile.id),[open,setOpen]=useState<string|null>(null),inst=profile.installations.filter(i=>i.active!==false),surveys=campaignSurveys(state,c),expected=c?.expectedInstallationIds||inst.map(i=>i.id),doneIds=new Set(surveys.filter(s=>s.status==="Confirmado").map(s=>s.installationId)),done=expected.filter(x=>doneIds.has(x)).length;
 const start=()=>setState({...state,campaigns:[{id:uid("camp"),profileId:profile.id,label:`Levantamiento ${isoDate()}`,createdAt:now(),status:"Abierta",expectedInstallationIds:inst.map(i=>i.id)},...state.campaigns]});
 const close=()=>c&&done===expected.length&&setState({...state,campaigns:state.campaigns.map(x=>x.id===c.id?{...x,status:"Cerrada",closedAt:now()}:x)});
 return <><h1>Levantamiento</h1><p className="lead">La supervisora registra únicamente el remanente físico.</p>{!c?<div className="actionCard"><h2>Sin campaña activa</h2><button className="btn primary large" onClick={start}>Iniciar campaña</button></div>:<><Progress done={done} total={expected.length}/><div className="mobileCards">{inst.filter(i=>expected.includes(i.id)).map(i=>{const s=surveys.find(x=>x.installationId===i.id);return <div className="installCard" key={i.id}><div><b>{i.name}</b><span>{i.commune}</span><small>{i.address}</small></div><span className={`pill ${s?"ok":"warn"}`}>{s?"Completado":"Pendiente"}</span><button className="btn primary large" disabled={c.status==="Cerrada"} onClick={()=>setOpen(i.id)}>{s?"Revisar":"Iniciar levantamiento"}</button></div>})}</div>{c.status==="Abierta"&&done===expected.length&&<div className="actionCard success"><h2>100% completado</h2><button className="btn primary large" onClick={close}>Cerrar levantamiento</button></div>}</>}{open&&c&&<SurveyEditor state={state} setState={setState} profile={profile} products={products} campaign={c} installationId={open} onClose={()=>setOpen(null)}/>}</>;
}
function SurveyEditor({state,setState,profile,products,campaign,installationId,onClose}:{state:MaterialState;setState:(x:MaterialState)=>void;profile:ClientProfile;products:Product[];campaign:Campaign;installationId:string;onClose:()=>void}){
 const inst=profile.installations.find(i=>i.id===installationId)!,existing=state.surveys.find(s=>s.campaignId===campaign.id&&s.installationId===installationId),auth=state.contractMaterials.filter(x=>x.profileId===profile.id&&x.authorized&&(!x.installationId||x.installationId===installationId));
 const [lines,setLines]=useState<SurveyLine[]>(auth.map(a=>{const p=products.find(x=>x.id===a.productId)!;const old=existing?.lines.find(x=>x.productId===a.productId);return old||{productId:a.productId,productName:p?.name||a.productId,unitPrice:p?.price||0,authorizedQty:a.authorizedQty,remainder:0,shortage:a.authorizedQty,lineNet:a.authorizedQty*(p?.price||0)}})),[remote,setRemote]=useState(existing?.remoteCandidate||inst.logisticsMode==="Remota"),[note,setNote]=useState(existing?.logisticsNote||"");
 const upd=(i:number,v:number)=>setLines(ls=>ls.map((l,idx)=>idx===i?{...l,remainder:Math.max(0,v),shortage:Math.max(0,l.authorizedQty-Math.max(0,v)),lineNet:Math.max(0,l.authorizedQty-Math.max(0,v))*l.unitPrice}:l)),net=lines.reduce((s,l)=>s+l.lineNet,0);
 const confirm=()=>{const sid=existing?.id||uid("lev"),survey:Survey={id:sid,campaignId:campaign.id,profileId:profile.id,installationId,installationName:inst.name,supervisor:"Supervisión",date:isoDate(),status:"Confirmado",remoteCandidate:remote,logisticsNote:note,lines,shortageNet:net};let local=state.localPurchases.filter(x=>x.surveyId!==sid);if(remote&&net>0){const lp:LocalPurchase={id:uid("local"),surveyId:sid,profileId:profile.id,installationId,installationName:inst.name,shortageNet:net,reason:note||"Evaluar costo de traslado versus carencia",requestedBy:"Supervisión",status:"Solicitada",maxAuthorized:0,mode:"Anticipo",actualNet:0};local=[lp,...local]}setState({...state,surveys:[survey,...state.surveys.filter(s=>!(s.campaignId===campaign.id&&s.installationId===installationId))],localPurchases:local});onClose()};
 return <div className="modalBg"><div className="modal"><div className="modalHead"><div><h2>{inst.name}</h2><p>{inst.commune}</p></div><button className="btn" onClick={onClose}>Cerrar</button></div>{!auth.length?<div className="notice warning">No hay materiales autorizados. Configúralos primero en Maestro.</div>:<><div className="countList">{lines.map((l,i)=><div className="countCard" key={l.productId}><div className="countTop"><div><b>{l.productName}</b><small>Base: {l.authorizedQty}</small></div><span className={`shortage ${l.shortage>0?"has":""}`}>Carencia {l.shortage}</span></div><label>¿Cuánto queda físicamente?</label><div className="stepper"><button onClick={()=>upd(i,l.remainder-1)}>−</button><input type="number" min={0} value={l.remainder} onChange={e=>upd(i,Number(e.target.value)||0)}/><button onClick={()=>upd(i,l.remainder+1)}>+</button></div></div>)}</div><div className="actionCard"><label className="choice"><input type="checkbox" checked={remote} onChange={e=>setRemote(e.target.checked)}/><span><b>Evaluar compra local</b><small>Solo si el traslado puede ser desproporcionado.</small></span></label>{remote&&<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Observación logística"/>}</div><div className="summarySticky"><div><span>Carencia neta</span><b>{clp(net)}</b></div><button className="btn primary large" onClick={confirm}>Confirmar levantamiento</button></div></>}</div></div>;
}
