import {notFound,redirect} from "next/navigation";
import Link from "next/link";
import {createClient} from "@/lib/supabase/server";
import ExpenseForm from "../ExpenseForm";
import {editRenditionExpense,markRenditionPaid,reviewExpense,submitRendition} from "../actions";
const money=(v:number|null|undefined)=>Number(v||0).toLocaleString("es-CL");
const cats=["Estacionamiento","Alojamiento","Colación/Alimentación","Compras/Materiales","Insumos varios","Movilización/Uber","Peajes","Otros"];
function badge(s:string|null|undefined){const v=(s||"").toUpperCase();if(["APROBADA","APROBADO","PAGADA","PAGADO"].includes(v))return "renditionBadge renditionBadgeOk";if(["RECHAZADA","RECHAZADO"].includes(v))return "renditionBadge renditionBadgeError";if(["ENVIADA","OBSERVADA","PENDIENTE"].includes(v))return "renditionBadge renditionBadgeWarning";return "renditionBadge renditionBadgeNeutral";}
export default async function Page({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const {data:p}=await supabase.from("user_profiles").select("id,role,active").eq("id",user.id).single();if(!p?.active)redirect("/");
 const {data:access}=await supabase.rpc("has_additional_service_access",{p_service_code:"rendiciones"});const admin=p.role==="Admin Total";if(!access&&!admin)redirect("/");
 const manager=["Admin Total","Finanzas","Gerencia"].includes(p.role);
 const {data:r}=await supabase.from("renditions").select("id,folio,creator_user_id,person_name,person_rut,period_start,period_end,status,previous_balance,company_funds,total_presented,total_authorized,amount_paid,review_observation,rendition_expenses(id,expense_date,category,document_type,provider_name,provider_rut,document_number,description,presented_amount,authorized_amount,review_observation,review_status,document_id)").eq("id",id).single();if(!r)notFound();if(!manager&&r.creator_user_id!==user.id)notFound();
 const ids=(r.rendition_expenses??[]).map((g:any)=>g.document_id).filter(Boolean);const docs=new Map<string,string>();if(ids.length){const {data:d}=await supabase.from("documents").select("id,storage_path").in("id",ids);for(const x of d??[]){const {data:s}=await supabase.storage.from("rendition-documents").createSignedUrl(x.storage_path,3600);if(s?.signedUrl)docs.set(x.id,s.signedUrl);}}
 const finance=p.role==="Finanzas",gerencia=p.role==="Gerencia";const canEdit=r.creator_user_id===user.id&&["Borrador","Observada"].includes(r.status);
 return <main className="renditionsPage renditionDetailPage"><header className="renditionsHero"><div><div className="renditionsEyebrow">ALEMSI · EXPEDIENTE</div><h1>{r.folio}</h1><p>{r.person_name} · {r.period_start} a {r.period_end}</p></div><div className="renditionsHeroActions"><span className={badge(r.status)}>{r.status}</span><Link className="renditionBtn renditionBtnGhost" href="/rendiciones">← Volver</Link></div></header>
 {r.review_observation&&<section className="renditionDetailAlert"><b>Observación</b><p>{r.review_observation}</p></section>}
 <section className="renditionMoneyGrid renditionDetailMoney"><div><span>Fondos</span><strong>$ {money(r.company_funds)}</strong></div><div><span>Saldo anterior</span><strong>$ {money(r.previous_balance)}</strong></div><div><span>Presentado</span><strong>$ {money(r.total_presented)}</strong></div><div><span>Autorizado</span><strong>$ {money(r.total_authorized)}</strong></div><div><span>Pagado</span><strong>$ {money(r.amount_paid)}</strong></div></section>
 <section className="renditionDetailSection"><div className="renditionsBoardHead"><div><h2>Gastos y comprobantes</h2><p>{r.rendition_expenses?.length||0} gasto(s)</p></div></div><div className="renditionExpenseList">{(r.rendition_expenses??[]).map((g:any)=><article key={g.id} className="renditionExpense"><div className="renditionExpenseMain"><div><span className="renditionLabel">Fecha</span><strong>{g.expense_date}</strong></div><div><span className="renditionLabel">Documento</span><strong>{g.document_type} {g.document_number||""}</strong><small>{g.provider_name||"—"}</small></div><div><span className="renditionLabel">Descripción</span><strong>{g.description}</strong><small>{g.category}</small></div><div className="renditionExpenseAmount"><span className="renditionLabel">Importe</span><strong>$ {money(g.presented_amount)}</strong></div><div><span className={badge(g.review_status||"Pendiente")}>{g.review_status||"Pendiente"}</span></div></div><div className="renditionExpenseActions">
 {g.document_id&&docs.get(g.document_id)?<a className="renditionBtn renditionBtnOutline" href={docs.get(g.document_id)} target="_blank" rel="noreferrer">Ver comprobante</a>:<span>Sin respaldo</span>}{g.review_observation&&<div className="renditionObservation"><b>Observación:</b> {g.review_observation}</div>}
 {canEdit&&<details className="renditionInlineDetails"><summary>Editar gasto</summary><form action={editRenditionExpense} className="renditionCompactForm"><input type="hidden" name="rendition_id" value={r.id}/><input type="hidden" name="expense_id" value={g.id}/><label>Fecha<input name="expense_date" type="date" defaultValue={g.expense_date} required/></label><label>Tipo<select name="document_type" defaultValue={g.document_type}>{["Factura","Boleta","Transferencia","Otro","Sin documento"].map(x=><option key={x}>{x}</option>)}</select></label><label>N.º documento<input name="document_number" defaultValue={g.document_number||""}/></label><label>Proveedor<input name="provider_name" defaultValue={g.provider_name||""}/></label><label>RUT<input name="provider_rut" defaultValue={g.provider_rut||""}/></label><label>Categoría<select name="category" defaultValue={g.category}>{cats.map(x=><option key={x}>{x}</option>)}</select></label><label className="renditionFieldWide">Descripción<input name="description" defaultValue={g.description} required/></label><label>Importe<input name="presented_amount" type="number" min="1" defaultValue={Number(g.presented_amount)} required/></label><div className="renditionFieldWide"><button className="renditionBtn renditionBtnPrimary">Guardar cambios</button></div></form></details>}
 {manager&&r.status==="Enviada"&&<form action={reviewExpense} className="renditionReviewForm"><input type="hidden" name="rendition_id" value={r.id}/><input type="hidden" name="expense_id" value={g.id}/><textarea name="observation" placeholder="Observación"/>{!gerencia&&<input name="authorized_amount" type="number" min="0" max={Number(g.presented_amount)} defaultValue={Number(g.presented_amount)}/>}<div className="renditionDecisionButtons"><button className="renditionBtn renditionBtnWarning" name="decision" value="OBSERVE">Observar</button>{!gerencia&&<><button className="renditionBtn renditionBtnSuccess" name="decision" value="APPROVE">Aprobar</button><button className="renditionBtn renditionBtnDanger" name="decision" value="REJECT">Rechazar</button></>}</div></form>}
 </div></article>)}{(r.rendition_expenses??[]).length===0&&<div className="renditionEmpty">Sin gastos registrados.</div>}</div></section>
 {canEdit&&<section className="renditionDetailSection"><details className="renditionAddExpense"><summary>+ Agregar comprobante</summary><div className="renditionAddExpenseBody"><ExpenseForm renditionId={r.id}/></div></details><form action={submitRendition} className="renditionSubmit"><input type="hidden" name="rendition_id" value={r.id}/><button className="renditionBtn renditionBtnPrimary" disabled={(r.rendition_expenses?.length||0)===0}>{(r.rendition_expenses?.length||0)===0?"Agrega un comprobante":"Enviar a Finanzas"}</button></form></section>}
 {(finance||admin)&&r.status==="Aprobada"&&Number(r.total_authorized)>0&&<form action={markRenditionPaid} className="renditionPayment renditionDetailSection"><h3>Registrar pago</h3><input type="hidden" name="rendition_id" value={r.id}/><label>Monto<input name="amount_paid" type="number" min="1" max={Number(r.total_authorized)} defaultValue={Number(r.total_authorized)} required/></label><label>Referencia<input name="payment_observation"/></label><button className="renditionBtn renditionBtnSuccess">Marcar como pagada</button></form>}
 </main>;
}