import JSZip from "jszip";
import {createClient} from "@/lib/supabase/server";

export const runtime="nodejs";
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]!));
const safe=(v:unknown)=>String(v||"guia").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/^-+|-+$/g,"").slice(0,90)||"guia";
const fmt=(v:string)=>new Intl.DateTimeFormat("es-CL",{timeZone:"America/Santiago",dateStyle:"short",timeStyle:"short"}).format(new Date(v));
function relation(v:any){return Array.isArray(v)?v[0]:v}

function guideHtml(d:any,deliverer:string){const installation=relation(d.installations),contract=relation(installation?.contracts),client=relation(contract?.clients);const rows=(d.dispatch_lines||[]).map((l:any,i:number)=>`<tr><td>${i+1}</td><td>${esc(l.materials?.supplier_code||"—")}</td><td>${esc(l.materials?.name||"Material")}</td><td>${esc(l.materials?.presentation||"—")}</td><td>${esc(l.materials?.unit||"—")}</td><td>${esc(l.delivered_qty||l.required_qty||0)}</td></tr>`).join("");return `<!doctype html><html lang="es"><head><meta charset="utf-8"><title>${esc(d.internal_number||d.guide_number||"Guía")}</title><style>body{font-family:Arial,sans-serif;color:#173650;margin:32px}h1{font-size:22px}.head,.data,.receive{border:1px solid #c8dce8;border-radius:12px;padding:14px;margin:12px 0}.data{display:grid;grid-template-columns:1fr 1fr;gap:8px}table{width:100%;border-collapse:collapse;margin:16px 0}th,td{border:1px solid #c8dce8;padding:7px;text-align:left;font-size:12px}.signature{max-width:280px;max-height:100px;border-bottom:1px solid #8aa0ad}.muted{color:#607887;font-size:12px}</style></head><body><div class="head"><h1>ALEMSI · GUÍA DE ENTREGA DE MATERIALES</h1><b>${esc(d.internal_number||d.guide_number||"Guía interna")}</b><div class="muted">Documento interno/logístico. Respaldo de entrega.</div></div><div class="data"><div><b>Cliente:</b> ${esc(client?.legal_name||"—")}</div><div><b>RUT:</b> ${esc(client?.rut||"—")}</div><div><b>Contrato:</b> ${esc(contract?.name||"—")}</div><div><b>Instalación:</b> ${esc(installation?.name||"—")}</div><div style="grid-column:1/-1"><b>Dirección:</b> ${esc([installation?.address,installation?.commune,installation?.city,installation?.region].filter(Boolean).join(" · ")||"—")}</div><div style="grid-column:1/-1"><b>Campaña / período:</b> ${esc(String(d.observations||"").replace(/^CAMPAÑA:[^·]+·?\s*/,""))}</div><div><b>Responsable entrega:</b> ${esc(deliverer||"—")}</div><div><b>Fecha entrega:</b> ${d.delivered_at?esc(fmt(d.delivered_at)):"—"}</div></div><table><thead><tr><th>N.º</th><th>Código</th><th>Material</th><th>Presentación</th><th>Unidad</th><th>Cantidad</th></tr></thead><tbody>${rows}</tbody></table><div class="receive"><h2>RECIBÍ CONFORME</h2><p><b>Nombre:</b> ${esc(d.recipient_name||"—")}</p><p><b>RUT:</b> ${esc(d.recipient_rut||"—")}</p><p><b>Cargo:</b> ${esc(d.recipient_role||"—")}</p><p><b>Correo informado en terreno:</b> ${esc(d.recipient_email||"—")}</p>${d.recipient_signature?`<p><b>Firma:</b><br><img class="signature" src="${esc(d.recipient_signature)}" alt="Firma receptor"></p>`:"<p><b>Firma:</b> No registrada</p>"}</div></body></html>`}

export async function GET(request:Request){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return new Response("Sesión no válida",{status:401});
 const {data:profile}=await supabase.from("user_profiles").select("role,active").eq("id",user.id).single();if(!profile?.active||!["Admin Total","Gerencia","Admin","Finanzas","Bodega"].includes(profile.role))return new Response("No autorizado",{status:403});
 const url=new URL(request.url),month=url.searchParams.get("month")||new Date().toISOString().slice(0,7),clientId=url.searchParams.get("client_id")||"",installationId=url.searchParams.get("installation_id")||"";
 if(!/^\d{4}-\d{2}$/.test(month))return new Response("Periodo inválido",{status:400});
 const [year,mon]=month.split("-").map(Number),start=`${month}-01T00:00:00-03:00`,next=mon===12?`${year+1}-01-01T00:00:00-03:00`:`${year}-${String(mon+1).padStart(2,"0")}-01T00:00:00-03:00`;
 let query=supabase.from("dispatches").select("id,internal_number,guide_number,status,observations,recipient_name,recipient_email,recipient_rut,recipient_role,recipient_signature,delivered_by,delivered_at,installation_id,installations(id,name,address,commune,city,region,contracts(id,name,clients(id,legal_name,rut))),dispatch_lines(id,required_qty,delivered_qty,materials(name,supplier_code,presentation,unit))").gte("delivered_at",start).lt("delivered_at",next).not("recipient_signature","is",null).order("delivered_at",{ascending:true});
 if(installationId)query=query.eq("installation_id",installationId);const {data,error}=await query;if(error)return new Response(error.message,{status:500});
 let rows=(data||[]).filter((d:any)=>{if(!clientId)return true;const c=relation(relation(d.installations)?.contracts)?.clients;return String(relation(c)?.id||"")===clientId;});if(!rows.length)return new Response("No hay guías firmadas para los filtros seleccionados",{status:404});
 const delivererIds=[...new Set(rows.map((d:any)=>d.delivered_by).filter(Boolean))];const {data:profiles}=delivererIds.length?await supabase.from("user_profiles").select("id,full_name,email").in("id",delivererIds):{data:[] as any[]};const names=new Map((profiles||[]).map((p:any)=>[p.id,p.full_name||p.email||p.id]));
 const zip=new JSZip();const manifest=["guia;fecha;cliente;contrato;instalacion;receptor;correo;responsable_entrega"];
 for(const d of rows as any[]){const i=relation(d.installations),c=relation(i?.contracts),cl=relation(c?.clients),name=`${safe(d.internal_number||d.guide_number)}-${safe(i?.name)}.html`;zip.file(name,guideHtml(d,String(names.get(d.delivered_by)||"")));manifest.push([d.internal_number||d.guide_number||"",d.delivered_at?fmt(d.delivered_at):"",cl?.legal_name||"",c?.name||"",i?.name||"",d.recipient_name||"",d.recipient_email||"",names.get(d.delivered_by)||""].map(v=>`"${String(v).replaceAll('"','""')}"`).join(";"));}
 zip.file("indice-entregas.csv",manifest.join("\n"));const bytes=await zip.generateAsync({type:"uint8array",compression:"DEFLATE",compressionOptions:{level:6}});return new Response(Buffer.from(bytes),{headers:{"Content-Type":"application/zip","Content-Disposition":`attachment; filename="guias-firmadas-${month}.zip"`,`Cache-Control`:"no-store"}});
}
